/*******************************************************************************
 *  This file is AUTOMATICALLY GENERATED by:
 *  ../tools/fortran_wrappers.pl ../include/magma_tally4_d.i
 *  Do not edit.
 ******************************************************************************/

#include <stdint.h>  // for uintptr_t

#include "magma_tally4.h"
#include "magma_tally4_mangling.h"

/*
 * typedef comming from fortran.h file provided in CUDADIR/src directory
 * it will probably change with future release of CUDA when they use 64 bit addresses
 */
typedef size_t devptr_t;

#ifdef PGI_FORTRAN
    #define magma_tally4_idevptr(ptr_) ((int*)               (ptr_))
    #define magma_tally4_zdevptr(ptr_) ((magma_tally4DoubleComplex*)(ptr_))
    #ifndef magma_tally4_cdevptr
    #define magma_tally4_cdevptr(ptr_) ((magma_tally4FloatComplex*) (ptr_))
    #endif
    #ifndef magma_tally4_ddevptr
    #define magma_tally4_ddevptr(ptr_) ((double*)            (ptr_))
    #endif
    #ifndef magma_tally4_sdevptr
    #define magma_tally4_sdevptr(ptr_) ((float*)             (ptr_))
    #endif
#else
    #define magma_tally4_idevptr(ptr_) ((int*)               (uintptr_t)(*(ptr_)))
    #define magma_tally4_zdevptr(ptr_) ((magma_tally4DoubleComplex*)(uintptr_t)(*(ptr_)))
    #ifndef magma_tally4_cdevptr
    #define magma_tally4_cdevptr(ptr_) ((magma_tally4FloatComplex*) (uintptr_t)(*(ptr_)))
    #endif
    #ifndef magma_tally4_ddevptr
    #define magma_tally4_ddevptr(ptr_) ((double*)            (uintptr_t)(*(ptr_)))
    #endif
    #ifndef magma_tally4_sdevptr
    #define magma_tally4_sdevptr(ptr_) ((float*)             (uintptr_t)(*(ptr_)))
    #endif
#endif

#ifdef __cplusplus
extern "C" {
#endif

#define magma_tally4f_get_dlaex3_m_nb FORTRAN_NAME( magma_tally4f_get_dlaex3_m_nb, MAGMA_tally4F_GET_DLAEX3_M_NB )
void magma_tally4f_get_dlaex3_m_nb(
     )
{
    magma_tally4_get_dlaex3_m_nb(
         );
}

#define magma_tally4f_get_dpotrf_nb FORTRAN_NAME( magma_tally4f_get_dpotrf_nb, MAGMA_tally4F_GET_DPOTRF_NB )
magma_tally4_int_t magma_tally4f_get_dpotrf_nb( magma_tally4_int_t *m )
{
    return magma_tally4_get_dpotrf_nb( *m );
}

#define magma_tally4f_get_dgetrf_nb FORTRAN_NAME( magma_tally4f_get_dgetrf_nb, MAGMA_tally4F_GET_DGETRF_NB )
magma_tally4_int_t magma_tally4f_get_dgetrf_nb( magma_tally4_int_t *m )
{
    return magma_tally4_get_dgetrf_nb( *m );
}

#define magma_tally4f_get_dgetri_nb FORTRAN_NAME( magma_tally4f_get_dgetri_nb, MAGMA_tally4F_GET_DGETRI_NB )
magma_tally4_int_t magma_tally4f_get_dgetri_nb( magma_tally4_int_t *m )
{
    return magma_tally4_get_dgetri_nb( *m );
}

#define magma_tally4f_get_dgeqp3_nb FORTRAN_NAME( magma_tally4f_get_dgeqp3_nb, MAGMA_tally4F_GET_DGEQP3_NB )
magma_tally4_int_t magma_tally4f_get_dgeqp3_nb( magma_tally4_int_t *m )
{
    return magma_tally4_get_dgeqp3_nb( *m );
}

#define magma_tally4f_get_dgeqrf_nb FORTRAN_NAME( magma_tally4f_get_dgeqrf_nb, MAGMA_tally4F_GET_DGEQRF_NB )
magma_tally4_int_t magma_tally4f_get_dgeqrf_nb( magma_tally4_int_t *m )
{
    return magma_tally4_get_dgeqrf_nb( *m );
}

#define magma_tally4f_get_dgeqlf_nb FORTRAN_NAME( magma_tally4f_get_dgeqlf_nb, MAGMA_tally4F_GET_DGEQLF_NB )
magma_tally4_int_t magma_tally4f_get_dgeqlf_nb( magma_tally4_int_t *m )
{
    return magma_tally4_get_dgeqlf_nb( *m );
}

#define magma_tally4f_get_dgehrd_nb FORTRAN_NAME( magma_tally4f_get_dgehrd_nb, MAGMA_tally4F_GET_DGEHRD_NB )
magma_tally4_int_t magma_tally4f_get_dgehrd_nb( magma_tally4_int_t *m )
{
    return magma_tally4_get_dgehrd_nb( *m );
}

#define magma_tally4f_get_dsytrd_nb FORTRAN_NAME( magma_tally4f_get_dsytrd_nb, MAGMA_tally4F_GET_DSYTRD_NB )
magma_tally4_int_t magma_tally4f_get_dsytrd_nb( magma_tally4_int_t *m )
{
    return magma_tally4_get_dsytrd_nb( *m );
}

#define magma_tally4f_get_dsytrf_nb FORTRAN_NAME( magma_tally4f_get_dsytrf_nb, MAGMA_tally4F_GET_DSYTRF_NB )
magma_tally4_int_t magma_tally4f_get_dsytrf_nb( magma_tally4_int_t *m )
{
    return magma_tally4_get_dsytrf_nb( *m );
}

#define magma_tally4f_get_dsytrf_nopiv_nb FORTRAN_NAME( magma_tally4f_get_dsytrf_nopiv_nb, MAGMA_tally4F_GET_DSYTRF_NOPIV_NB )
magma_tally4_int_t magma_tally4f_get_dsytrf_nopiv_nb( magma_tally4_int_t *m )
{
    return magma_tally4_get_dsytrf_nopiv_nb( *m );
}

#define magma_tally4f_get_dgelqf_nb FORTRAN_NAME( magma_tally4f_get_dgelqf_nb, MAGMA_tally4F_GET_DGELQF_NB )
magma_tally4_int_t magma_tally4f_get_dgelqf_nb( magma_tally4_int_t *m )
{
    return magma_tally4_get_dgelqf_nb( *m );
}

#define magma_tally4f_get_dgebrd_nb FORTRAN_NAME( magma_tally4f_get_dgebrd_nb, MAGMA_tally4F_GET_DGEBRD_NB )
magma_tally4_int_t magma_tally4f_get_dgebrd_nb( magma_tally4_int_t *m )
{
    return magma_tally4_get_dgebrd_nb( *m );
}

#define magma_tally4f_get_dsygst_nb FORTRAN_NAME( magma_tally4f_get_dsygst_nb, MAGMA_tally4F_GET_DSYGST_NB )
magma_tally4_int_t magma_tally4f_get_dsygst_nb( magma_tally4_int_t *m )
{
    return magma_tally4_get_dsygst_nb( *m );
}

#define magma_tally4f_get_dgesvd_nb FORTRAN_NAME( magma_tally4f_get_dgesvd_nb, MAGMA_tally4F_GET_DGESVD_NB )
magma_tally4_int_t magma_tally4f_get_dgesvd_nb( magma_tally4_int_t *m )
{
    return magma_tally4_get_dgesvd_nb( *m );
}

#define magma_tally4f_get_dsygst_nb_m FORTRAN_NAME( magma_tally4f_get_dsygst_nb_m, MAGMA_tally4F_GET_DSYGST_NB_M )
magma_tally4_int_t magma_tally4f_get_dsygst_nb_m( magma_tally4_int_t *m )
{
    return magma_tally4_get_dsygst_nb_m( *m );
}

#define magma_tally4f_get_dbulge_nb FORTRAN_NAME( magma_tally4f_get_dbulge_nb, MAGMA_tally4F_GET_DBULGE_NB )
void magma_tally4f_get_dbulge_nb(
    magma_tally4_int_t *m, magma_tally4_int_t *nbthreads )
{
    magma_tally4_get_dbulge_nb(
        *m, *nbthreads );
}

#define magma_tally4f_dbulge_get_Vblksiz FORTRAN_NAME( magma_tally4f_dbulge_get_Vblksiz, MAGMA_tally4F_DBULGE_GET_VBLKSIZ )
void magma_tally4f_dbulge_get_Vblksiz(
    magma_tally4_int_t *m, magma_tally4_int_t *nb, magma_tally4_int_t *nbthreads )
{
    magma_tally4_dbulge_get_Vblksiz(
        *m, *nb, *nbthreads );
}

#define magma_tally4f_get_dbulge_gcperf FORTRAN_NAME( magma_tally4f_get_dbulge_gcperf, MAGMA_tally4F_GET_DBULGE_GCPERF )
void magma_tally4f_get_dbulge_gcperf(
     )
{
    magma_tally4_get_dbulge_gcperf(
         );
}

#define magma_tally4f_dmove_eig FORTRAN_NAME( magma_tally4f_dmove_eig, MAGMA_tally4F_DMOVE_EIG )
void magma_tally4f_dmove_eig(
    const char* range, magma_tally4_int_t *n,
    double *w,
    magma_tally4_int_t *il,
    magma_tally4_int_t *iu, double *vl, double *vu,
    magma_tally4_int_t *m )
{
    magma_tally4_dmove_eig(
        magma_tally4_range_const(*range), *n,
        w,
        il,
        iu, *vl, *vu,
        m );
}

#define magma_tally4f_dvrange FORTRAN_NAME( magma_tally4f_dvrange, MAGMA_tally4F_DVRANGE )
void magma_tally4f_dvrange(
    magma_tally4_int_t *k,
    double *d,
    magma_tally4_int_t *il,
    magma_tally4_int_t *iu, double *vl, double *vu )
{
    magma_tally4_dvrange(
        *k,
        d,
        il,
        iu, *vl, *vu );
}

#define magma_tally4f_dirange FORTRAN_NAME( magma_tally4f_dirange, MAGMA_tally4F_DIRANGE )
void magma_tally4f_dirange(
    magma_tally4_int_t *k,
    magma_tally4_int_t *indxq,
    magma_tally4_int_t *iil,
    magma_tally4_int_t *iiu, magma_tally4_int_t *il, magma_tally4_int_t *iu )
{
    magma_tally4_dirange(
        *k,
        indxq,
        iil,
        iiu, *il, *iu );
}

#define magma_tally4f_dgebrd FORTRAN_NAME( magma_tally4f_dgebrd, MAGMA_tally4F_DGEBRD )
void magma_tally4f_dgebrd(
    magma_tally4_int_t *m, magma_tally4_int_t *n,
    double *A, magma_tally4_int_t *lda,
    double *d,
    double *e,
    double *tauq,
    double *taup,
    double *work, magma_tally4_int_t *lwork,
    magma_tally4_int_t *info )
{
    magma_tally4_dgebrd(
        *m, *n,
        A, *lda,
        d,
        e,
        tauq,
        taup,
        work, *lwork,
        info );
}

#define magma_tally4f_dgeev FORTRAN_NAME( magma_tally4f_dgeev, MAGMA_tally4F_DGEEV )
void magma_tally4f_dgeev(
    const char* jobvl, const char* jobvr, magma_tally4_int_t *n,
    double *A, magma_tally4_int_t *lda,
    double *wr,
    double *wi,
    double *VL, magma_tally4_int_t *ldvl,
    double *VR, magma_tally4_int_t *ldvr,
    double *work, magma_tally4_int_t *lwork,
    magma_tally4_int_t *info )
{
    magma_tally4_dgeev(
        magma_tally4_vec_const(*jobvl), magma_tally4_vec_const(*jobvr), *n,
        A, *lda,
        wr,
        wi,
        VL, *ldvl,
        VR, *ldvr,
        work, *lwork,
        info );
}

#define magma_tally4f_dgehrd FORTRAN_NAME( magma_tally4f_dgehrd, MAGMA_tally4F_DGEHRD )
void magma_tally4f_dgehrd(
    magma_tally4_int_t *n, magma_tally4_int_t *ilo, magma_tally4_int_t *ihi,
    double *A, magma_tally4_int_t *lda,
    double *tau,
    double *work, magma_tally4_int_t *lwork,
    devptr_t *dT,
    magma_tally4_int_t *info )
{
    magma_tally4_dgehrd(
        *n, *ilo, *ihi,
        A, *lda,
        tau,
        work, *lwork,
        magma_tally4_ddevptr(dT),
        info );
}

#define magma_tally4f_dgehrd2 FORTRAN_NAME( magma_tally4f_dgehrd2, MAGMA_tally4F_DGEHRD2 )
void magma_tally4f_dgehrd2(
    magma_tally4_int_t *n, magma_tally4_int_t *ilo, magma_tally4_int_t *ihi,
    double *A, magma_tally4_int_t *lda,
    double *tau,
    double *work, magma_tally4_int_t *lwork,
    magma_tally4_int_t *info )
{
    magma_tally4_dgehrd2(
        *n, *ilo, *ihi,
        A, *lda,
        tau,
        work, *lwork,
        info );
}

#define magma_tally4f_dgelqf FORTRAN_NAME( magma_tally4f_dgelqf, MAGMA_tally4F_DGELQF )
void magma_tally4f_dgelqf(
    magma_tally4_int_t *m, magma_tally4_int_t *n,
    double *A, magma_tally4_int_t *lda,
    double *tau,
    double *work, magma_tally4_int_t *lwork,
    magma_tally4_int_t *info )
{
    magma_tally4_dgelqf(
        *m, *n,
        A, *lda,
        tau,
        work, *lwork,
        info );
}

#define magma_tally4f_dgeqlf FORTRAN_NAME( magma_tally4f_dgeqlf, MAGMA_tally4F_DGEQLF )
void magma_tally4f_dgeqlf(
    magma_tally4_int_t *m, magma_tally4_int_t *n,
    double *A, magma_tally4_int_t *lda,
    double *tau,
    double *work, magma_tally4_int_t *lwork,
    magma_tally4_int_t *info )
{
    magma_tally4_dgeqlf(
        *m, *n,
        A, *lda,
        tau,
        work, *lwork,
        info );
}

#define magma_tally4f_dgeqp3 FORTRAN_NAME( magma_tally4f_dgeqp3, MAGMA_tally4F_DGEQP3 )
void magma_tally4f_dgeqp3(
    magma_tally4_int_t *m, magma_tally4_int_t *n,
    double *A, magma_tally4_int_t *lda,
    magma_tally4_int_t *jpvt,
    double *tau,
    double *work, magma_tally4_int_t *lwork,
    magma_tally4_int_t *info )
{
    magma_tally4_dgeqp3(
        *m, *n,
        A, *lda,
        jpvt,
        tau,
        work, *lwork,
        info );
}

#define magma_tally4f_dgeqrf FORTRAN_NAME( magma_tally4f_dgeqrf, MAGMA_tally4F_DGEQRF )
void magma_tally4f_dgeqrf(
    magma_tally4_int_t *m, magma_tally4_int_t *n,
    double *A, magma_tally4_int_t *lda,
    double *tau,
    double *work, magma_tally4_int_t *lwork,
    magma_tally4_int_t *info )
{
    magma_tally4_dgeqrf(
        *m, *n,
        A, *lda,
        tau,
        work, *lwork,
        info );
}

#define magma_tally4f_dgeqrf_ooc FORTRAN_NAME( magma_tally4f_dgeqrf_ooc, MAGMA_tally4F_DGEQRF_OOC )
void magma_tally4f_dgeqrf_ooc(
    magma_tally4_int_t *m, magma_tally4_int_t *n,
    double *A, magma_tally4_int_t *lda,
    double *tau,
    double *work, magma_tally4_int_t *lwork,
    magma_tally4_int_t *info )
{
    magma_tally4_dgeqrf_ooc(
        *m, *n,
        A, *lda,
        tau,
        work, *lwork,
        info );
}

#define magma_tally4f_dgeqrf4 FORTRAN_NAME( magma_tally4f_dgeqrf4, MAGMA_tally4F_DGEQRF4 )
void magma_tally4f_dgeqrf4(
    magma_tally4_int_t *ngpu, magma_tally4_int_t *m, magma_tally4_int_t *n,
    double *A, magma_tally4_int_t *lda,
    double *tau,
    double *work, magma_tally4_int_t *lwork,
    magma_tally4_int_t *info )
{
    magma_tally4_dgeqrf4(
        *ngpu, *m, *n,
        A, *lda,
        tau,
        work, *lwork,
        info );
}

#define magma_tally4f_dgesdd FORTRAN_NAME( magma_tally4f_dgesdd, MAGMA_tally4F_DGESDD )
void magma_tally4f_dgesdd(
    const char* jobz, magma_tally4_int_t *m, magma_tally4_int_t *n,
    double *A, magma_tally4_int_t *lda,
    double *s,
    double *U, magma_tally4_int_t *ldu,
    double *VT, magma_tally4_int_t *ldvt,
    double *work, magma_tally4_int_t *lwork,
    magma_tally4_int_t *iwork,
    magma_tally4_int_t *info )
{
    magma_tally4_dgesdd(
        magma_tally4_vec_const(*jobz), *m, *n,
        A, *lda,
        s,
        U, *ldu,
        VT, *ldvt,
        work, *lwork,
        iwork,
        info );
}

#define magma_tally4f_dgesv FORTRAN_NAME( magma_tally4f_dgesv, MAGMA_tally4F_DGESV )
void magma_tally4f_dgesv(
    magma_tally4_int_t *n, magma_tally4_int_t *nrhs,
    double *A, magma_tally4_int_t *lda,
    magma_tally4_int_t *ipiv,
    double *B, magma_tally4_int_t *ldb,
    magma_tally4_int_t *info )
{
    magma_tally4_dgesv(
        *n, *nrhs,
        A, *lda,
        ipiv,
        B, *ldb,
        info );
}

#define magma_tally4f_dgesv_rbt FORTRAN_NAME( magma_tally4f_dgesv_rbt, MAGMA_tally4F_DGESV_RBT )
void magma_tally4f_dgesv_rbt(
    const char* ref, magma_tally4_int_t *n, magma_tally4_int_t *nrhs,
    double *A, magma_tally4_int_t *lda,
    double *B, magma_tally4_int_t *ldb,
    magma_tally4_int_t *info )
{
    magma_tally4_dgesv_rbt(
        magma_tally4_bool_const(*ref), *n, *nrhs,
        A, *lda,
        B, *ldb,
        info );
}

#define magma_tally4f_dgesvd FORTRAN_NAME( magma_tally4f_dgesvd, MAGMA_tally4F_DGESVD )
void magma_tally4f_dgesvd(
    const char* jobu, const char* jobvt, magma_tally4_int_t *m, magma_tally4_int_t *n,
    double *A, magma_tally4_int_t *lda,
    double *s,
    double *U, magma_tally4_int_t *ldu,
    double *VT, magma_tally4_int_t *ldvt,
    double *work, magma_tally4_int_t *lwork,
    magma_tally4_int_t *info )
{
    magma_tally4_dgesvd(
        magma_tally4_vec_const(*jobu), magma_tally4_vec_const(*jobvt), *m, *n,
        A, *lda,
        s,
        U, *ldu,
        VT, *ldvt,
        work, *lwork,
        info );
}

#define magma_tally4f_dgetf2_nopiv FORTRAN_NAME( magma_tally4f_dgetf2_nopiv, MAGMA_tally4F_DGETF2_NOPIV )
void magma_tally4f_dgetf2_nopiv(
    magma_tally4_int_t *m, magma_tally4_int_t *n,
    double *A, magma_tally4_int_t *lda,
    magma_tally4_int_t *info )
{
    magma_tally4_dgetf2_nopiv(
        *m, *n,
        A, *lda,
        info );
}

#define magma_tally4f_dgetrf FORTRAN_NAME( magma_tally4f_dgetrf, MAGMA_tally4F_DGETRF )
void magma_tally4f_dgetrf(
    magma_tally4_int_t *m, magma_tally4_int_t *n,
    double *A, magma_tally4_int_t *lda,
    magma_tally4_int_t *ipiv,
    magma_tally4_int_t *info )
{
    magma_tally4_dgetrf(
        *m, *n,
        A, *lda,
        ipiv,
        info );
}

#define magma_tally4f_dgetrf_nopiv FORTRAN_NAME( magma_tally4f_dgetrf_nopiv, MAGMA_tally4F_DGETRF_NOPIV )
void magma_tally4f_dgetrf_nopiv(
    magma_tally4_int_t *m, magma_tally4_int_t *n,
    double *A, magma_tally4_int_t *lda,
    magma_tally4_int_t *info )
{
    magma_tally4_dgetrf_nopiv(
        *m, *n,
        A, *lda,
        info );
}

#define magma_tally4f_dgetrf_piv FORTRAN_NAME( magma_tally4f_dgetrf_piv, MAGMA_tally4F_DGETRF_PIV )
void magma_tally4f_dgetrf_piv(
    magma_tally4_int_t *m, magma_tally4_int_t *n, magma_tally4_int_t *NB,
    double *A, magma_tally4_int_t *lda,
    magma_tally4_int_t *ipiv,
    magma_tally4_int_t *info )
{
    magma_tally4_dgetrf_piv(
        *m, *n, *NB,
        A, *lda,
        ipiv,
        info );
}

#define magma_tally4f_dsyevd FORTRAN_NAME( magma_tally4f_dsyevd, MAGMA_tally4F_DSYEVD )
void magma_tally4f_dsyevd(
    const char* jobz, const char* uplo, magma_tally4_int_t *n,
    double *A, magma_tally4_int_t *lda,
    double *w,
    double *work, magma_tally4_int_t *lwork,
    magma_tally4_int_t *iwork, magma_tally4_int_t *liwork,
    magma_tally4_int_t *info )
{
    magma_tally4_dsyevd(
        magma_tally4_vec_const(*jobz), magma_tally4_uplo_const(*uplo), *n,
        A, *lda,
        w,
        work, *lwork,
        iwork, *liwork,
        info );
}

#define magma_tally4f_dsyevdx FORTRAN_NAME( magma_tally4f_dsyevdx, MAGMA_tally4F_DSYEVDX )
void magma_tally4f_dsyevdx(
    const char* jobz, const char* range, const char* uplo, magma_tally4_int_t *n,
    double *A, magma_tally4_int_t *lda, double *vl, double *vu, magma_tally4_int_t *il, magma_tally4_int_t *iu,
    magma_tally4_int_t *m,
    double *w,
    double *work, magma_tally4_int_t *lwork,
    magma_tally4_int_t *iwork, magma_tally4_int_t *liwork,
    magma_tally4_int_t *info )
{
    magma_tally4_dsyevdx(
        magma_tally4_vec_const(*jobz), magma_tally4_range_const(*range), magma_tally4_uplo_const(*uplo), *n,
        A, *lda, *vl, *vu, *il, *iu,
        m,
        w,
        work, *lwork,
        iwork, *liwork,
        info );
}

#define magma_tally4f_dsyevdx_2stage FORTRAN_NAME( magma_tally4f_dsyevdx_2stage, MAGMA_tally4F_DSYEVDX_2STAGE )
void magma_tally4f_dsyevdx_2stage(
    const char* jobz, const char* range, const char* uplo, magma_tally4_int_t *n,
    double *A, magma_tally4_int_t *lda, double *vl, double *vu, magma_tally4_int_t *il, magma_tally4_int_t *iu,
    magma_tally4_int_t *m,
    double *w,
    double *work, magma_tally4_int_t *lwork,
    magma_tally4_int_t *iwork, magma_tally4_int_t *liwork,
    magma_tally4_int_t *info )
{
    magma_tally4_dsyevdx_2stage(
        magma_tally4_vec_const(*jobz), magma_tally4_range_const(*range), magma_tally4_uplo_const(*uplo), *n,
        A, *lda, *vl, *vu, *il, *iu,
        m,
        w,
        work, *lwork,
        iwork, *liwork,
        info );
}

#define magma_tally4f_dsygst FORTRAN_NAME( magma_tally4f_dsygst, MAGMA_tally4F_DSYGST )
void magma_tally4f_dsygst(
    magma_tally4_int_t *itype, const char* uplo, magma_tally4_int_t *n,
    double *A, magma_tally4_int_t *lda,
    double *B, magma_tally4_int_t *ldb,
    magma_tally4_int_t *info )
{
    magma_tally4_dsygst(
        *itype, magma_tally4_uplo_const(*uplo), *n,
        A, *lda,
        B, *ldb,
        info );
}

#define magma_tally4f_dsygvd FORTRAN_NAME( magma_tally4f_dsygvd, MAGMA_tally4F_DSYGVD )
void magma_tally4f_dsygvd(
    magma_tally4_int_t *itype, const char* jobz, const char* uplo, magma_tally4_int_t *n,
    double *A, magma_tally4_int_t *lda,
    double *B, magma_tally4_int_t *ldb,
    double *w,
    double *work, magma_tally4_int_t *lwork,
    magma_tally4_int_t *iwork, magma_tally4_int_t *liwork,
    magma_tally4_int_t *info )
{
    magma_tally4_dsygvd(
        *itype, magma_tally4_vec_const(*jobz), magma_tally4_uplo_const(*uplo), *n,
        A, *lda,
        B, *ldb,
        w,
        work, *lwork,
        iwork, *liwork,
        info );
}

#define magma_tally4f_dsygvdx FORTRAN_NAME( magma_tally4f_dsygvdx, MAGMA_tally4F_DSYGVDX )
void magma_tally4f_dsygvdx(
    magma_tally4_int_t *itype, const char* jobz, const char* range, const char* uplo, magma_tally4_int_t *n,
    double *A, magma_tally4_int_t *lda,
    double *B, magma_tally4_int_t *ldb, double *vl, double *vu, magma_tally4_int_t *il, magma_tally4_int_t *iu,
    magma_tally4_int_t *m,
    double *w,
    double *work, magma_tally4_int_t *lwork,
    magma_tally4_int_t *iwork, magma_tally4_int_t *liwork,
    magma_tally4_int_t *info )
{
    magma_tally4_dsygvdx(
        *itype, magma_tally4_vec_const(*jobz), magma_tally4_range_const(*range), magma_tally4_uplo_const(*uplo), *n,
        A, *lda,
        B, *ldb, *vl, *vu, *il, *iu,
        m,
        w,
        work, *lwork,
        iwork, *liwork,
        info );
}

#define magma_tally4f_dsygvdx_2stage FORTRAN_NAME( magma_tally4f_dsygvdx_2stage, MAGMA_tally4F_DSYGVDX_2STAGE )
void magma_tally4f_dsygvdx_2stage(
    magma_tally4_int_t *itype, const char* jobz, const char* range, const char* uplo, magma_tally4_int_t *n,
    double *A, magma_tally4_int_t *lda,
    double *B, magma_tally4_int_t *ldb, double *vl, double *vu, magma_tally4_int_t *il, magma_tally4_int_t *iu,
    magma_tally4_int_t *m,
    double *w,
    double *work, magma_tally4_int_t *lwork,
    magma_tally4_int_t *iwork, magma_tally4_int_t *liwork,
    magma_tally4_int_t *info )
{
    magma_tally4_dsygvdx_2stage(
        *itype, magma_tally4_vec_const(*jobz), magma_tally4_range_const(*range), magma_tally4_uplo_const(*uplo), *n,
        A, *lda,
        B, *ldb, *vl, *vu, *il, *iu,
        m,
        w,
        work, *lwork,
        iwork, *liwork,
        info );
}

#define magma_tally4f_dsysv FORTRAN_NAME( magma_tally4f_dsysv, MAGMA_tally4F_DSYSV )
void magma_tally4f_dsysv(
    const char* uplo, magma_tally4_int_t *n, magma_tally4_int_t *nrhs,
    double *A, magma_tally4_int_t *lda,
    magma_tally4_int_t *ipiv,
    double *B, magma_tally4_int_t *ldb,
    magma_tally4_int_t *info )
{
    magma_tally4_dsysv(
        magma_tally4_uplo_const(*uplo), *n, *nrhs,
        A, *lda,
        ipiv,
        B, *ldb,
        info );
}

#define magma_tally4f_dsytrd FORTRAN_NAME( magma_tally4f_dsytrd, MAGMA_tally4F_DSYTRD )
void magma_tally4f_dsytrd(
    const char* uplo, magma_tally4_int_t *n,
    double *A, magma_tally4_int_t *lda,
    double *d,
    double *e,
    double *tau,
    double *work, magma_tally4_int_t *lwork,
    magma_tally4_int_t *info )
{
    magma_tally4_dsytrd(
        magma_tally4_uplo_const(*uplo), *n,
        A, *lda,
        d,
        e,
        tau,
        work, *lwork,
        info );
}

#define magma_tally4f_dsytrf FORTRAN_NAME( magma_tally4f_dsytrf, MAGMA_tally4F_DSYTRF )
void magma_tally4f_dsytrf(
    const char* uplo, magma_tally4_int_t *n,
    double *A, magma_tally4_int_t *lda,
    magma_tally4_int_t *ipiv,
    magma_tally4_int_t *info )
{
    magma_tally4_dsytrf(
        magma_tally4_uplo_const(*uplo), *n,
        A, *lda,
        ipiv,
        info );
}

#define magma_tally4f_dsytrf_nopiv FORTRAN_NAME( magma_tally4f_dsytrf_nopiv, MAGMA_tally4F_DSYTRF_NOPIV )
void magma_tally4f_dsytrf_nopiv(
    const char* uplo, magma_tally4_int_t *n,
    double *a, magma_tally4_int_t *lda,
    magma_tally4_int_t *info )
{
    magma_tally4_dsytrf_nopiv(
        magma_tally4_uplo_const(*uplo), *n,
        a, *lda,
        info );
}

#define magma_tally4f_dsytrd_sb2st FORTRAN_NAME( magma_tally4f_dsytrd_sb2st, MAGMA_tally4F_DSYTRD_SB2ST )
void magma_tally4f_dsytrd_sb2st(
    const char* uplo, magma_tally4_int_t *n, magma_tally4_int_t *nb, magma_tally4_int_t *Vblksiz,
    double *A, magma_tally4_int_t *lda,
    double *d,
    double *e,
    double *V, magma_tally4_int_t *ldv,
    double *TAU, magma_tally4_int_t *compT,
    double *T, magma_tally4_int_t *ldt )
{
    magma_tally4_dsytrd_sb2st(
        magma_tally4_uplo_const(*uplo), *n, *nb, *Vblksiz,
        A, *lda,
        d,
        e,
        V, *ldv,
        TAU, *compT,
        T, *ldt );
}

#define magma_tally4f_dsytrd_sy2sb FORTRAN_NAME( magma_tally4f_dsytrd_sy2sb, MAGMA_tally4F_DSYTRD_SY2SB )
void magma_tally4f_dsytrd_sy2sb(
    const char* uplo, magma_tally4_int_t *n, magma_tally4_int_t *nb,
    double *A, magma_tally4_int_t *lda,
    double *tau,
    double *work, magma_tally4_int_t *lwork,
    devptr_t *dT,
    magma_tally4_int_t *info )
{
    magma_tally4_dsytrd_sy2sb(
        magma_tally4_uplo_const(*uplo), *n, *nb,
        A, *lda,
        tau,
        work, *lwork,
        magma_tally4_ddevptr(dT),
        info );
}

#define magma_tally4f_dlaln2 FORTRAN_NAME( magma_tally4f_dlaln2, MAGMA_tally4F_DLALN2 )
void magma_tally4f_dlaln2(
    magma_tally4_int_t *trans, magma_tally4_int_t *na, magma_tally4_int_t *nw, double *smin, double *ca,
    const double *A, magma_tally4_int_t *lda, double *d1, double *d2,
    const double *B, magma_tally4_int_t *ldb, double *wr, double *wi,
    double *X, magma_tally4_int_t *ldx,
    double *scale,
    double *xnorm,
    magma_tally4_int_t *info )
{
    magma_tally4_dlaln2(
        *trans, *na, *nw, *smin, *ca,
        A, *lda, *d1, *d2,
        B, *ldb, *wr, *wi,
        X, *ldx,
        scale,
        xnorm,
        info );
}

#define magma_tally4f_dlaqtrsd FORTRAN_NAME( magma_tally4f_dlaqtrsd, MAGMA_tally4F_DLAQTRSD )
void magma_tally4f_dlaqtrsd(
    const char* trans, magma_tally4_int_t *n,
    const double *T, magma_tally4_int_t *ldt,
    double *x, magma_tally4_int_t *ldx,
    const double *cnorm,
    magma_tally4_int_t *info )
{
    magma_tally4_dlaqtrsd(
        magma_tally4_trans_const(*trans), *n,
        T, *ldt,
        x, *ldx,
        cnorm,
        info );
}

#define magma_tally4f_dlauum FORTRAN_NAME( magma_tally4f_dlauum, MAGMA_tally4F_DLAUUM )
void magma_tally4f_dlauum(
    const char* uplo, magma_tally4_int_t *n,
    double *A, magma_tally4_int_t *lda,
    magma_tally4_int_t *info )
{
    magma_tally4_dlauum(
        magma_tally4_uplo_const(*uplo), *n,
        A, *lda,
        info );
}

#define magma_tally4f_dposv FORTRAN_NAME( magma_tally4f_dposv, MAGMA_tally4F_DPOSV )
void magma_tally4f_dposv(
    const char* uplo, magma_tally4_int_t *n, magma_tally4_int_t *nrhs,
    double *A, magma_tally4_int_t *lda,
    double *B, magma_tally4_int_t *ldb,
    magma_tally4_int_t *info )
{
    magma_tally4_dposv(
        magma_tally4_uplo_const(*uplo), *n, *nrhs,
        A, *lda,
        B, *ldb,
        info );
}

#define magma_tally4f_dpotrf FORTRAN_NAME( magma_tally4f_dpotrf, MAGMA_tally4F_DPOTRF )
void magma_tally4f_dpotrf(
    const char* uplo, magma_tally4_int_t *n,
    double *A, magma_tally4_int_t *lda,
    magma_tally4_int_t *info )
{
    magma_tally4_dpotrf(
        magma_tally4_uplo_const(*uplo), *n,
        A, *lda,
        info );
}

#define magma_tally4f_dpotri FORTRAN_NAME( magma_tally4f_dpotri, MAGMA_tally4F_DPOTRI )
void magma_tally4f_dpotri(
    const char* uplo, magma_tally4_int_t *n,
    double *A, magma_tally4_int_t *lda,
    magma_tally4_int_t *info )
{
    magma_tally4_dpotri(
        magma_tally4_uplo_const(*uplo), *n,
        A, *lda,
        info );
}

#define magma_tally4f_dstedx FORTRAN_NAME( magma_tally4f_dstedx, MAGMA_tally4F_DSTEDX )
void magma_tally4f_dstedx(
    const char* range, magma_tally4_int_t *n, double *vl, double *vu, magma_tally4_int_t *il, magma_tally4_int_t *iu,
    double *d,
    double *e,
    double *Z, magma_tally4_int_t *ldz,
    double *rwork, magma_tally4_int_t *lrwork,
    magma_tally4_int_t *iwork, magma_tally4_int_t *liwork,
    devptr_t *dwork,
    magma_tally4_int_t *info )
{
    magma_tally4_dstedx(
        magma_tally4_range_const(*range), *n, *vl, *vu, *il, *iu,
        d,
        e,
        Z, *ldz,
        rwork, *lrwork,
        iwork, *liwork,
        magma_tally4_ddevptr(dwork),
        info );
}

#define magma_tally4f_dtrevc3 FORTRAN_NAME( magma_tally4f_dtrevc3, MAGMA_tally4F_DTREVC3 )
void magma_tally4f_dtrevc3(
    const char* side, const char* howmany,
    magma_tally4_int_t *select, magma_tally4_int_t *n,
    double *T, magma_tally4_int_t *ldt,
    double *VL, magma_tally4_int_t *ldvl,
    double *VR, magma_tally4_int_t *ldvr, magma_tally4_int_t *mm,
    magma_tally4_int_t *mout,
    double *work, magma_tally4_int_t *lwork,
    magma_tally4_int_t *info )
{
    magma_tally4_dtrevc3(
        magma_tally4_side_const(*side), magma_tally4_vec_const(*howmany),
        select, *n,
        T, *ldt,
        VL, *ldvl,
        VR, *ldvr, *mm,
        mout,
        work, *lwork,
        info );
}

#define magma_tally4f_dtrevc3_mt FORTRAN_NAME( magma_tally4f_dtrevc3_mt, MAGMA_tally4F_DTREVC3_MT )
void magma_tally4f_dtrevc3_mt(
    const char* side, const char* howmany,
    magma_tally4_int_t *select, magma_tally4_int_t *n,
    double *T, magma_tally4_int_t *ldt,
    double *VL, magma_tally4_int_t *ldvl,
    double *VR, magma_tally4_int_t *ldvr, magma_tally4_int_t *mm,
    magma_tally4_int_t *mout,
    double *work, magma_tally4_int_t *lwork,
    magma_tally4_int_t *info )
{
    magma_tally4_dtrevc3_mt(
        magma_tally4_side_const(*side), magma_tally4_vec_const(*howmany),
        select, *n,
        T, *ldt,
        VL, *ldvl,
        VR, *ldvr, *mm,
        mout,
        work, *lwork,
        info );
}

#define magma_tally4f_dtrtri FORTRAN_NAME( magma_tally4f_dtrtri, MAGMA_tally4F_DTRTRI )
void magma_tally4f_dtrtri(
    const char* uplo, const char* diag, magma_tally4_int_t *n,
    double *A, magma_tally4_int_t *lda,
    magma_tally4_int_t *info )
{
    magma_tally4_dtrtri(
        magma_tally4_uplo_const(*uplo), magma_tally4_diag_const(*diag), *n,
        A, *lda,
        info );
}

#define magma_tally4f_dorghr FORTRAN_NAME( magma_tally4f_dorghr, MAGMA_tally4F_DORGHR )
void magma_tally4f_dorghr(
    magma_tally4_int_t *n, magma_tally4_int_t *ilo, magma_tally4_int_t *ihi,
    double *A, magma_tally4_int_t *lda,
    double *tau,
    devptr_t *dT, magma_tally4_int_t *nb,
    magma_tally4_int_t *info )
{
    magma_tally4_dorghr(
        *n, *ilo, *ihi,
        A, *lda,
        tau,
        magma_tally4_ddevptr(dT), *nb,
        info );
}

#define magma_tally4f_dorgqr FORTRAN_NAME( magma_tally4f_dorgqr, MAGMA_tally4F_DORGQR )
void magma_tally4f_dorgqr(
    magma_tally4_int_t *m, magma_tally4_int_t *n, magma_tally4_int_t *k,
    double *A, magma_tally4_int_t *lda,
    double *tau,
    devptr_t *dT, magma_tally4_int_t *nb,
    magma_tally4_int_t *info )
{
    magma_tally4_dorgqr(
        *m, *n, *k,
        A, *lda,
        tau,
        magma_tally4_ddevptr(dT), *nb,
        info );
}

#define magma_tally4f_dorgqr2 FORTRAN_NAME( magma_tally4f_dorgqr2, MAGMA_tally4F_DORGQR2 )
void magma_tally4f_dorgqr2(
    magma_tally4_int_t *m, magma_tally4_int_t *n, magma_tally4_int_t *k,
    double *A, magma_tally4_int_t *lda,
    double *tau,
    magma_tally4_int_t *info )
{
    magma_tally4_dorgqr2(
        *m, *n, *k,
        A, *lda,
        tau,
        info );
}

#define magma_tally4f_dormbr FORTRAN_NAME( magma_tally4f_dormbr, MAGMA_tally4F_DORMBR )
void magma_tally4f_dormbr(
    const char* vect, const char* side, const char* trans, magma_tally4_int_t *m, magma_tally4_int_t *n, magma_tally4_int_t *k,
    double *A, magma_tally4_int_t *lda,
    double *tau,
    double *C, magma_tally4_int_t *ldc,
    double *work, magma_tally4_int_t *lwork,
    magma_tally4_int_t *info )
{
    magma_tally4_dormbr(
        magma_tally4_vect_const(*vect), magma_tally4_side_const(*side), magma_tally4_trans_const(*trans), *m, *n, *k,
        A, *lda,
        tau,
        C, *ldc,
        work, *lwork,
        info );
}

#define magma_tally4f_dormlq FORTRAN_NAME( magma_tally4f_dormlq, MAGMA_tally4F_DORMLQ )
void magma_tally4f_dormlq(
    const char* side, const char* trans, magma_tally4_int_t *m, magma_tally4_int_t *n, magma_tally4_int_t *k,
    double *A, magma_tally4_int_t *lda,
    double *tau,
    double *C, magma_tally4_int_t *ldc,
    double *work, magma_tally4_int_t *lwork,
    magma_tally4_int_t *info )
{
    magma_tally4_dormlq(
        magma_tally4_side_const(*side), magma_tally4_trans_const(*trans), *m, *n, *k,
        A, *lda,
        tau,
        C, *ldc,
        work, *lwork,
        info );
}

#define magma_tally4f_dormql FORTRAN_NAME( magma_tally4f_dormql, MAGMA_tally4F_DORMQL )
void magma_tally4f_dormql(
    const char* side, const char* trans, magma_tally4_int_t *m, magma_tally4_int_t *n, magma_tally4_int_t *k,
    double *A, magma_tally4_int_t *lda,
    double *tau,
    double *C, magma_tally4_int_t *ldc,
    double *work, magma_tally4_int_t *lwork,
    magma_tally4_int_t *info )
{
    magma_tally4_dormql(
        magma_tally4_side_const(*side), magma_tally4_trans_const(*trans), *m, *n, *k,
        A, *lda,
        tau,
        C, *ldc,
        work, *lwork,
        info );
}

#define magma_tally4f_dormqr FORTRAN_NAME( magma_tally4f_dormqr, MAGMA_tally4F_DORMQR )
void magma_tally4f_dormqr(
    const char* side, const char* trans, magma_tally4_int_t *m, magma_tally4_int_t *n, magma_tally4_int_t *k,
    double *A, magma_tally4_int_t *lda,
    double *tau,
    double *C, magma_tally4_int_t *ldc,
    double *work, magma_tally4_int_t *lwork,
    magma_tally4_int_t *info )
{
    magma_tally4_dormqr(
        magma_tally4_side_const(*side), magma_tally4_trans_const(*trans), *m, *n, *k,
        A, *lda,
        tau,
        C, *ldc,
        work, *lwork,
        info );
}

#define magma_tally4f_dormtr FORTRAN_NAME( magma_tally4f_dormtr, MAGMA_tally4F_DORMTR )
void magma_tally4f_dormtr(
    const char* side, const char* uplo, const char* trans, magma_tally4_int_t *m, magma_tally4_int_t *n,
    double *A, magma_tally4_int_t *lda,
    double *tau,
    double *C, magma_tally4_int_t *ldc,
    double *work, magma_tally4_int_t *lwork,
    magma_tally4_int_t *info )
{
    magma_tally4_dormtr(
        magma_tally4_side_const(*side), magma_tally4_uplo_const(*uplo), magma_tally4_trans_const(*trans), *m, *n,
        A, *lda,
        tau,
        C, *ldc,
        work, *lwork,
        info );
}

#define magma_tally4f_dgeev_m FORTRAN_NAME( magma_tally4f_dgeev_m, MAGMA_tally4F_DGEEV_M )
void magma_tally4f_dgeev_m(
    const char* jobvl, const char* jobvr, magma_tally4_int_t *n,
    double *A, magma_tally4_int_t *lda,
    double *wr,
    double *wi,
    double *VL, magma_tally4_int_t *ldvl,
    double *VR, magma_tally4_int_t *ldvr,
    double *work, magma_tally4_int_t *lwork,
    magma_tally4_int_t *info )
{
    magma_tally4_dgeev_m(
        magma_tally4_vec_const(*jobvl), magma_tally4_vec_const(*jobvr), *n,
        A, *lda,
        wr,
        wi,
        VL, *ldvl,
        VR, *ldvr,
        work, *lwork,
        info );
}

#define magma_tally4f_dgehrd_m FORTRAN_NAME( magma_tally4f_dgehrd_m, MAGMA_tally4F_DGEHRD_M )
void magma_tally4f_dgehrd_m(
    magma_tally4_int_t *n, magma_tally4_int_t *ilo, magma_tally4_int_t *ihi,
    double *A, magma_tally4_int_t *lda,
    double *tau,
    double *work, magma_tally4_int_t *lwork,
    double *T,
    magma_tally4_int_t *info )
{
    magma_tally4_dgehrd_m(
        *n, *ilo, *ihi,
        A, *lda,
        tau,
        work, *lwork,
        T,
        info );
}

#define magma_tally4f_dgetrf_m FORTRAN_NAME( magma_tally4f_dgetrf_m, MAGMA_tally4F_DGETRF_M )
void magma_tally4f_dgetrf_m(
    magma_tally4_int_t *ngpu, magma_tally4_int_t *m, magma_tally4_int_t *n,
    double *A, magma_tally4_int_t *lda,
    magma_tally4_int_t *ipiv,
    magma_tally4_int_t *info )
{
    magma_tally4_dgetrf_m(
        *ngpu, *m, *n,
        A, *lda,
        ipiv,
        info );
}

#define magma_tally4f_dsyevd_m FORTRAN_NAME( magma_tally4f_dsyevd_m, MAGMA_tally4F_DSYEVD_M )
void magma_tally4f_dsyevd_m(
    magma_tally4_int_t *ngpu, const char* jobz, const char* uplo, magma_tally4_int_t *n,
    double *A, magma_tally4_int_t *lda,
    double *w,
    double *work, magma_tally4_int_t *lwork,
    magma_tally4_int_t *iwork, magma_tally4_int_t *liwork,
    magma_tally4_int_t *info )
{
    magma_tally4_dsyevd_m(
        *ngpu, magma_tally4_vec_const(*jobz), magma_tally4_uplo_const(*uplo), *n,
        A, *lda,
        w,
        work, *lwork,
        iwork, *liwork,
        info );
}

#define magma_tally4f_dsyevdx_2stage_m FORTRAN_NAME( magma_tally4f_dsyevdx_2stage_m, MAGMA_tally4F_DSYEVDX_2STAGE_M )
void magma_tally4f_dsyevdx_2stage_m(
    magma_tally4_int_t *ngpu, const char* jobz, const char* range, const char* uplo, magma_tally4_int_t *n,
    double *A, magma_tally4_int_t *lda, double *vl, double *vu, magma_tally4_int_t *il, magma_tally4_int_t *iu,
    magma_tally4_int_t *m,
    double *w,
    double *work, magma_tally4_int_t *lwork,
    magma_tally4_int_t *iwork, magma_tally4_int_t *liwork,
    magma_tally4_int_t *info )
{
    magma_tally4_dsyevdx_2stage_m(
        *ngpu, magma_tally4_vec_const(*jobz), magma_tally4_range_const(*range), magma_tally4_uplo_const(*uplo), *n,
        A, *lda, *vl, *vu, *il, *iu,
        m,
        w,
        work, *lwork,
        iwork, *liwork,
        info );
}

#define magma_tally4f_dsyevdx_m FORTRAN_NAME( magma_tally4f_dsyevdx_m, MAGMA_tally4F_DSYEVDX_M )
void magma_tally4f_dsyevdx_m(
    magma_tally4_int_t *ngpu, const char* jobz, const char* range, const char* uplo, magma_tally4_int_t *n,
    double *A, magma_tally4_int_t *lda, double *vl, double *vu, magma_tally4_int_t *il, magma_tally4_int_t *iu,
    magma_tally4_int_t *m,
    double *w,
    double *work, magma_tally4_int_t *lwork,
    magma_tally4_int_t *iwork, magma_tally4_int_t *liwork,
    magma_tally4_int_t *info )
{
    magma_tally4_dsyevdx_m(
        *ngpu, magma_tally4_vec_const(*jobz), magma_tally4_range_const(*range), magma_tally4_uplo_const(*uplo), *n,
        A, *lda, *vl, *vu, *il, *iu,
        m,
        w,
        work, *lwork,
        iwork, *liwork,
        info );
}

#define magma_tally4f_dsygst_m FORTRAN_NAME( magma_tally4f_dsygst_m, MAGMA_tally4F_DSYGST_M )
void magma_tally4f_dsygst_m(
    magma_tally4_int_t *ngpu, magma_tally4_int_t *itype, const char* uplo, magma_tally4_int_t *n,
    double *A, magma_tally4_int_t *lda,
    double *B, magma_tally4_int_t *ldb,
    magma_tally4_int_t *info )
{
    magma_tally4_dsygst_m(
        *ngpu, *itype, magma_tally4_uplo_const(*uplo), *n,
        A, *lda,
        B, *ldb,
        info );
}

#define magma_tally4f_dsygvd_m FORTRAN_NAME( magma_tally4f_dsygvd_m, MAGMA_tally4F_DSYGVD_M )
void magma_tally4f_dsygvd_m(
    magma_tally4_int_t *ngpu, magma_tally4_int_t *itype, const char* jobz, const char* uplo, magma_tally4_int_t *n,
    double *A, magma_tally4_int_t *lda,
    double *B, magma_tally4_int_t *ldb,
    double *w,
    double *work, magma_tally4_int_t *lwork,
    magma_tally4_int_t *iwork, magma_tally4_int_t *liwork,
    magma_tally4_int_t *info )
{
    magma_tally4_dsygvd_m(
        *ngpu, *itype, magma_tally4_vec_const(*jobz), magma_tally4_uplo_const(*uplo), *n,
        A, *lda,
        B, *ldb,
        w,
        work, *lwork,
        iwork, *liwork,
        info );
}

#define magma_tally4f_dsygvdx_2stage_m FORTRAN_NAME( magma_tally4f_dsygvdx_2stage_m, MAGMA_tally4F_DSYGVDX_2STAGE_M )
void magma_tally4f_dsygvdx_2stage_m(
    magma_tally4_int_t *ngpu, magma_tally4_int_t *itype, const char* jobz, const char* range, const char* uplo, magma_tally4_int_t *n,
    double *A, magma_tally4_int_t *lda,
    double *B, magma_tally4_int_t *ldb, double *vl, double *vu, magma_tally4_int_t *il, magma_tally4_int_t *iu,
    magma_tally4_int_t *m,
    double *w,
    double *work, magma_tally4_int_t *lwork,
    magma_tally4_int_t *iwork, magma_tally4_int_t *liwork,
    magma_tally4_int_t *info )
{
    magma_tally4_dsygvdx_2stage_m(
        *ngpu, *itype, magma_tally4_vec_const(*jobz), magma_tally4_range_const(*range), magma_tally4_uplo_const(*uplo), *n,
        A, *lda,
        B, *ldb, *vl, *vu, *il, *iu,
        m,
        w,
        work, *lwork,
        iwork, *liwork,
        info );
}

#define magma_tally4f_dsygvdx_m FORTRAN_NAME( magma_tally4f_dsygvdx_m, MAGMA_tally4F_DSYGVDX_M )
void magma_tally4f_dsygvdx_m(
    magma_tally4_int_t *ngpu, magma_tally4_int_t *itype, const char* jobz, const char* range, const char* uplo, magma_tally4_int_t *n,
    double *A, magma_tally4_int_t *lda,
    double *B, magma_tally4_int_t *ldb, double *vl, double *vu, magma_tally4_int_t *il, magma_tally4_int_t *iu,
    magma_tally4_int_t *m,
    double *w,
    double *work, magma_tally4_int_t *lwork,
    magma_tally4_int_t *iwork, magma_tally4_int_t *liwork,
    magma_tally4_int_t *info )
{
    magma_tally4_dsygvdx_m(
        *ngpu, *itype, magma_tally4_vec_const(*jobz), magma_tally4_range_const(*range), magma_tally4_uplo_const(*uplo), *n,
        A, *lda,
        B, *ldb, *vl, *vu, *il, *iu,
        m,
        w,
        work, *lwork,
        iwork, *liwork,
        info );
}

#define magma_tally4f_dpotrf_m FORTRAN_NAME( magma_tally4f_dpotrf_m, MAGMA_tally4F_DPOTRF_M )
void magma_tally4f_dpotrf_m(
    magma_tally4_int_t *ngpu, const char* uplo, magma_tally4_int_t *n,
    double *A, magma_tally4_int_t *lda,
    magma_tally4_int_t *info )
{
    magma_tally4_dpotrf_m(
        *ngpu, magma_tally4_uplo_const(*uplo), *n,
        A, *lda,
        info );
}

#define magma_tally4f_dstedx_m FORTRAN_NAME( magma_tally4f_dstedx_m, MAGMA_tally4F_DSTEDX_M )
void magma_tally4f_dstedx_m(
    magma_tally4_int_t *ngpu, const char* range, magma_tally4_int_t *n, double *vl, double *vu, magma_tally4_int_t *il, magma_tally4_int_t *iu,
    double *d,
    double *e,
    double *Z, magma_tally4_int_t *ldz,
    double *rwork, magma_tally4_int_t *lrwork,
    magma_tally4_int_t *iwork, magma_tally4_int_t *liwork,
    magma_tally4_int_t *info )
{
    magma_tally4_dstedx_m(
        *ngpu, magma_tally4_range_const(*range), *n, *vl, *vu, *il, *iu,
        d,
        e,
        Z, *ldz,
        rwork, *lrwork,
        iwork, *liwork,
        info );
}

#define magma_tally4f_dtrsm_m FORTRAN_NAME( magma_tally4f_dtrsm_m, MAGMA_tally4F_DTRSM_M )
void magma_tally4f_dtrsm_m(
    magma_tally4_int_t *ngpu, const char* side, const char* uplo, const char* transa, const char* diag, magma_tally4_int_t *m, magma_tally4_int_t *n, double *alpha,
    double *A, magma_tally4_int_t *lda,
    double *B, magma_tally4_int_t *ldb )
{
    magma_tally4_dtrsm_m(
        *ngpu, magma_tally4_side_const(*side), magma_tally4_uplo_const(*uplo), magma_tally4_trans_const(*transa), magma_tally4_diag_const(*diag), *m, *n, *alpha,
        A, *lda,
        B, *ldb );
}

#define magma_tally4f_dorghr_m FORTRAN_NAME( magma_tally4f_dorghr_m, MAGMA_tally4F_DORGHR_M )
void magma_tally4f_dorghr_m(
    magma_tally4_int_t *n, magma_tally4_int_t *ilo, magma_tally4_int_t *ihi,
    double *A, magma_tally4_int_t *lda,
    double *tau,
    double *T, magma_tally4_int_t *nb,
    magma_tally4_int_t *info )
{
    magma_tally4_dorghr_m(
        *n, *ilo, *ihi,
        A, *lda,
        tau,
        T, *nb,
        info );
}

#define magma_tally4f_dorgqr_m FORTRAN_NAME( magma_tally4f_dorgqr_m, MAGMA_tally4F_DORGQR_M )
void magma_tally4f_dorgqr_m(
    magma_tally4_int_t *m, magma_tally4_int_t *n, magma_tally4_int_t *k,
    double *A, magma_tally4_int_t *lda,
    double *tau,
    double *T, magma_tally4_int_t *nb,
    magma_tally4_int_t *info )
{
    magma_tally4_dorgqr_m(
        *m, *n, *k,
        A, *lda,
        tau,
        T, *nb,
        info );
}

#define magma_tally4f_dormqr_m FORTRAN_NAME( magma_tally4f_dormqr_m, MAGMA_tally4F_DORMQR_M )
void magma_tally4f_dormqr_m(
    magma_tally4_int_t *ngpu, const char* side, const char* trans, magma_tally4_int_t *m, magma_tally4_int_t *n, magma_tally4_int_t *k,
    double *A, magma_tally4_int_t *lda,
    double *tau,
    double *C, magma_tally4_int_t *ldc,
    double *work, magma_tally4_int_t *lwork,
    magma_tally4_int_t *info )
{
    magma_tally4_dormqr_m(
        *ngpu, magma_tally4_side_const(*side), magma_tally4_trans_const(*trans), *m, *n, *k,
        A, *lda,
        tau,
        C, *ldc,
        work, *lwork,
        info );
}

#define magma_tally4f_dormtr_m FORTRAN_NAME( magma_tally4f_dormtr_m, MAGMA_tally4F_DORMTR_M )
void magma_tally4f_dormtr_m(
    magma_tally4_int_t *ngpu, const char* side, const char* uplo, const char* trans, magma_tally4_int_t *m, magma_tally4_int_t *n,
    double *A, magma_tally4_int_t *lda,
    double *tau,
    double *C, magma_tally4_int_t *ldc,
    double *work, magma_tally4_int_t *lwork,
    magma_tally4_int_t *info )
{
    magma_tally4_dormtr_m(
        *ngpu, magma_tally4_side_const(*side), magma_tally4_uplo_const(*uplo), magma_tally4_trans_const(*trans), *m, *n,
        A, *lda,
        tau,
        C, *ldc,
        work, *lwork,
        info );
}

#define magma_tally4f_dgegqr_gpu FORTRAN_NAME( magma_tally4f_dgegqr_gpu, MAGMA_tally4F_DGEGQR_GPU )
void magma_tally4f_dgegqr_gpu(
    magma_tally4_int_t *ikind, magma_tally4_int_t *m, magma_tally4_int_t *n,
    devptr_t *dA, magma_tally4_int_t *ldda,
    devptr_t *dwork,
    double *work,
    magma_tally4_int_t *info )
{
    magma_tally4_dgegqr_gpu(
        *ikind, *m, *n,
        magma_tally4_ddevptr(dA), *ldda,
        magma_tally4_ddevptr(dwork),
        work,
        info );
}

#define magma_tally4f_dgelqf_gpu FORTRAN_NAME( magma_tally4f_dgelqf_gpu, MAGMA_tally4F_DGELQF_GPU )
void magma_tally4f_dgelqf_gpu(
    magma_tally4_int_t *m, magma_tally4_int_t *n,
    devptr_t *dA, magma_tally4_int_t *ldda,
    double *tau,
    double *work, magma_tally4_int_t *lwork,
    magma_tally4_int_t *info )
{
    magma_tally4_dgelqf_gpu(
        *m, *n,
        magma_tally4_ddevptr(dA), *ldda,
        tau,
        work, *lwork,
        info );
}

#define magma_tally4f_dgels_gpu FORTRAN_NAME( magma_tally4f_dgels_gpu, MAGMA_tally4F_DGELS_GPU )
void magma_tally4f_dgels_gpu(
    const char* trans, magma_tally4_int_t *m, magma_tally4_int_t *n, magma_tally4_int_t *nrhs,
    devptr_t *dA, magma_tally4_int_t *ldda,
    devptr_t *dB, magma_tally4_int_t *lddb,
    double *hwork, magma_tally4_int_t *lwork,
    magma_tally4_int_t *info )
{
    magma_tally4_dgels_gpu(
        magma_tally4_trans_const(*trans), *m, *n, *nrhs,
        magma_tally4_ddevptr(dA), *ldda,
        magma_tally4_ddevptr(dB), *lddb,
        hwork, *lwork,
        info );
}

#define magma_tally4f_dgels3_gpu FORTRAN_NAME( magma_tally4f_dgels3_gpu, MAGMA_tally4F_DGELS3_GPU )
void magma_tally4f_dgels3_gpu(
    const char* trans, magma_tally4_int_t *m, magma_tally4_int_t *n, magma_tally4_int_t *nrhs,
    devptr_t *dA, magma_tally4_int_t *ldda,
    devptr_t *dB, magma_tally4_int_t *lddb,
    double *hwork, magma_tally4_int_t *lwork,
    magma_tally4_int_t *info )
{
    magma_tally4_dgels3_gpu(
        magma_tally4_trans_const(*trans), *m, *n, *nrhs,
        magma_tally4_ddevptr(dA), *ldda,
        magma_tally4_ddevptr(dB), *lddb,
        hwork, *lwork,
        info );
}

#define magma_tally4f_dgeqp3_gpu FORTRAN_NAME( magma_tally4f_dgeqp3_gpu, MAGMA_tally4F_DGEQP3_GPU )
void magma_tally4f_dgeqp3_gpu(
    magma_tally4_int_t *m, magma_tally4_int_t *n,
    devptr_t *dA, magma_tally4_int_t *ldda,
    magma_tally4_int_t *jpvt,
    double *tau,
    devptr_t *dwork, magma_tally4_int_t *lwork,
    magma_tally4_int_t *info )
{
    magma_tally4_dgeqp3_gpu(
        *m, *n,
        magma_tally4_ddevptr(dA), *ldda,
        jpvt,
        tau,
        magma_tally4_ddevptr(dwork), *lwork,
        info );
}

#define magma_tally4f_dgeqr2x_gpu FORTRAN_NAME( magma_tally4f_dgeqr2x_gpu, MAGMA_tally4F_DGEQR2X_GPU )
void magma_tally4f_dgeqr2x_gpu(
    magma_tally4_int_t *m, magma_tally4_int_t *n,
    devptr_t *dA, magma_tally4_int_t *ldda,
    devptr_t *dtau,
    devptr_t *dT,
    devptr_t *ddA,
    devptr_t *dwork,
    magma_tally4_int_t *info )
{
    magma_tally4_dgeqr2x_gpu(
        *m, *n,
        magma_tally4_ddevptr(dA), *ldda,
        magma_tally4_ddevptr(dtau),
        magma_tally4_ddevptr(dT),
        magma_tally4_ddevptr(ddA),
        magma_tally4_ddevptr(dwork),
        info );
}

#define magma_tally4f_dgeqr2x2_gpu FORTRAN_NAME( magma_tally4f_dgeqr2x2_gpu, MAGMA_tally4F_DGEQR2X2_GPU )
void magma_tally4f_dgeqr2x2_gpu(
    magma_tally4_int_t *m, magma_tally4_int_t *n,
    devptr_t *dA, magma_tally4_int_t *ldda,
    devptr_t *dtau,
    devptr_t *dT,
    devptr_t *ddA,
    devptr_t *dwork,
    magma_tally4_int_t *info )
{
    magma_tally4_dgeqr2x2_gpu(
        *m, *n,
        magma_tally4_ddevptr(dA), *ldda,
        magma_tally4_ddevptr(dtau),
        magma_tally4_ddevptr(dT),
        magma_tally4_ddevptr(ddA),
        magma_tally4_ddevptr(dwork),
        info );
}

#define magma_tally4f_dgeqr2x3_gpu FORTRAN_NAME( magma_tally4f_dgeqr2x3_gpu, MAGMA_tally4F_DGEQR2X3_GPU )
void magma_tally4f_dgeqr2x3_gpu(
    magma_tally4_int_t *m, magma_tally4_int_t *n,
    devptr_t *dA, magma_tally4_int_t *ldda,
    devptr_t *dtau,
    devptr_t *dT,
    devptr_t *ddA,
    devptr_t *dwork,
    magma_tally4_int_t *info )
{
    magma_tally4_dgeqr2x3_gpu(
        *m, *n,
        magma_tally4_ddevptr(dA), *ldda,
        magma_tally4_ddevptr(dtau),
        magma_tally4_ddevptr(dT),
        magma_tally4_ddevptr(ddA),
        magma_tally4_ddevptr(dwork),
        info );
}

#define magma_tally4f_dgeqr2x4_gpu FORTRAN_NAME( magma_tally4f_dgeqr2x4_gpu, MAGMA_tally4F_DGEQR2X4_GPU )
void magma_tally4f_dgeqr2x4_gpu(
    magma_tally4_int_t *m, magma_tally4_int_t *n,
    devptr_t *dA, magma_tally4_int_t *ldda,
    devptr_t *dtau,
    devptr_t *dT,
    devptr_t *ddA,
    devptr_t *dwork, magma_tally4_queue_t *queue,
    magma_tally4_int_t *info )
{
    magma_tally4_dgeqr2x4_gpu(
        *m, *n,
        magma_tally4_ddevptr(dA), *ldda,
        magma_tally4_ddevptr(dtau),
        magma_tally4_ddevptr(dT),
        magma_tally4_ddevptr(ddA),
        magma_tally4_ddevptr(dwork), *queue,
        info );
}

#define magma_tally4f_dgeqrf_gpu FORTRAN_NAME( magma_tally4f_dgeqrf_gpu, MAGMA_tally4F_DGEQRF_GPU )
void magma_tally4f_dgeqrf_gpu(
    magma_tally4_int_t *m, magma_tally4_int_t *n,
    devptr_t *dA, magma_tally4_int_t *ldda,
    double *tau,
    devptr_t *dT,
    magma_tally4_int_t *info )
{
    magma_tally4_dgeqrf_gpu(
        *m, *n,
        magma_tally4_ddevptr(dA), *ldda,
        tau,
        magma_tally4_ddevptr(dT),
        info );
}

#define magma_tally4f_dgeqrf2_gpu FORTRAN_NAME( magma_tally4f_dgeqrf2_gpu, MAGMA_tally4F_DGEQRF2_GPU )
void magma_tally4f_dgeqrf2_gpu(
    magma_tally4_int_t *m, magma_tally4_int_t *n,
    devptr_t *dA, magma_tally4_int_t *ldda,
    double *tau,
    magma_tally4_int_t *info )
{
    magma_tally4_dgeqrf2_gpu(
        *m, *n,
        magma_tally4_ddevptr(dA), *ldda,
        tau,
        info );
}

#define magma_tally4f_dgeqrf3_gpu FORTRAN_NAME( magma_tally4f_dgeqrf3_gpu, MAGMA_tally4F_DGEQRF3_GPU )
void magma_tally4f_dgeqrf3_gpu(
    magma_tally4_int_t *m, magma_tally4_int_t *n,
    devptr_t *dA, magma_tally4_int_t *ldda,
    double *tau,
    devptr_t *dT,
    magma_tally4_int_t *info )
{
    magma_tally4_dgeqrf3_gpu(
        *m, *n,
        magma_tally4_ddevptr(dA), *ldda,
        tau,
        magma_tally4_ddevptr(dT),
        info );
}

#define magma_tally4f_dgeqrs_gpu FORTRAN_NAME( magma_tally4f_dgeqrs_gpu, MAGMA_tally4F_DGEQRS_GPU )
void magma_tally4f_dgeqrs_gpu(
    magma_tally4_int_t *m, magma_tally4_int_t *n, magma_tally4_int_t *nrhs,
    devptr_t *dA, magma_tally4_int_t *ldda,
    double *tau,
    devptr_t *dT,
    devptr_t *dB, magma_tally4_int_t *lddb,
    double *hwork, magma_tally4_int_t *lwork,
    magma_tally4_int_t *info )
{
    magma_tally4_dgeqrs_gpu(
        *m, *n, *nrhs,
        magma_tally4_ddevptr(dA), *ldda,
        tau,
        magma_tally4_ddevptr(dT),
        magma_tally4_ddevptr(dB), *lddb,
        hwork, *lwork,
        info );
}

#define magma_tally4f_dgeqrs3_gpu FORTRAN_NAME( magma_tally4f_dgeqrs3_gpu, MAGMA_tally4F_DGEQRS3_GPU )
void magma_tally4f_dgeqrs3_gpu(
    magma_tally4_int_t *m, magma_tally4_int_t *n, magma_tally4_int_t *nrhs,
    devptr_t *dA, magma_tally4_int_t *ldda,
    double *tau,
    devptr_t *dT,
    devptr_t *dB, magma_tally4_int_t *lddb,
    double *hwork, magma_tally4_int_t *lwork,
    magma_tally4_int_t *info )
{
    magma_tally4_dgeqrs3_gpu(
        *m, *n, *nrhs,
        magma_tally4_ddevptr(dA), *ldda,
        tau,
        magma_tally4_ddevptr(dT),
        magma_tally4_ddevptr(dB), *lddb,
        hwork, *lwork,
        info );
}

#define magma_tally4f_dgerbt_gpu FORTRAN_NAME( magma_tally4f_dgerbt_gpu, MAGMA_tally4F_DGERBT_GPU )
void magma_tally4f_dgerbt_gpu(
    const char* gen, magma_tally4_int_t *n, magma_tally4_int_t *nrhs,
    devptr_t *dA, magma_tally4_int_t *ldda,
    devptr_t *dB, magma_tally4_int_t *lddb,
    double *U,
    double *V,
    magma_tally4_int_t *info )
{
    magma_tally4_dgerbt_gpu(
        magma_tally4_bool_const(*gen), *n, *nrhs,
        magma_tally4_ddevptr(dA), *ldda,
        magma_tally4_ddevptr(dB), *lddb,
        U,
        V,
        info );
}

#define magma_tally4f_dgessm_gpu FORTRAN_NAME( magma_tally4f_dgessm_gpu, MAGMA_tally4F_DGESSM_GPU )
void magma_tally4f_dgessm_gpu(
    const char* order, magma_tally4_int_t *m, magma_tally4_int_t *n, magma_tally4_int_t *k, magma_tally4_int_t *ib,
    magma_tally4_int_t *ipiv,
    devptr_t *dL1, magma_tally4_int_t *lddl1,
    devptr_t *dL, magma_tally4_int_t *lddl,
    devptr_t *dA, magma_tally4_int_t *ldda,
    magma_tally4_int_t *info )
{
    magma_tally4_dgessm_gpu(
        magma_tally4_order_const(*order), *m, *n, *k, *ib,
        ipiv,
        magma_tally4_ddevptr(dL1), *lddl1,
        magma_tally4_ddevptr(dL), *lddl,
        magma_tally4_ddevptr(dA), *ldda,
        info );
}

#define magma_tally4f_dgesv_gpu FORTRAN_NAME( magma_tally4f_dgesv_gpu, MAGMA_tally4F_DGESV_GPU )
void magma_tally4f_dgesv_gpu(
    magma_tally4_int_t *n, magma_tally4_int_t *nrhs,
    devptr_t *dA, magma_tally4_int_t *ldda,
    magma_tally4_int_t *ipiv,
    devptr_t *dB, magma_tally4_int_t *lddb,
    magma_tally4_int_t *info )
{
    magma_tally4_dgesv_gpu(
        *n, *nrhs,
        magma_tally4_ddevptr(dA), *ldda,
        ipiv,
        magma_tally4_ddevptr(dB), *lddb,
        info );
}

#define magma_tally4f_dgesv_nopiv_gpu FORTRAN_NAME( magma_tally4f_dgesv_nopiv_gpu, MAGMA_tally4F_DGESV_NOPIV_GPU )
void magma_tally4f_dgesv_nopiv_gpu(
    magma_tally4_int_t *n, magma_tally4_int_t *nrhs,
    devptr_t *dA, magma_tally4_int_t *ldda,
    devptr_t *dB, magma_tally4_int_t *lddb,
    magma_tally4_int_t *info )
{
    magma_tally4_dgesv_nopiv_gpu(
        *n, *nrhs,
        magma_tally4_ddevptr(dA), *ldda,
        magma_tally4_ddevptr(dB), *lddb,
        info );
}

#define magma_tally4f_dgetf2_gpu FORTRAN_NAME( magma_tally4f_dgetf2_gpu, MAGMA_tally4F_DGETF2_GPU )
void magma_tally4f_dgetf2_gpu(
    magma_tally4_int_t *m, magma_tally4_int_t *n,
    devptr_t *dA, magma_tally4_int_t *ldda,
    magma_tally4_int_t *ipiv,
    magma_tally4_int_t *info )
{
    magma_tally4_dgetf2_gpu(
        *m, *n,
        magma_tally4_ddevptr(dA), *ldda,
        ipiv,
        info );
}

#define magma_tally4f_dgetrf_gpu FORTRAN_NAME( magma_tally4f_dgetrf_gpu, MAGMA_tally4F_DGETRF_GPU )
void magma_tally4f_dgetrf_gpu(
    magma_tally4_int_t *m, magma_tally4_int_t *n,
    devptr_t *dA, magma_tally4_int_t *ldda,
    magma_tally4_int_t *ipiv,
    magma_tally4_int_t *info )
{
    magma_tally4_dgetrf_gpu(
        *m, *n,
        magma_tally4_ddevptr(dA), *ldda,
        ipiv,
        info );
}

#define magma_tally4f_dgetrf_nopiv_gpu FORTRAN_NAME( magma_tally4f_dgetrf_nopiv_gpu, MAGMA_tally4F_DGETRF_NOPIV_GPU )
void magma_tally4f_dgetrf_nopiv_gpu(
    magma_tally4_int_t *m, magma_tally4_int_t *n,
    devptr_t *dA, magma_tally4_int_t *ldda,
    magma_tally4_int_t *info )
{
    magma_tally4_dgetrf_nopiv_gpu(
        *m, *n,
        magma_tally4_ddevptr(dA), *ldda,
        info );
}

#define magma_tally4f_dgetri_gpu FORTRAN_NAME( magma_tally4f_dgetri_gpu, MAGMA_tally4F_DGETRI_GPU )
void magma_tally4f_dgetri_gpu(
    magma_tally4_int_t *n,
    devptr_t *dA, magma_tally4_int_t *ldda,
    magma_tally4_int_t *ipiv,
    devptr_t *dwork, magma_tally4_int_t *lwork,
    magma_tally4_int_t *info )
{
    magma_tally4_dgetri_gpu(
        *n,
        magma_tally4_ddevptr(dA), *ldda,
        ipiv,
        magma_tally4_ddevptr(dwork), *lwork,
        info );
}

#define magma_tally4f_dgetrs_gpu FORTRAN_NAME( magma_tally4f_dgetrs_gpu, MAGMA_tally4F_DGETRS_GPU )
void magma_tally4f_dgetrs_gpu(
    const char* trans, magma_tally4_int_t *n, magma_tally4_int_t *nrhs,
    devptr_t *dA, magma_tally4_int_t *ldda,
    magma_tally4_int_t *ipiv,
    devptr_t *dB, magma_tally4_int_t *lddb,
    magma_tally4_int_t *info )
{
    magma_tally4_dgetrs_gpu(
        magma_tally4_trans_const(*trans), *n, *nrhs,
        magma_tally4_ddevptr(dA), *ldda,
        ipiv,
        magma_tally4_ddevptr(dB), *lddb,
        info );
}

#define magma_tally4f_dgetrs_nopiv_gpu FORTRAN_NAME( magma_tally4f_dgetrs_nopiv_gpu, MAGMA_tally4F_DGETRS_NOPIV_GPU )
void magma_tally4f_dgetrs_nopiv_gpu(
    const char* trans, magma_tally4_int_t *n, magma_tally4_int_t *nrhs,
    devptr_t *dA, magma_tally4_int_t *ldda,
    devptr_t *dB, magma_tally4_int_t *lddb,
    magma_tally4_int_t *info )
{
    magma_tally4_dgetrs_nopiv_gpu(
        magma_tally4_trans_const(*trans), *n, *nrhs,
        magma_tally4_ddevptr(dA), *ldda,
        magma_tally4_ddevptr(dB), *lddb,
        info );
}

#define magma_tally4f_dsyevd_gpu FORTRAN_NAME( magma_tally4f_dsyevd_gpu, MAGMA_tally4F_DSYEVD_GPU )
void magma_tally4f_dsyevd_gpu(
    const char* jobz, const char* uplo, magma_tally4_int_t *n,
    devptr_t *dA, magma_tally4_int_t *ldda,
    double *w,
    double *wA, magma_tally4_int_t *ldwa,
    double *work, magma_tally4_int_t *lwork,
    magma_tally4_int_t *iwork, magma_tally4_int_t *liwork,
    magma_tally4_int_t *info )
{
    magma_tally4_dsyevd_gpu(
        magma_tally4_vec_const(*jobz), magma_tally4_uplo_const(*uplo), *n,
        magma_tally4_ddevptr(dA), *ldda,
        w,
        wA, *ldwa,
        work, *lwork,
        iwork, *liwork,
        info );
}

#define magma_tally4f_dsyevdx_gpu FORTRAN_NAME( magma_tally4f_dsyevdx_gpu, MAGMA_tally4F_DSYEVDX_GPU )
void magma_tally4f_dsyevdx_gpu(
    const char* jobz, const char* range, const char* uplo, magma_tally4_int_t *n,
    devptr_t *dA, magma_tally4_int_t *ldda, double *vl, double *vu, magma_tally4_int_t *il, magma_tally4_int_t *iu,
    magma_tally4_int_t *m,
    double *w,
    double *wA, magma_tally4_int_t *ldwa,
    double *work, magma_tally4_int_t *lwork,
    magma_tally4_int_t *iwork, magma_tally4_int_t *liwork,
    magma_tally4_int_t *info )
{
    magma_tally4_dsyevdx_gpu(
        magma_tally4_vec_const(*jobz), magma_tally4_range_const(*range), magma_tally4_uplo_const(*uplo), *n,
        magma_tally4_ddevptr(dA), *ldda, *vl, *vu, *il, *iu,
        m,
        w,
        wA, *ldwa,
        work, *lwork,
        iwork, *liwork,
        info );
}

#define magma_tally4f_dsygst_gpu FORTRAN_NAME( magma_tally4f_dsygst_gpu, MAGMA_tally4F_DSYGST_GPU )
void magma_tally4f_dsygst_gpu(
    magma_tally4_int_t *itype, const char* uplo, magma_tally4_int_t *n,
    devptr_t *dA, magma_tally4_int_t *ldda,
    devptr_t *dB, magma_tally4_int_t *lddb,
    magma_tally4_int_t *info )
{
    magma_tally4_dsygst_gpu(
        *itype, magma_tally4_uplo_const(*uplo), *n,
        magma_tally4_ddevptr(dA), *ldda,
        magma_tally4_ddevptr(dB), *lddb,
        info );
}

#define magma_tally4f_dsytrd_gpu FORTRAN_NAME( magma_tally4f_dsytrd_gpu, MAGMA_tally4F_DSYTRD_GPU )
void magma_tally4f_dsytrd_gpu(
    const char* uplo, magma_tally4_int_t *n,
    devptr_t *dA, magma_tally4_int_t *ldda,
    double *d,
    double *e,
    double *tau,
    double *wA, magma_tally4_int_t *ldwa,
    double *work, magma_tally4_int_t *lwork,
    magma_tally4_int_t *info )
{
    magma_tally4_dsytrd_gpu(
        magma_tally4_uplo_const(*uplo), *n,
        magma_tally4_ddevptr(dA), *ldda,
        d,
        e,
        tau,
        wA, *ldwa,
        work, *lwork,
        info );
}

#define magma_tally4f_dsytrd2_gpu FORTRAN_NAME( magma_tally4f_dsytrd2_gpu, MAGMA_tally4F_DSYTRD2_GPU )
void magma_tally4f_dsytrd2_gpu(
    const char* uplo, magma_tally4_int_t *n,
    devptr_t *dA, magma_tally4_int_t *ldda,
    double *d,
    double *e,
    double *tau,
    double *wA, magma_tally4_int_t *ldwa,
    double *work, magma_tally4_int_t *lwork,
    devptr_t *dwork, magma_tally4_int_t *ldwork,
    magma_tally4_int_t *info )
{
    magma_tally4_dsytrd2_gpu(
        magma_tally4_uplo_const(*uplo), *n,
        magma_tally4_ddevptr(dA), *ldda,
        d,
        e,
        tau,
        wA, *ldwa,
        work, *lwork,
        magma_tally4_ddevptr(dwork), *ldwork,
        info );
}

#define magma_tally4f_dsytrf_nopiv_gpu FORTRAN_NAME( magma_tally4f_dsytrf_nopiv_gpu, MAGMA_tally4F_DSYTRF_NOPIV_GPU )
void magma_tally4f_dsytrf_nopiv_gpu(
    const char* uplo, magma_tally4_int_t *n,
    devptr_t *da, magma_tally4_int_t *ldda,
    magma_tally4_int_t *info )
{
    magma_tally4_dsytrf_nopiv_gpu(
        magma_tally4_uplo_const(*uplo), *n,
        magma_tally4_ddevptr(da), *ldda,
        info );
}

#define magma_tally4f_dlarf_gpu FORTRAN_NAME( magma_tally4f_dlarf_gpu, MAGMA_tally4F_DLARF_GPU )
void magma_tally4f_dlarf_gpu(
    magma_tally4_int_t *m, magma_tally4_int_t *n,
    devptr_t *dv,
    devptr_t *dtau,
    devptr_t *dC, magma_tally4_int_t *lddc )
{
    magma_tally4_dlarf_gpu(
        *m, *n,
        magma_tally4_ddevptr(dv),
        magma_tally4_ddevptr(dtau),
        magma_tally4_ddevptr(dC), *lddc );
}

#define magma_tally4f_dlarfb_gpu FORTRAN_NAME( magma_tally4f_dlarfb_gpu, MAGMA_tally4F_DLARFB_GPU )
void magma_tally4f_dlarfb_gpu(
    const char* side, const char* trans, const char* direct, const char* storev, magma_tally4_int_t *m, magma_tally4_int_t *n, magma_tally4_int_t *k,
    devptr_t *dV, magma_tally4_int_t *lddv,
    devptr_t *dT, magma_tally4_int_t *lddt,
    devptr_t *dC, magma_tally4_int_t *lddc,
    devptr_t *dwork, magma_tally4_int_t *ldwork )
{
    magma_tally4_dlarfb_gpu(
        magma_tally4_side_const(*side), magma_tally4_trans_const(*trans), magma_tally4_direct_const(*direct), magma_tally4_storev_const(*storev), *m, *n, *k,
        magma_tally4_ddevptr(dV), *lddv,
        magma_tally4_ddevptr(dT), *lddt,
        magma_tally4_ddevptr(dC), *lddc,
        magma_tally4_ddevptr(dwork), *ldwork );
}

#define magma_tally4f_dlarfb_gpu_gemm FORTRAN_NAME( magma_tally4f_dlarfb_gpu_gemm, MAGMA_tally4F_DLARFB_GPU_GEMM )
void magma_tally4f_dlarfb_gpu_gemm(
    const char* side, const char* trans, const char* direct, const char* storev, magma_tally4_int_t *m, magma_tally4_int_t *n, magma_tally4_int_t *k,
    devptr_t *dV, magma_tally4_int_t *lddv,
    devptr_t *dT, magma_tally4_int_t *lddt,
    devptr_t *dC, magma_tally4_int_t *lddc,
    devptr_t *dwork, magma_tally4_int_t *ldwork,
    devptr_t *dworkvt, magma_tally4_int_t *ldworkvt )
{
    magma_tally4_dlarfb_gpu_gemm(
        magma_tally4_side_const(*side), magma_tally4_trans_const(*trans), magma_tally4_direct_const(*direct), magma_tally4_storev_const(*storev), *m, *n, *k,
        magma_tally4_ddevptr(dV), *lddv,
        magma_tally4_ddevptr(dT), *lddt,
        magma_tally4_ddevptr(dC), *lddc,
        magma_tally4_ddevptr(dwork), *ldwork,
        magma_tally4_ddevptr(dworkvt), *ldworkvt );
}

#define magma_tally4f_dlarfb2_gpu FORTRAN_NAME( magma_tally4f_dlarfb2_gpu, MAGMA_tally4F_DLARFB2_GPU )
void magma_tally4f_dlarfb2_gpu(
    magma_tally4_int_t *m, magma_tally4_int_t *n, magma_tally4_int_t *k,
    devptr_t *dV, magma_tally4_int_t *lddv,
    devptr_t *dT, magma_tally4_int_t *lddt,
    devptr_t *dC, magma_tally4_int_t *lddc,
    devptr_t *dwork, magma_tally4_int_t *ldwork )
{
    magma_tally4_dlarfb2_gpu(
        *m, *n, *k,
        magma_tally4_ddevptr(dV), *lddv,
        magma_tally4_ddevptr(dT), *lddt,
        magma_tally4_ddevptr(dC), *lddc,
        magma_tally4_ddevptr(dwork), *ldwork );
}

#define magma_tally4f_dlauum_gpu FORTRAN_NAME( magma_tally4f_dlauum_gpu, MAGMA_tally4F_DLAUUM_GPU )
void magma_tally4f_dlauum_gpu(
    const char* uplo, magma_tally4_int_t *n,
    devptr_t *dA, magma_tally4_int_t *ldda,
    magma_tally4_int_t *info )
{
    magma_tally4_dlauum_gpu(
        magma_tally4_uplo_const(*uplo), *n,
        magma_tally4_ddevptr(dA), *ldda,
        info );
}

#define magma_tally4f_dposv_gpu FORTRAN_NAME( magma_tally4f_dposv_gpu, MAGMA_tally4F_DPOSV_GPU )
void magma_tally4f_dposv_gpu(
    const char* uplo, magma_tally4_int_t *n, magma_tally4_int_t *nrhs,
    devptr_t *dA, magma_tally4_int_t *ldda,
    devptr_t *dB, magma_tally4_int_t *lddb,
    magma_tally4_int_t *info )
{
    magma_tally4_dposv_gpu(
        magma_tally4_uplo_const(*uplo), *n, *nrhs,
        magma_tally4_ddevptr(dA), *ldda,
        magma_tally4_ddevptr(dB), *lddb,
        info );
}

#define magma_tally4f_dpotf2_gpu FORTRAN_NAME( magma_tally4f_dpotf2_gpu, MAGMA_tally4F_DPOTF2_GPU )
void magma_tally4f_dpotf2_gpu(
    const char* uplo, magma_tally4_int_t *n,
    devptr_t *dA, magma_tally4_int_t *ldda,
    magma_tally4_int_t *info )
{
    magma_tally4_dpotf2_gpu(
        magma_tally4_uplo_const(*uplo), *n,
        magma_tally4_ddevptr(dA), *ldda,
        info );
}

#define magma_tally4f_dpotrf_gpu FORTRAN_NAME( magma_tally4f_dpotrf_gpu, MAGMA_tally4F_DPOTRF_GPU )
void magma_tally4f_dpotrf_gpu(
    const char* uplo, magma_tally4_int_t *n,
    devptr_t *dA, magma_tally4_int_t *ldda,
    magma_tally4_int_t *info )
{
    magma_tally4_dpotrf_gpu(
        magma_tally4_uplo_const(*uplo), *n,
        magma_tally4_ddevptr(dA), *ldda,
        info );
}

#define magma_tally4f_dpotri_gpu FORTRAN_NAME( magma_tally4f_dpotri_gpu, MAGMA_tally4F_DPOTRI_GPU )
void magma_tally4f_dpotri_gpu(
    const char* uplo, magma_tally4_int_t *n,
    devptr_t *dA, magma_tally4_int_t *ldda,
    magma_tally4_int_t *info )
{
    magma_tally4_dpotri_gpu(
        magma_tally4_uplo_const(*uplo), *n,
        magma_tally4_ddevptr(dA), *ldda,
        info );
}

#define magma_tally4f_dpotrs_gpu FORTRAN_NAME( magma_tally4f_dpotrs_gpu, MAGMA_tally4F_DPOTRS_GPU )
void magma_tally4f_dpotrs_gpu(
    const char* uplo, magma_tally4_int_t *n, magma_tally4_int_t *nrhs,
    devptr_t *dA, magma_tally4_int_t *ldda,
    devptr_t *dB, magma_tally4_int_t *lddb,
    magma_tally4_int_t *info )
{
    magma_tally4_dpotrs_gpu(
        magma_tally4_uplo_const(*uplo), *n, *nrhs,
        magma_tally4_ddevptr(dA), *ldda,
        magma_tally4_ddevptr(dB), *lddb,
        info );
}

#define magma_tally4f_dssssm_gpu FORTRAN_NAME( magma_tally4f_dssssm_gpu, MAGMA_tally4F_DSSSSM_GPU )
void magma_tally4f_dssssm_gpu(
    const char* order, magma_tally4_int_t *m1, magma_tally4_int_t *n1, magma_tally4_int_t *m2, magma_tally4_int_t *n2, magma_tally4_int_t *k, magma_tally4_int_t *ib,
    devptr_t *dA1, magma_tally4_int_t *ldda1,
    devptr_t *dA2, magma_tally4_int_t *ldda2,
    devptr_t *dL1, magma_tally4_int_t *lddl1,
    devptr_t *dL2, magma_tally4_int_t *lddl2,
    magma_tally4_int_t *ipiv,
    magma_tally4_int_t *info )
{
    magma_tally4_dssssm_gpu(
        magma_tally4_order_const(*order), *m1, *n1, *m2, *n2, *k, *ib,
        magma_tally4_ddevptr(dA1), *ldda1,
        magma_tally4_ddevptr(dA2), *ldda2,
        magma_tally4_ddevptr(dL1), *lddl1,
        magma_tally4_ddevptr(dL2), *lddl2,
        ipiv,
        info );
}

#define magma_tally4f_dtrtri_gpu FORTRAN_NAME( magma_tally4f_dtrtri_gpu, MAGMA_tally4F_DTRTRI_GPU )
void magma_tally4f_dtrtri_gpu(
    const char* uplo, const char* diag, magma_tally4_int_t *n,
    devptr_t *dA, magma_tally4_int_t *ldda,
    magma_tally4_int_t *info )
{
    magma_tally4_dtrtri_gpu(
        magma_tally4_uplo_const(*uplo), magma_tally4_diag_const(*diag), *n,
        magma_tally4_ddevptr(dA), *ldda,
        info );
}

#define magma_tally4f_dorgqr_gpu FORTRAN_NAME( magma_tally4f_dorgqr_gpu, MAGMA_tally4F_DORGQR_GPU )
void magma_tally4f_dorgqr_gpu(
    magma_tally4_int_t *m, magma_tally4_int_t *n, magma_tally4_int_t *k,
    devptr_t *dA, magma_tally4_int_t *ldda,
    double *tau,
    devptr_t *dT, magma_tally4_int_t *nb,
    magma_tally4_int_t *info )
{
    magma_tally4_dorgqr_gpu(
        *m, *n, *k,
        magma_tally4_ddevptr(dA), *ldda,
        tau,
        magma_tally4_ddevptr(dT), *nb,
        info );
}

#define magma_tally4f_dormql2_gpu FORTRAN_NAME( magma_tally4f_dormql2_gpu, MAGMA_tally4F_DORMQL2_GPU )
void magma_tally4f_dormql2_gpu(
    const char* side, const char* trans, magma_tally4_int_t *m, magma_tally4_int_t *n, magma_tally4_int_t *k,
    devptr_t *dA, magma_tally4_int_t *ldda,
    double *tau,
    devptr_t *dC, magma_tally4_int_t *lddc,
    double *wA, magma_tally4_int_t *ldwa,
    magma_tally4_int_t *info )
{
    magma_tally4_dormql2_gpu(
        magma_tally4_side_const(*side), magma_tally4_trans_const(*trans), *m, *n, *k,
        magma_tally4_ddevptr(dA), *ldda,
        tau,
        magma_tally4_ddevptr(dC), *lddc,
        wA, *ldwa,
        info );
}

#define magma_tally4f_dormqr_gpu FORTRAN_NAME( magma_tally4f_dormqr_gpu, MAGMA_tally4F_DORMQR_GPU )
void magma_tally4f_dormqr_gpu(
    const char* side, const char* trans, magma_tally4_int_t *m, magma_tally4_int_t *n, magma_tally4_int_t *k,
    devptr_t *dA, magma_tally4_int_t *ldda,
    double *tau,
    devptr_t *dC, magma_tally4_int_t *lddc,
    double *hwork, magma_tally4_int_t *lwork,
    devptr_t *dT, magma_tally4_int_t *nb,
    magma_tally4_int_t *info )
{
    magma_tally4_dormqr_gpu(
        magma_tally4_side_const(*side), magma_tally4_trans_const(*trans), *m, *n, *k,
        magma_tally4_ddevptr(dA), *ldda,
        tau,
        magma_tally4_ddevptr(dC), *lddc,
        hwork, *lwork,
        magma_tally4_ddevptr(dT), *nb,
        info );
}

#define magma_tally4f_dormqr2_gpu FORTRAN_NAME( magma_tally4f_dormqr2_gpu, MAGMA_tally4F_DORMQR2_GPU )
void magma_tally4f_dormqr2_gpu(
    const char* side, const char* trans, magma_tally4_int_t *m, magma_tally4_int_t *n, magma_tally4_int_t *k,
    devptr_t *dA, magma_tally4_int_t *ldda,
    double *tau,
    devptr_t *dC, magma_tally4_int_t *lddc,
    double *wA, magma_tally4_int_t *ldwa,
    magma_tally4_int_t *info )
{
    magma_tally4_dormqr2_gpu(
        magma_tally4_side_const(*side), magma_tally4_trans_const(*trans), *m, *n, *k,
        magma_tally4_ddevptr(dA), *ldda,
        tau,
        magma_tally4_ddevptr(dC), *lddc,
        wA, *ldwa,
        info );
}

#define magma_tally4f_dormtr_gpu FORTRAN_NAME( magma_tally4f_dormtr_gpu, MAGMA_tally4F_DORMTR_GPU )
void magma_tally4f_dormtr_gpu(
    const char* side, const char* uplo, const char* trans, magma_tally4_int_t *m, magma_tally4_int_t *n,
    devptr_t *dA, magma_tally4_int_t *ldda,
    double *tau,
    devptr_t *dC, magma_tally4_int_t *lddc,
    double *wA, magma_tally4_int_t *ldwa,
    magma_tally4_int_t *info )
{
    magma_tally4_dormtr_gpu(
        magma_tally4_side_const(*side), magma_tally4_uplo_const(*uplo), magma_tally4_trans_const(*trans), *m, *n,
        magma_tally4_ddevptr(dA), *ldda,
        tau,
        magma_tally4_ddevptr(dC), *lddc,
        wA, *ldwa,
        info );
}

#define magma_tally4f_dnan_inf FORTRAN_NAME( magma_tally4f_dnan_inf, MAGMA_tally4F_DNAN_INF )
void magma_tally4f_dnan_inf(
    const char* uplo, magma_tally4_int_t *m, magma_tally4_int_t *n,
    const double *A, magma_tally4_int_t *lda,
    magma_tally4_int_t *cnt_nan,
    magma_tally4_int_t *cnt_inf )
{
    magma_tally4_dnan_inf(
        magma_tally4_uplo_const(*uplo), *m, *n,
        A, *lda,
        cnt_nan,
        cnt_inf );
}

#define magma_tally4f_dnan_inf_gpu FORTRAN_NAME( magma_tally4f_dnan_inf_gpu, MAGMA_tally4F_DNAN_INF_GPU )
void magma_tally4f_dnan_inf_gpu(
    const char* uplo, magma_tally4_int_t *m, magma_tally4_int_t *n,
    devptr_t *dA, magma_tally4_int_t *ldda,
    magma_tally4_int_t *cnt_nan,
    magma_tally4_int_t *cnt_inf )
{
    magma_tally4_dnan_inf_gpu(
        magma_tally4_uplo_const(*uplo), *m, *n,
        magma_tally4_ddevptr(dA), *ldda,
        cnt_nan,
        cnt_inf );
}

#define magma_tally4f_dprint FORTRAN_NAME( magma_tally4f_dprint, MAGMA_tally4F_DPRINT )
void magma_tally4f_dprint(
    magma_tally4_int_t *m, magma_tally4_int_t *n,
    const double *A, magma_tally4_int_t *lda )
{
    magma_tally4_dprint(
        *m, *n,
        A, *lda );
}

#define magma_tally4f_dprint_gpu FORTRAN_NAME( magma_tally4f_dprint_gpu, MAGMA_tally4F_DPRINT_GPU )
void magma_tally4f_dprint_gpu(
    magma_tally4_int_t *m, magma_tally4_int_t *n,
    devptr_t *dA, magma_tally4_int_t *ldda )
{
    magma_tally4_dprint_gpu(
        *m, *n,
        magma_tally4_ddevptr(dA), *ldda );
}


#ifdef __cplusplus
}
#endif
