/*******************************************************************************
 *  This file is AUTOMATICALLY GENERATED by:
 *  ../tools/fortran_wrappers.pl ../include/magma_tally2_s.i
 *  Do not edit.
 ******************************************************************************/

#include <stdint.h>  // for uintptr_t

#include "magma_tally2.h"
#include "magma_tally2_mangling.h"

/*
 * typedef comming from fortran.h file provided in CUDADIR/src directory
 * it will probably change with future release of CUDA when they use 64 bit addresses
 */
typedef size_t devptr_t;

#ifdef PGI_FORTRAN
    #define magma_tally2_idevptr(ptr_) ((int*)               (ptr_))
    #define magma_tally2_zdevptr(ptr_) ((magma_tally2DoubleComplex*)(ptr_))
    #ifndef magma_tally2_cdevptr
    #define magma_tally2_cdevptr(ptr_) ((magma_tally2FloatComplex*) (ptr_))
    #endif
    #ifndef magma_tally2_ddevptr
    #define magma_tally2_ddevptr(ptr_) ((double*)            (ptr_))
    #endif
    #ifndef magma_tally2_sdevptr
    #define magma_tally2_sdevptr(ptr_) ((float*)             (ptr_))
    #endif
#else
    #define magma_tally2_idevptr(ptr_) ((int*)               (uintptr_t)(*(ptr_)))
    #define magma_tally2_zdevptr(ptr_) ((magma_tally2DoubleComplex*)(uintptr_t)(*(ptr_)))
    #ifndef magma_tally2_cdevptr
    #define magma_tally2_cdevptr(ptr_) ((magma_tally2FloatComplex*) (uintptr_t)(*(ptr_)))
    #endif
    #ifndef magma_tally2_ddevptr
    #define magma_tally2_ddevptr(ptr_) ((double*)            (uintptr_t)(*(ptr_)))
    #endif
    #ifndef magma_tally2_sdevptr
    #define magma_tally2_sdevptr(ptr_) ((float*)             (uintptr_t)(*(ptr_)))
    #endif
#endif

#ifdef __cplusplus
extern "C" {
#endif

#define magma_tally2f_get_slaex3_m_nb FORTRAN_NAME( magma_tally2f_get_slaex3_m_nb, MAGMA_tally2F_GET_SLAEX3_M_NB )
void magma_tally2f_get_slaex3_m_nb(
     )
{
    magma_tally2_get_slaex3_m_nb(
         );
}

#define magma_tally2f_get_spotrf_nb FORTRAN_NAME( magma_tally2f_get_spotrf_nb, MAGMA_tally2F_GET_SPOTRF_NB )
magma_tally2_int_t magma_tally2f_get_spotrf_nb( magma_tally2_int_t *m )
{
    return magma_tally2_get_spotrf_nb( *m );
}

#define magma_tally2f_get_sgetrf_nb FORTRAN_NAME( magma_tally2f_get_sgetrf_nb, MAGMA_tally2F_GET_SGETRF_NB )
magma_tally2_int_t magma_tally2f_get_sgetrf_nb( magma_tally2_int_t *m )
{
    return magma_tally2_get_sgetrf_nb( *m );
}

#define magma_tally2f_get_sgetri_nb FORTRAN_NAME( magma_tally2f_get_sgetri_nb, MAGMA_tally2F_GET_SGETRI_NB )
magma_tally2_int_t magma_tally2f_get_sgetri_nb( magma_tally2_int_t *m )
{
    return magma_tally2_get_sgetri_nb( *m );
}

#define magma_tally2f_get_sgeqp3_nb FORTRAN_NAME( magma_tally2f_get_sgeqp3_nb, MAGMA_tally2F_GET_SGEQP3_NB )
magma_tally2_int_t magma_tally2f_get_sgeqp3_nb( magma_tally2_int_t *m )
{
    return magma_tally2_get_sgeqp3_nb( *m );
}

#define magma_tally2f_get_sgeqrf_nb FORTRAN_NAME( magma_tally2f_get_sgeqrf_nb, MAGMA_tally2F_GET_SGEQRF_NB )
magma_tally2_int_t magma_tally2f_get_sgeqrf_nb( magma_tally2_int_t *m )
{
    return magma_tally2_get_sgeqrf_nb( *m );
}

#define magma_tally2f_get_sgeqlf_nb FORTRAN_NAME( magma_tally2f_get_sgeqlf_nb, MAGMA_tally2F_GET_SGEQLF_NB )
magma_tally2_int_t magma_tally2f_get_sgeqlf_nb( magma_tally2_int_t *m )
{
    return magma_tally2_get_sgeqlf_nb( *m );
}

#define magma_tally2f_get_sgehrd_nb FORTRAN_NAME( magma_tally2f_get_sgehrd_nb, MAGMA_tally2F_GET_SGEHRD_NB )
magma_tally2_int_t magma_tally2f_get_sgehrd_nb( magma_tally2_int_t *m )
{
    return magma_tally2_get_sgehrd_nb( *m );
}

#define magma_tally2f_get_ssytrd_nb FORTRAN_NAME( magma_tally2f_get_ssytrd_nb, MAGMA_tally2F_GET_SSYTRD_NB )
magma_tally2_int_t magma_tally2f_get_ssytrd_nb( magma_tally2_int_t *m )
{
    return magma_tally2_get_ssytrd_nb( *m );
}

#define magma_tally2f_get_ssytrf_nb FORTRAN_NAME( magma_tally2f_get_ssytrf_nb, MAGMA_tally2F_GET_SSYTRF_NB )
magma_tally2_int_t magma_tally2f_get_ssytrf_nb( magma_tally2_int_t *m )
{
    return magma_tally2_get_ssytrf_nb( *m );
}

#define magma_tally2f_get_ssytrf_nopiv_tally2_nb FORTRAN_NAME( magma_tally2f_get_ssytrf_nopiv_tally2_nb, MAGMA_tally2F_GET_SSYTRF_NOPIV_NB )
magma_tally2_int_t magma_tally2f_get_ssytrf_nopiv_tally2_nb( magma_tally2_int_t *m )
{
    return magma_tally2_get_ssytrf_nopiv_tally2_nb( *m );
}

#define magma_tally2f_get_sgelqf_nb FORTRAN_NAME( magma_tally2f_get_sgelqf_nb, MAGMA_tally2F_GET_SGELQF_NB )
magma_tally2_int_t magma_tally2f_get_sgelqf_nb( magma_tally2_int_t *m )
{
    return magma_tally2_get_sgelqf_nb( *m );
}

#define magma_tally2f_get_sgebrd_nb FORTRAN_NAME( magma_tally2f_get_sgebrd_nb, MAGMA_tally2F_GET_SGEBRD_NB )
magma_tally2_int_t magma_tally2f_get_sgebrd_nb( magma_tally2_int_t *m )
{
    return magma_tally2_get_sgebrd_nb( *m );
}

#define magma_tally2f_get_ssygst_nb FORTRAN_NAME( magma_tally2f_get_ssygst_nb, MAGMA_tally2F_GET_SSYGST_NB )
magma_tally2_int_t magma_tally2f_get_ssygst_nb( magma_tally2_int_t *m )
{
    return magma_tally2_get_ssygst_nb( *m );
}

#define magma_tally2f_get_sgesvd_nb FORTRAN_NAME( magma_tally2f_get_sgesvd_nb, MAGMA_tally2F_GET_SGESVD_NB )
magma_tally2_int_t magma_tally2f_get_sgesvd_nb( magma_tally2_int_t *m )
{
    return magma_tally2_get_sgesvd_nb( *m );
}

#define magma_tally2f_get_ssygst_nb_m FORTRAN_NAME( magma_tally2f_get_ssygst_nb_m, MAGMA_tally2F_GET_SSYGST_NB_M )
magma_tally2_int_t magma_tally2f_get_ssygst_nb_m( magma_tally2_int_t *m )
{
    return magma_tally2_get_ssygst_nb_m( *m );
}

#define magma_tally2f_get_sbulge_nb FORTRAN_NAME( magma_tally2f_get_sbulge_nb, MAGMA_tally2F_GET_SBULGE_NB )
void magma_tally2f_get_sbulge_nb(
    magma_tally2_int_t *m, magma_tally2_int_t *nbthreads )
{
    magma_tally2_get_sbulge_nb(
        *m, *nbthreads );
}

#define magma_tally2f_sbulge_get_Vblksiz FORTRAN_NAME( magma_tally2f_sbulge_get_Vblksiz, MAGMA_tally2F_SBULGE_GET_VBLKSIZ )
void magma_tally2f_sbulge_get_Vblksiz(
    magma_tally2_int_t *m, magma_tally2_int_t *nb, magma_tally2_int_t *nbthreads )
{
    magma_tally2_sbulge_get_Vblksiz(
        *m, *nb, *nbthreads );
}

#define magma_tally2f_get_sbulge_gcperf FORTRAN_NAME( magma_tally2f_get_sbulge_gcperf, MAGMA_tally2F_GET_SBULGE_GCPERF )
void magma_tally2f_get_sbulge_gcperf(
     )
{
    magma_tally2_get_sbulge_gcperf(
         );
}

#define magma_tally2f_smove_eig FORTRAN_NAME( magma_tally2f_smove_eig, MAGMA_tally2F_SMOVE_EIG )
void magma_tally2f_smove_eig(
    const char* range, magma_tally2_int_t *n,
    float *w,
    magma_tally2_int_t *il,
    magma_tally2_int_t *iu, float *vl, float *vu,
    magma_tally2_int_t *m )
{
    magma_tally2_smove_eig(
        magma_tally2_range_const(*range), *n,
        w,
        il,
        iu, *vl, *vu,
        m );
}

#define magma_tally2f_svrange FORTRAN_NAME( magma_tally2f_svrange, MAGMA_tally2F_SVRANGE )
void magma_tally2f_svrange(
    magma_tally2_int_t *k,
    float *d,
    magma_tally2_int_t *il,
    magma_tally2_int_t *iu, float *vl, float *vu )
{
    magma_tally2_svrange(
        *k,
        d,
        il,
        iu, *vl, *vu );
}

#define magma_tally2f_sirange FORTRAN_NAME( magma_tally2f_sirange, MAGMA_tally2F_SIRANGE )
void magma_tally2f_sirange(
    magma_tally2_int_t *k,
    magma_tally2_int_t *indxq,
    magma_tally2_int_t *iil,
    magma_tally2_int_t *iiu, magma_tally2_int_t *il, magma_tally2_int_t *iu )
{
    magma_tally2_sirange(
        *k,
        indxq,
        iil,
        iiu, *il, *iu );
}

#define magma_tally2f_sgebrd FORTRAN_NAME( magma_tally2f_sgebrd, MAGMA_tally2F_SGEBRD )
void magma_tally2f_sgebrd(
    magma_tally2_int_t *m, magma_tally2_int_t *n,
    float *A, magma_tally2_int_t *lda,
    float *d,
    float *e,
    float *tauq,
    float *taup,
    float *work, magma_tally2_int_t *lwork,
    magma_tally2_int_t *info )
{
    magma_tally2_sgebrd(
        *m, *n,
        A, *lda,
        d,
        e,
        tauq,
        taup,
        work, *lwork,
        info );
}

#define magma_tally2f_sgeev FORTRAN_NAME( magma_tally2f_sgeev, MAGMA_tally2F_SGEEV )
void magma_tally2f_sgeev(
    const char* jobvl, const char* jobvr, magma_tally2_int_t *n,
    float *A, magma_tally2_int_t *lda,
    float *wr,
    float *wi,
    float *VL, magma_tally2_int_t *ldvl,
    float *VR, magma_tally2_int_t *ldvr,
    float *work, magma_tally2_int_t *lwork,
    magma_tally2_int_t *info )
{
    magma_tally2_sgeev(
        magma_tally2_vec_const(*jobvl), magma_tally2_vec_const(*jobvr), *n,
        A, *lda,
        wr,
        wi,
        VL, *ldvl,
        VR, *ldvr,
        work, *lwork,
        info );
}

#define magma_tally2f_sgehrd FORTRAN_NAME( magma_tally2f_sgehrd, MAGMA_tally2F_SGEHRD )
void magma_tally2f_sgehrd(
    magma_tally2_int_t *n, magma_tally2_int_t *ilo, magma_tally2_int_t *ihi,
    float *A, magma_tally2_int_t *lda,
    float *tau,
    float *work, magma_tally2_int_t *lwork,
    devptr_t *dT,
    magma_tally2_int_t *info )
{
    magma_tally2_sgehrd(
        *n, *ilo, *ihi,
        A, *lda,
        tau,
        work, *lwork,
        magma_tally2_sdevptr(dT),
        info );
}

#define magma_tally2f_sgehrd2 FORTRAN_NAME( magma_tally2f_sgehrd2, MAGMA_tally2F_SGEHRD2 )
void magma_tally2f_sgehrd2(
    magma_tally2_int_t *n, magma_tally2_int_t *ilo, magma_tally2_int_t *ihi,
    float *A, magma_tally2_int_t *lda,
    float *tau,
    float *work, magma_tally2_int_t *lwork,
    magma_tally2_int_t *info )
{
    magma_tally2_sgehrd2(
        *n, *ilo, *ihi,
        A, *lda,
        tau,
        work, *lwork,
        info );
}

#define magma_tally2f_sgelqf FORTRAN_NAME( magma_tally2f_sgelqf, MAGMA_tally2F_SGELQF )
void magma_tally2f_sgelqf(
    magma_tally2_int_t *m, magma_tally2_int_t *n,
    float *A, magma_tally2_int_t *lda,
    float *tau,
    float *work, magma_tally2_int_t *lwork,
    magma_tally2_int_t *info )
{
    magma_tally2_sgelqf(
        *m, *n,
        A, *lda,
        tau,
        work, *lwork,
        info );
}

#define magma_tally2f_sgeqlf FORTRAN_NAME( magma_tally2f_sgeqlf, MAGMA_tally2F_SGEQLF )
void magma_tally2f_sgeqlf(
    magma_tally2_int_t *m, magma_tally2_int_t *n,
    float *A, magma_tally2_int_t *lda,
    float *tau,
    float *work, magma_tally2_int_t *lwork,
    magma_tally2_int_t *info )
{
    magma_tally2_sgeqlf(
        *m, *n,
        A, *lda,
        tau,
        work, *lwork,
        info );
}

#define magma_tally2f_sgeqp3 FORTRAN_NAME( magma_tally2f_sgeqp3, MAGMA_tally2F_SGEQP3 )
void magma_tally2f_sgeqp3(
    magma_tally2_int_t *m, magma_tally2_int_t *n,
    float *A, magma_tally2_int_t *lda,
    magma_tally2_int_t *jpvt,
    float *tau,
    float *work, magma_tally2_int_t *lwork,
    magma_tally2_int_t *info )
{
    magma_tally2_sgeqp3(
        *m, *n,
        A, *lda,
        jpvt,
        tau,
        work, *lwork,
        info );
}

#define magma_tally2f_sgeqrf FORTRAN_NAME( magma_tally2f_sgeqrf, MAGMA_tally2F_SGEQRF )
void magma_tally2f_sgeqrf(
    magma_tally2_int_t *m, magma_tally2_int_t *n,
    float *A, magma_tally2_int_t *lda,
    float *tau,
    float *work, magma_tally2_int_t *lwork,
    magma_tally2_int_t *info )
{
    magma_tally2_sgeqrf(
        *m, *n,
        A, *lda,
        tau,
        work, *lwork,
        info );
}

#define magma_tally2f_sgeqrf_ooc FORTRAN_NAME( magma_tally2f_sgeqrf_ooc, MAGMA_tally2F_SGEQRF_OOC )
void magma_tally2f_sgeqrf_ooc(
    magma_tally2_int_t *m, magma_tally2_int_t *n,
    float *A, magma_tally2_int_t *lda,
    float *tau,
    float *work, magma_tally2_int_t *lwork,
    magma_tally2_int_t *info )
{
    magma_tally2_sgeqrf_ooc(
        *m, *n,
        A, *lda,
        tau,
        work, *lwork,
        info );
}

#define magma_tally2f_sgeqrf4 FORTRAN_NAME( magma_tally2f_sgeqrf4, MAGMA_tally2F_SGEQRF4 )
void magma_tally2f_sgeqrf4(
    magma_tally2_int_t *ngpu, magma_tally2_int_t *m, magma_tally2_int_t *n,
    float *A, magma_tally2_int_t *lda,
    float *tau,
    float *work, magma_tally2_int_t *lwork,
    magma_tally2_int_t *info )
{
    magma_tally2_sgeqrf4(
        *ngpu, *m, *n,
        A, *lda,
        tau,
        work, *lwork,
        info );
}

#define magma_tally2f_sgesdd FORTRAN_NAME( magma_tally2f_sgesdd, MAGMA_tally2F_SGESDD )
void magma_tally2f_sgesdd(
    const char* jobz, magma_tally2_int_t *m, magma_tally2_int_t *n,
    float *A, magma_tally2_int_t *lda,
    float *s,
    float *U, magma_tally2_int_t *ldu,
    float *VT, magma_tally2_int_t *ldvt,
    float *work, magma_tally2_int_t *lwork,
    magma_tally2_int_t *iwork,
    magma_tally2_int_t *info )
{
    magma_tally2_sgesdd(
        magma_tally2_vec_const(*jobz), *m, *n,
        A, *lda,
        s,
        U, *ldu,
        VT, *ldvt,
        work, *lwork,
        iwork,
        info );
}

#define magma_tally2f_sgesv FORTRAN_NAME( magma_tally2f_sgesv, MAGMA_tally2F_SGESV )
void magma_tally2f_sgesv(
    magma_tally2_int_t *n, magma_tally2_int_t *nrhs,
    float *A, magma_tally2_int_t *lda,
    magma_tally2_int_t *ipiv,
    float *B, magma_tally2_int_t *ldb,
    magma_tally2_int_t *info )
{
    magma_tally2_sgesv(
        *n, *nrhs,
        A, *lda,
        ipiv,
        B, *ldb,
        info );
}

#define magma_tally2f_sgesv_rbt FORTRAN_NAME( magma_tally2f_sgesv_rbt, MAGMA_tally2F_SGESV_RBT )
void magma_tally2f_sgesv_rbt(
    const char* ref, magma_tally2_int_t *n, magma_tally2_int_t *nrhs,
    float *A, magma_tally2_int_t *lda,
    float *B, magma_tally2_int_t *ldb,
    magma_tally2_int_t *info )
{
    magma_tally2_sgesv_rbt(
        magma_tally2_bool_const(*ref), *n, *nrhs,
        A, *lda,
        B, *ldb,
        info );
}

#define magma_tally2f_sgesvd FORTRAN_NAME( magma_tally2f_sgesvd, MAGMA_tally2F_SGESVD )
void magma_tally2f_sgesvd(
    const char* jobu, const char* jobvt, magma_tally2_int_t *m, magma_tally2_int_t *n,
    float *A, magma_tally2_int_t *lda,
    float *s,
    float *U, magma_tally2_int_t *ldu,
    float *VT, magma_tally2_int_t *ldvt,
    float *work, magma_tally2_int_t *lwork,
    magma_tally2_int_t *info )
{
    magma_tally2_sgesvd(
        magma_tally2_vec_const(*jobu), magma_tally2_vec_const(*jobvt), *m, *n,
        A, *lda,
        s,
        U, *ldu,
        VT, *ldvt,
        work, *lwork,
        info );
}

#define magma_tally2f_sgetf2_nopiv FORTRAN_NAME( magma_tally2f_sgetf2_nopiv, MAGMA_tally2F_SGETF2_NOPIV )
void magma_tally2f_sgetf2_nopiv(
    magma_tally2_int_t *m, magma_tally2_int_t *n,
    float *A, magma_tally2_int_t *lda,
    magma_tally2_int_t *info )
{
    magma_tally2_sgetf2_nopiv(
        *m, *n,
        A, *lda,
        info );
}

#define magma_tally2f_sgetrf FORTRAN_NAME( magma_tally2f_sgetrf, MAGMA_tally2F_SGETRF )
void magma_tally2f_sgetrf(
    magma_tally2_int_t *m, magma_tally2_int_t *n,
    float *A, magma_tally2_int_t *lda,
    magma_tally2_int_t *ipiv,
    magma_tally2_int_t *info )
{
    magma_tally2_sgetrf(
        *m, *n,
        A, *lda,
        ipiv,
        info );
}

#define magma_tally2f_sgetrf_nopiv FORTRAN_NAME( magma_tally2f_sgetrf_nopiv, MAGMA_tally2F_SGETRF_NOPIV )
void magma_tally2f_sgetrf_nopiv(
    magma_tally2_int_t *m, magma_tally2_int_t *n,
    float *A, magma_tally2_int_t *lda,
    magma_tally2_int_t *info )
{
    magma_tally2_sgetrf_nopiv(
        *m, *n,
        A, *lda,
        info );
}

#define magma_tally2f_sgetrf_piv FORTRAN_NAME( magma_tally2f_sgetrf_piv, MAGMA_tally2F_SGETRF_PIV )
void magma_tally2f_sgetrf_piv(
    magma_tally2_int_t *m, magma_tally2_int_t *n, magma_tally2_int_t *NB,
    float *A, magma_tally2_int_t *lda,
    magma_tally2_int_t *ipiv,
    magma_tally2_int_t *info )
{
    magma_tally2_sgetrf_piv(
        *m, *n, *NB,
        A, *lda,
        ipiv,
        info );
}

#define magma_tally2f_ssyevd FORTRAN_NAME( magma_tally2f_ssyevd, MAGMA_tally2F_SSYEVD )
void magma_tally2f_ssyevd(
    const char* jobz, const char* uplo, magma_tally2_int_t *n,
    float *A, magma_tally2_int_t *lda,
    float *w,
    float *work, magma_tally2_int_t *lwork,
    magma_tally2_int_t *iwork, magma_tally2_int_t *liwork,
    magma_tally2_int_t *info )
{
    magma_tally2_ssyevd(
        magma_tally2_vec_const(*jobz), magma_tally2_uplo_const(*uplo), *n,
        A, *lda,
        w,
        work, *lwork,
        iwork, *liwork,
        info );
}

#define magma_tally2f_ssyevdx FORTRAN_NAME( magma_tally2f_ssyevdx, MAGMA_tally2F_SSYEVDX )
void magma_tally2f_ssyevdx(
    const char* jobz, const char* range, const char* uplo, magma_tally2_int_t *n,
    float *A, magma_tally2_int_t *lda, float *vl, float *vu, magma_tally2_int_t *il, magma_tally2_int_t *iu,
    magma_tally2_int_t *m,
    float *w,
    float *work, magma_tally2_int_t *lwork,
    magma_tally2_int_t *iwork, magma_tally2_int_t *liwork,
    magma_tally2_int_t *info )
{
    magma_tally2_ssyevdx(
        magma_tally2_vec_const(*jobz), magma_tally2_range_const(*range), magma_tally2_uplo_const(*uplo), *n,
        A, *lda, *vl, *vu, *il, *iu,
        m,
        w,
        work, *lwork,
        iwork, *liwork,
        info );
}

#define magma_tally2f_ssyevdx_2stage FORTRAN_NAME( magma_tally2f_ssyevdx_2stage, MAGMA_tally2F_SSYEVDX_2STAGE )
void magma_tally2f_ssyevdx_2stage(
    const char* jobz, const char* range, const char* uplo, magma_tally2_int_t *n,
    float *A, magma_tally2_int_t *lda, float *vl, float *vu, magma_tally2_int_t *il, magma_tally2_int_t *iu,
    magma_tally2_int_t *m,
    float *w,
    float *work, magma_tally2_int_t *lwork,
    magma_tally2_int_t *iwork, magma_tally2_int_t *liwork,
    magma_tally2_int_t *info )
{
    magma_tally2_ssyevdx_2stage(
        magma_tally2_vec_const(*jobz), magma_tally2_range_const(*range), magma_tally2_uplo_const(*uplo), *n,
        A, *lda, *vl, *vu, *il, *iu,
        m,
        w,
        work, *lwork,
        iwork, *liwork,
        info );
}

#define magma_tally2f_ssygst FORTRAN_NAME( magma_tally2f_ssygst, MAGMA_tally2F_SSYGST )
void magma_tally2f_ssygst(
    magma_tally2_int_t *itype, const char* uplo, magma_tally2_int_t *n,
    float *A, magma_tally2_int_t *lda,
    float *B, magma_tally2_int_t *ldb,
    magma_tally2_int_t *info )
{
    magma_tally2_ssygst(
        *itype, magma_tally2_uplo_const(*uplo), *n,
        A, *lda,
        B, *ldb,
        info );
}

#define magma_tally2f_ssygvd FORTRAN_NAME( magma_tally2f_ssygvd, MAGMA_tally2F_SSYGVD )
void magma_tally2f_ssygvd(
    magma_tally2_int_t *itype, const char* jobz, const char* uplo, magma_tally2_int_t *n,
    float *A, magma_tally2_int_t *lda,
    float *B, magma_tally2_int_t *ldb,
    float *w,
    float *work, magma_tally2_int_t *lwork,
    magma_tally2_int_t *iwork, magma_tally2_int_t *liwork,
    magma_tally2_int_t *info )
{
    magma_tally2_ssygvd(
        *itype, magma_tally2_vec_const(*jobz), magma_tally2_uplo_const(*uplo), *n,
        A, *lda,
        B, *ldb,
        w,
        work, *lwork,
        iwork, *liwork,
        info );
}

#define magma_tally2f_ssygvdx FORTRAN_NAME( magma_tally2f_ssygvdx, MAGMA_tally2F_SSYGVDX )
void magma_tally2f_ssygvdx(
    magma_tally2_int_t *itype, const char* jobz, const char* range, const char* uplo, magma_tally2_int_t *n,
    float *A, magma_tally2_int_t *lda,
    float *B, magma_tally2_int_t *ldb, float *vl, float *vu, magma_tally2_int_t *il, magma_tally2_int_t *iu,
    magma_tally2_int_t *m,
    float *w,
    float *work, magma_tally2_int_t *lwork,
    magma_tally2_int_t *iwork, magma_tally2_int_t *liwork,
    magma_tally2_int_t *info )
{
    magma_tally2_ssygvdx(
        *itype, magma_tally2_vec_const(*jobz), magma_tally2_range_const(*range), magma_tally2_uplo_const(*uplo), *n,
        A, *lda,
        B, *ldb, *vl, *vu, *il, *iu,
        m,
        w,
        work, *lwork,
        iwork, *liwork,
        info );
}

#define magma_tally2f_ssygvdx_2stage FORTRAN_NAME( magma_tally2f_ssygvdx_2stage, MAGMA_tally2F_SSYGVDX_2STAGE )
void magma_tally2f_ssygvdx_2stage(
    magma_tally2_int_t *itype, const char* jobz, const char* range, const char* uplo, magma_tally2_int_t *n,
    float *A, magma_tally2_int_t *lda,
    float *B, magma_tally2_int_t *ldb, float *vl, float *vu, magma_tally2_int_t *il, magma_tally2_int_t *iu,
    magma_tally2_int_t *m,
    float *w,
    float *work, magma_tally2_int_t *lwork,
    magma_tally2_int_t *iwork, magma_tally2_int_t *liwork,
    magma_tally2_int_t *info )
{
    magma_tally2_ssygvdx_2stage(
        *itype, magma_tally2_vec_const(*jobz), magma_tally2_range_const(*range), magma_tally2_uplo_const(*uplo), *n,
        A, *lda,
        B, *ldb, *vl, *vu, *il, *iu,
        m,
        w,
        work, *lwork,
        iwork, *liwork,
        info );
}

#define magma_tally2f_ssysv FORTRAN_NAME( magma_tally2f_ssysv, MAGMA_tally2F_SSYSV )
void magma_tally2f_ssysv(
    const char* uplo, magma_tally2_int_t *n, magma_tally2_int_t *nrhs,
    float *A, magma_tally2_int_t *lda,
    magma_tally2_int_t *ipiv,
    float *B, magma_tally2_int_t *ldb,
    magma_tally2_int_t *info )
{
    magma_tally2_ssysv(
        magma_tally2_uplo_const(*uplo), *n, *nrhs,
        A, *lda,
        ipiv,
        B, *ldb,
        info );
}

#define magma_tally2f_ssytrd FORTRAN_NAME( magma_tally2f_ssytrd, MAGMA_tally2F_SSYTRD )
void magma_tally2f_ssytrd(
    const char* uplo, magma_tally2_int_t *n,
    float *A, magma_tally2_int_t *lda,
    float *d,
    float *e,
    float *tau,
    float *work, magma_tally2_int_t *lwork,
    magma_tally2_int_t *info )
{
    magma_tally2_ssytrd(
        magma_tally2_uplo_const(*uplo), *n,
        A, *lda,
        d,
        e,
        tau,
        work, *lwork,
        info );
}

#define magma_tally2f_ssytrf FORTRAN_NAME( magma_tally2f_ssytrf, MAGMA_tally2F_SSYTRF )
void magma_tally2f_ssytrf(
    const char* uplo, magma_tally2_int_t *n,
    float *A, magma_tally2_int_t *lda,
    magma_tally2_int_t *ipiv,
    magma_tally2_int_t *info )
{
    magma_tally2_ssytrf(
        magma_tally2_uplo_const(*uplo), *n,
        A, *lda,
        ipiv,
        info );
}

#define magma_tally2f_ssytrf_nopiv_tally2 FORTRAN_NAME( magma_tally2f_ssytrf_nopiv_tally2, MAGMA_tally2F_SSYTRF_NOPIV )
void magma_tally2f_ssytrf_nopiv_tally2(
    const char* uplo, magma_tally2_int_t *n,
    float *a, magma_tally2_int_t *lda,
    magma_tally2_int_t *info )
{
    magma_tally2_ssytrf_nopiv_tally2(
        magma_tally2_uplo_const(*uplo), *n,
        a, *lda,
        info );
}

#define magma_tally2f_ssytrd_sb2st FORTRAN_NAME( magma_tally2f_ssytrd_sb2st, MAGMA_tally2F_SSYTRD_SB2ST )
void magma_tally2f_ssytrd_sb2st(
    const char* uplo, magma_tally2_int_t *n, magma_tally2_int_t *nb, magma_tally2_int_t *Vblksiz,
    float *A, magma_tally2_int_t *lda,
    float *d,
    float *e,
    float *V, magma_tally2_int_t *ldv,
    float *TAU, magma_tally2_int_t *compT,
    float *T, magma_tally2_int_t *ldt )
{
    magma_tally2_ssytrd_sb2st(
        magma_tally2_uplo_const(*uplo), *n, *nb, *Vblksiz,
        A, *lda,
        d,
        e,
        V, *ldv,
        TAU, *compT,
        T, *ldt );
}

#define magma_tally2f_ssytrd_sy2sb FORTRAN_NAME( magma_tally2f_ssytrd_sy2sb, MAGMA_tally2F_SSYTRD_SY2SB )
void magma_tally2f_ssytrd_sy2sb(
    const char* uplo, magma_tally2_int_t *n, magma_tally2_int_t *nb,
    float *A, magma_tally2_int_t *lda,
    float *tau,
    float *work, magma_tally2_int_t *lwork,
    devptr_t *dT,
    magma_tally2_int_t *info )
{
    magma_tally2_ssytrd_sy2sb(
        magma_tally2_uplo_const(*uplo), *n, *nb,
        A, *lda,
        tau,
        work, *lwork,
        magma_tally2_sdevptr(dT),
        info );
}

#define magma_tally2f_slaln2 FORTRAN_NAME( magma_tally2f_slaln2, MAGMA_tally2F_SLALN2 )
void magma_tally2f_slaln2(
    magma_tally2_int_t *trans, magma_tally2_int_t *na, magma_tally2_int_t *nw, float *smin, float *ca,
    const float *A, magma_tally2_int_t *lda, float *d1, float *d2,
    const float *B, magma_tally2_int_t *ldb, float *wr, float *wi,
    float *X, magma_tally2_int_t *ldx,
    float *scale,
    float *xnorm,
    magma_tally2_int_t *info )
{
    magma_tally2_slaln2(
        *trans, *na, *nw, *smin, *ca,
        A, *lda, *d1, *d2,
        B, *ldb, *wr, *wi,
        X, *ldx,
        scale,
        xnorm,
        info );
}

#define magma_tally2f_slaqtrsd FORTRAN_NAME( magma_tally2f_slaqtrsd, MAGMA_tally2F_SLAQTRSD )
void magma_tally2f_slaqtrsd(
    const char* trans, magma_tally2_int_t *n,
    const float *T, magma_tally2_int_t *ldt,
    float *x, magma_tally2_int_t *ldx,
    const float *cnorm,
    magma_tally2_int_t *info )
{
    magma_tally2_slaqtrsd(
        magma_tally2_trans_const(*trans), *n,
        T, *ldt,
        x, *ldx,
        cnorm,
        info );
}

#define magma_tally2f_slauum FORTRAN_NAME( magma_tally2f_slauum, MAGMA_tally2F_SLAUUM )
void magma_tally2f_slauum(
    const char* uplo, magma_tally2_int_t *n,
    float *A, magma_tally2_int_t *lda,
    magma_tally2_int_t *info )
{
    magma_tally2_slauum(
        magma_tally2_uplo_const(*uplo), *n,
        A, *lda,
        info );
}

#define magma_tally2f_sposv FORTRAN_NAME( magma_tally2f_sposv, MAGMA_tally2F_SPOSV )
void magma_tally2f_sposv(
    const char* uplo, magma_tally2_int_t *n, magma_tally2_int_t *nrhs,
    float *A, magma_tally2_int_t *lda,
    float *B, magma_tally2_int_t *ldb,
    magma_tally2_int_t *info )
{
    magma_tally2_sposv(
        magma_tally2_uplo_const(*uplo), *n, *nrhs,
        A, *lda,
        B, *ldb,
        info );
}

#define magma_tally2f_spotrf FORTRAN_NAME( magma_tally2f_spotrf, MAGMA_tally2F_SPOTRF )
void magma_tally2f_spotrf(
    const char* uplo, magma_tally2_int_t *n,
    float *A, magma_tally2_int_t *lda,
    magma_tally2_int_t *info )
{
    magma_tally2_spotrf(
        magma_tally2_uplo_const(*uplo), *n,
        A, *lda,
        info );
}

#define magma_tally2f_spotri FORTRAN_NAME( magma_tally2f_spotri, MAGMA_tally2F_SPOTRI )
void magma_tally2f_spotri(
    const char* uplo, magma_tally2_int_t *n,
    float *A, magma_tally2_int_t *lda,
    magma_tally2_int_t *info )
{
    magma_tally2_spotri(
        magma_tally2_uplo_const(*uplo), *n,
        A, *lda,
        info );
}

#define magma_tally2f_sstedx FORTRAN_NAME( magma_tally2f_sstedx, MAGMA_tally2F_SSTEDX )
void magma_tally2f_sstedx(
    const char* range, magma_tally2_int_t *n, float *vl, float *vu, magma_tally2_int_t *il, magma_tally2_int_t *iu,
    float *d,
    float *e,
    float *Z, magma_tally2_int_t *ldz,
    float *rwork, magma_tally2_int_t *lrwork,
    magma_tally2_int_t *iwork, magma_tally2_int_t *liwork,
    devptr_t *dwork,
    magma_tally2_int_t *info )
{
    magma_tally2_sstedx(
        magma_tally2_range_const(*range), *n, *vl, *vu, *il, *iu,
        d,
        e,
        Z, *ldz,
        rwork, *lrwork,
        iwork, *liwork,
        magma_tally2_sdevptr(dwork),
        info );
}

#define magma_tally2f_strevc3 FORTRAN_NAME( magma_tally2f_strevc3, MAGMA_tally2F_STREVC3 )
void magma_tally2f_strevc3(
    const char* side, const char* howmany,
    magma_tally2_int_t *select, magma_tally2_int_t *n,
    float *T, magma_tally2_int_t *ldt,
    float *VL, magma_tally2_int_t *ldvl,
    float *VR, magma_tally2_int_t *ldvr, magma_tally2_int_t *mm,
    magma_tally2_int_t *mout,
    float *work, magma_tally2_int_t *lwork,
    magma_tally2_int_t *info )
{
    magma_tally2_strevc3(
        magma_tally2_side_const(*side), magma_tally2_vec_const(*howmany),
        select, *n,
        T, *ldt,
        VL, *ldvl,
        VR, *ldvr, *mm,
        mout,
        work, *lwork,
        info );
}

#define magma_tally2f_strevc3_mt FORTRAN_NAME( magma_tally2f_strevc3_mt, MAGMA_tally2F_STREVC3_MT )
void magma_tally2f_strevc3_mt(
    const char* side, const char* howmany,
    magma_tally2_int_t *select, magma_tally2_int_t *n,
    float *T, magma_tally2_int_t *ldt,
    float *VL, magma_tally2_int_t *ldvl,
    float *VR, magma_tally2_int_t *ldvr, magma_tally2_int_t *mm,
    magma_tally2_int_t *mout,
    float *work, magma_tally2_int_t *lwork,
    magma_tally2_int_t *info )
{
    magma_tally2_strevc3_mt(
        magma_tally2_side_const(*side), magma_tally2_vec_const(*howmany),
        select, *n,
        T, *ldt,
        VL, *ldvl,
        VR, *ldvr, *mm,
        mout,
        work, *lwork,
        info );
}

#define magma_tally2f_strtri FORTRAN_NAME( magma_tally2f_strtri, MAGMA_tally2F_STRTRI )
void magma_tally2f_strtri(
    const char* uplo, const char* diag, magma_tally2_int_t *n,
    float *A, magma_tally2_int_t *lda,
    magma_tally2_int_t *info )
{
    magma_tally2_strtri(
        magma_tally2_uplo_const(*uplo), magma_tally2_diag_const(*diag), *n,
        A, *lda,
        info );
}

#define magma_tally2f_sorghr FORTRAN_NAME( magma_tally2f_sorghr, MAGMA_tally2F_SORGHR )
void magma_tally2f_sorghr(
    magma_tally2_int_t *n, magma_tally2_int_t *ilo, magma_tally2_int_t *ihi,
    float *A, magma_tally2_int_t *lda,
    float *tau,
    devptr_t *dT, magma_tally2_int_t *nb,
    magma_tally2_int_t *info )
{
    magma_tally2_sorghr(
        *n, *ilo, *ihi,
        A, *lda,
        tau,
        magma_tally2_sdevptr(dT), *nb,
        info );
}

#define magma_tally2f_sorgqr FORTRAN_NAME( magma_tally2f_sorgqr, MAGMA_tally2F_SORGQR )
void magma_tally2f_sorgqr(
    magma_tally2_int_t *m, magma_tally2_int_t *n, magma_tally2_int_t *k,
    float *A, magma_tally2_int_t *lda,
    float *tau,
    devptr_t *dT, magma_tally2_int_t *nb,
    magma_tally2_int_t *info )
{
    magma_tally2_sorgqr(
        *m, *n, *k,
        A, *lda,
        tau,
        magma_tally2_sdevptr(dT), *nb,
        info );
}

#define magma_tally2f_sorgqr2 FORTRAN_NAME( magma_tally2f_sorgqr2, MAGMA_tally2F_SORGQR2 )
void magma_tally2f_sorgqr2(
    magma_tally2_int_t *m, magma_tally2_int_t *n, magma_tally2_int_t *k,
    float *A, magma_tally2_int_t *lda,
    float *tau,
    magma_tally2_int_t *info )
{
    magma_tally2_sorgqr2(
        *m, *n, *k,
        A, *lda,
        tau,
        info );
}

#define magma_tally2f_sormbr FORTRAN_NAME( magma_tally2f_sormbr, MAGMA_tally2F_SORMBR )
void magma_tally2f_sormbr(
    const char* vect, const char* side, const char* trans, magma_tally2_int_t *m, magma_tally2_int_t *n, magma_tally2_int_t *k,
    float *A, magma_tally2_int_t *lda,
    float *tau,
    float *C, magma_tally2_int_t *ldc,
    float *work, magma_tally2_int_t *lwork,
    magma_tally2_int_t *info )
{
    magma_tally2_sormbr(
        magma_tally2_vect_const(*vect), magma_tally2_side_const(*side), magma_tally2_trans_const(*trans), *m, *n, *k,
        A, *lda,
        tau,
        C, *ldc,
        work, *lwork,
        info );
}

#define magma_tally2f_sormlq FORTRAN_NAME( magma_tally2f_sormlq, MAGMA_tally2F_SORMLQ )
void magma_tally2f_sormlq(
    const char* side, const char* trans, magma_tally2_int_t *m, magma_tally2_int_t *n, magma_tally2_int_t *k,
    float *A, magma_tally2_int_t *lda,
    float *tau,
    float *C, magma_tally2_int_t *ldc,
    float *work, magma_tally2_int_t *lwork,
    magma_tally2_int_t *info )
{
    magma_tally2_sormlq(
        magma_tally2_side_const(*side), magma_tally2_trans_const(*trans), *m, *n, *k,
        A, *lda,
        tau,
        C, *ldc,
        work, *lwork,
        info );
}

#define magma_tally2f_sormql FORTRAN_NAME( magma_tally2f_sormql, MAGMA_tally2F_SORMQL )
void magma_tally2f_sormql(
    const char* side, const char* trans, magma_tally2_int_t *m, magma_tally2_int_t *n, magma_tally2_int_t *k,
    float *A, magma_tally2_int_t *lda,
    float *tau,
    float *C, magma_tally2_int_t *ldc,
    float *work, magma_tally2_int_t *lwork,
    magma_tally2_int_t *info )
{
    magma_tally2_sormql(
        magma_tally2_side_const(*side), magma_tally2_trans_const(*trans), *m, *n, *k,
        A, *lda,
        tau,
        C, *ldc,
        work, *lwork,
        info );
}

#define magma_tally2f_sormqr FORTRAN_NAME( magma_tally2f_sormqr, MAGMA_tally2F_SORMQR )
void magma_tally2f_sormqr(
    const char* side, const char* trans, magma_tally2_int_t *m, magma_tally2_int_t *n, magma_tally2_int_t *k,
    float *A, magma_tally2_int_t *lda,
    float *tau,
    float *C, magma_tally2_int_t *ldc,
    float *work, magma_tally2_int_t *lwork,
    magma_tally2_int_t *info )
{
    magma_tally2_sormqr(
        magma_tally2_side_const(*side), magma_tally2_trans_const(*trans), *m, *n, *k,
        A, *lda,
        tau,
        C, *ldc,
        work, *lwork,
        info );
}

#define magma_tally2f_sormtr FORTRAN_NAME( magma_tally2f_sormtr, MAGMA_tally2F_SORMTR )
void magma_tally2f_sormtr(
    const char* side, const char* uplo, const char* trans, magma_tally2_int_t *m, magma_tally2_int_t *n,
    float *A, magma_tally2_int_t *lda,
    float *tau,
    float *C, magma_tally2_int_t *ldc,
    float *work, magma_tally2_int_t *lwork,
    magma_tally2_int_t *info )
{
    magma_tally2_sormtr(
        magma_tally2_side_const(*side), magma_tally2_uplo_const(*uplo), magma_tally2_trans_const(*trans), *m, *n,
        A, *lda,
        tau,
        C, *ldc,
        work, *lwork,
        info );
}

#define magma_tally2f_sgeev_m FORTRAN_NAME( magma_tally2f_sgeev_m, MAGMA_tally2F_SGEEV_M )
void magma_tally2f_sgeev_m(
    const char* jobvl, const char* jobvr, magma_tally2_int_t *n,
    float *A, magma_tally2_int_t *lda,
    float *wr,
    float *wi,
    float *VL, magma_tally2_int_t *ldvl,
    float *VR, magma_tally2_int_t *ldvr,
    float *work, magma_tally2_int_t *lwork,
    magma_tally2_int_t *info )
{
    magma_tally2_sgeev_m(
        magma_tally2_vec_const(*jobvl), magma_tally2_vec_const(*jobvr), *n,
        A, *lda,
        wr,
        wi,
        VL, *ldvl,
        VR, *ldvr,
        work, *lwork,
        info );
}

#define magma_tally2f_sgehrd_m FORTRAN_NAME( magma_tally2f_sgehrd_m, MAGMA_tally2F_SGEHRD_M )
void magma_tally2f_sgehrd_m(
    magma_tally2_int_t *n, magma_tally2_int_t *ilo, magma_tally2_int_t *ihi,
    float *A, magma_tally2_int_t *lda,
    float *tau,
    float *work, magma_tally2_int_t *lwork,
    float *T,
    magma_tally2_int_t *info )
{
    magma_tally2_sgehrd_m(
        *n, *ilo, *ihi,
        A, *lda,
        tau,
        work, *lwork,
        T,
        info );
}

#define magma_tally2f_sgetrf_m FORTRAN_NAME( magma_tally2f_sgetrf_m, MAGMA_tally2F_SGETRF_M )
void magma_tally2f_sgetrf_m(
    magma_tally2_int_t *ngpu, magma_tally2_int_t *m, magma_tally2_int_t *n,
    float *A, magma_tally2_int_t *lda,
    magma_tally2_int_t *ipiv,
    magma_tally2_int_t *info )
{
    magma_tally2_sgetrf_m(
        *ngpu, *m, *n,
        A, *lda,
        ipiv,
        info );
}

#define magma_tally2f_ssyevd_m FORTRAN_NAME( magma_tally2f_ssyevd_m, MAGMA_tally2F_SSYEVD_M )
void magma_tally2f_ssyevd_m(
    magma_tally2_int_t *ngpu, const char* jobz, const char* uplo, magma_tally2_int_t *n,
    float *A, magma_tally2_int_t *lda,
    float *w,
    float *work, magma_tally2_int_t *lwork,
    magma_tally2_int_t *iwork, magma_tally2_int_t *liwork,
    magma_tally2_int_t *info )
{
    magma_tally2_ssyevd_m(
        *ngpu, magma_tally2_vec_const(*jobz), magma_tally2_uplo_const(*uplo), *n,
        A, *lda,
        w,
        work, *lwork,
        iwork, *liwork,
        info );
}

#define magma_tally2f_ssyevdx_2stage_m FORTRAN_NAME( magma_tally2f_ssyevdx_2stage_m, MAGMA_tally2F_SSYEVDX_2STAGE_M )
void magma_tally2f_ssyevdx_2stage_m(
    magma_tally2_int_t *ngpu, const char* jobz, const char* range, const char* uplo, magma_tally2_int_t *n,
    float *A, magma_tally2_int_t *lda, float *vl, float *vu, magma_tally2_int_t *il, magma_tally2_int_t *iu,
    magma_tally2_int_t *m,
    float *w,
    float *work, magma_tally2_int_t *lwork,
    magma_tally2_int_t *iwork, magma_tally2_int_t *liwork,
    magma_tally2_int_t *info )
{
    magma_tally2_ssyevdx_2stage_m(
        *ngpu, magma_tally2_vec_const(*jobz), magma_tally2_range_const(*range), magma_tally2_uplo_const(*uplo), *n,
        A, *lda, *vl, *vu, *il, *iu,
        m,
        w,
        work, *lwork,
        iwork, *liwork,
        info );
}

#define magma_tally2f_ssyevdx_m FORTRAN_NAME( magma_tally2f_ssyevdx_m, MAGMA_tally2F_SSYEVDX_M )
void magma_tally2f_ssyevdx_m(
    magma_tally2_int_t *ngpu, const char* jobz, const char* range, const char* uplo, magma_tally2_int_t *n,
    float *A, magma_tally2_int_t *lda, float *vl, float *vu, magma_tally2_int_t *il, magma_tally2_int_t *iu,
    magma_tally2_int_t *m,
    float *w,
    float *work, magma_tally2_int_t *lwork,
    magma_tally2_int_t *iwork, magma_tally2_int_t *liwork,
    magma_tally2_int_t *info )
{
    magma_tally2_ssyevdx_m(
        *ngpu, magma_tally2_vec_const(*jobz), magma_tally2_range_const(*range), magma_tally2_uplo_const(*uplo), *n,
        A, *lda, *vl, *vu, *il, *iu,
        m,
        w,
        work, *lwork,
        iwork, *liwork,
        info );
}

#define magma_tally2f_ssygst_m FORTRAN_NAME( magma_tally2f_ssygst_m, MAGMA_tally2F_SSYGST_M )
void magma_tally2f_ssygst_m(
    magma_tally2_int_t *ngpu, magma_tally2_int_t *itype, const char* uplo, magma_tally2_int_t *n,
    float *A, magma_tally2_int_t *lda,
    float *B, magma_tally2_int_t *ldb,
    magma_tally2_int_t *info )
{
    magma_tally2_ssygst_m(
        *ngpu, *itype, magma_tally2_uplo_const(*uplo), *n,
        A, *lda,
        B, *ldb,
        info );
}

#define magma_tally2f_ssygvd_m FORTRAN_NAME( magma_tally2f_ssygvd_m, MAGMA_tally2F_SSYGVD_M )
void magma_tally2f_ssygvd_m(
    magma_tally2_int_t *ngpu, magma_tally2_int_t *itype, const char* jobz, const char* uplo, magma_tally2_int_t *n,
    float *A, magma_tally2_int_t *lda,
    float *B, magma_tally2_int_t *ldb,
    float *w,
    float *work, magma_tally2_int_t *lwork,
    magma_tally2_int_t *iwork, magma_tally2_int_t *liwork,
    magma_tally2_int_t *info )
{
    magma_tally2_ssygvd_m(
        *ngpu, *itype, magma_tally2_vec_const(*jobz), magma_tally2_uplo_const(*uplo), *n,
        A, *lda,
        B, *ldb,
        w,
        work, *lwork,
        iwork, *liwork,
        info );
}

#define magma_tally2f_ssygvdx_2stage_m FORTRAN_NAME( magma_tally2f_ssygvdx_2stage_m, MAGMA_tally2F_SSYGVDX_2STAGE_M )
void magma_tally2f_ssygvdx_2stage_m(
    magma_tally2_int_t *ngpu, magma_tally2_int_t *itype, const char* jobz, const char* range, const char* uplo, magma_tally2_int_t *n,
    float *A, magma_tally2_int_t *lda,
    float *B, magma_tally2_int_t *ldb, float *vl, float *vu, magma_tally2_int_t *il, magma_tally2_int_t *iu,
    magma_tally2_int_t *m,
    float *w,
    float *work, magma_tally2_int_t *lwork,
    magma_tally2_int_t *iwork, magma_tally2_int_t *liwork,
    magma_tally2_int_t *info )
{
    magma_tally2_ssygvdx_2stage_m(
        *ngpu, *itype, magma_tally2_vec_const(*jobz), magma_tally2_range_const(*range), magma_tally2_uplo_const(*uplo), *n,
        A, *lda,
        B, *ldb, *vl, *vu, *il, *iu,
        m,
        w,
        work, *lwork,
        iwork, *liwork,
        info );
}

#define magma_tally2f_ssygvdx_m FORTRAN_NAME( magma_tally2f_ssygvdx_m, MAGMA_tally2F_SSYGVDX_M )
void magma_tally2f_ssygvdx_m(
    magma_tally2_int_t *ngpu, magma_tally2_int_t *itype, const char* jobz, const char* range, const char* uplo, magma_tally2_int_t *n,
    float *A, magma_tally2_int_t *lda,
    float *B, magma_tally2_int_t *ldb, float *vl, float *vu, magma_tally2_int_t *il, magma_tally2_int_t *iu,
    magma_tally2_int_t *m,
    float *w,
    float *work, magma_tally2_int_t *lwork,
    magma_tally2_int_t *iwork, magma_tally2_int_t *liwork,
    magma_tally2_int_t *info )
{
    magma_tally2_ssygvdx_m(
        *ngpu, *itype, magma_tally2_vec_const(*jobz), magma_tally2_range_const(*range), magma_tally2_uplo_const(*uplo), *n,
        A, *lda,
        B, *ldb, *vl, *vu, *il, *iu,
        m,
        w,
        work, *lwork,
        iwork, *liwork,
        info );
}

#define magma_tally2f_spotrf_m FORTRAN_NAME( magma_tally2f_spotrf_m, MAGMA_tally2F_SPOTRF_M )
void magma_tally2f_spotrf_m(
    magma_tally2_int_t *ngpu, const char* uplo, magma_tally2_int_t *n,
    float *A, magma_tally2_int_t *lda,
    magma_tally2_int_t *info )
{
    magma_tally2_spotrf_m(
        *ngpu, magma_tally2_uplo_const(*uplo), *n,
        A, *lda,
        info );
}

#define magma_tally2f_sstedx_m FORTRAN_NAME( magma_tally2f_sstedx_m, MAGMA_tally2F_SSTEDX_M )
void magma_tally2f_sstedx_m(
    magma_tally2_int_t *ngpu, const char* range, magma_tally2_int_t *n, float *vl, float *vu, magma_tally2_int_t *il, magma_tally2_int_t *iu,
    float *d,
    float *e,
    float *Z, magma_tally2_int_t *ldz,
    float *rwork, magma_tally2_int_t *lrwork,
    magma_tally2_int_t *iwork, magma_tally2_int_t *liwork,
    magma_tally2_int_t *info )
{
    magma_tally2_sstedx_m(
        *ngpu, magma_tally2_range_const(*range), *n, *vl, *vu, *il, *iu,
        d,
        e,
        Z, *ldz,
        rwork, *lrwork,
        iwork, *liwork,
        info );
}

#define magma_tally2f_strsm_m FORTRAN_NAME( magma_tally2f_strsm_m, MAGMA_tally2F_STRSM_M )
void magma_tally2f_strsm_m(
    magma_tally2_int_t *ngpu, const char* side, const char* uplo, const char* transa, const char* diag, magma_tally2_int_t *m, magma_tally2_int_t *n, float *alpha,
    float *A, magma_tally2_int_t *lda,
    float *B, magma_tally2_int_t *ldb )
{
    magma_tally2_strsm_m(
        *ngpu, magma_tally2_side_const(*side), magma_tally2_uplo_const(*uplo), magma_tally2_trans_const(*transa), magma_tally2_diag_const(*diag), *m, *n, *alpha,
        A, *lda,
        B, *ldb );
}

#define magma_tally2f_sorghr_m FORTRAN_NAME( magma_tally2f_sorghr_m, MAGMA_tally2F_SORGHR_M )
void magma_tally2f_sorghr_m(
    magma_tally2_int_t *n, magma_tally2_int_t *ilo, magma_tally2_int_t *ihi,
    float *A, magma_tally2_int_t *lda,
    float *tau,
    float *T, magma_tally2_int_t *nb,
    magma_tally2_int_t *info )
{
    magma_tally2_sorghr_m(
        *n, *ilo, *ihi,
        A, *lda,
        tau,
        T, *nb,
        info );
}

#define magma_tally2f_sorgqr_m FORTRAN_NAME( magma_tally2f_sorgqr_m, MAGMA_tally2F_SORGQR_M )
void magma_tally2f_sorgqr_m(
    magma_tally2_int_t *m, magma_tally2_int_t *n, magma_tally2_int_t *k,
    float *A, magma_tally2_int_t *lda,
    float *tau,
    float *T, magma_tally2_int_t *nb,
    magma_tally2_int_t *info )
{
    magma_tally2_sorgqr_m(
        *m, *n, *k,
        A, *lda,
        tau,
        T, *nb,
        info );
}

#define magma_tally2f_sormqr_m FORTRAN_NAME( magma_tally2f_sormqr_m, MAGMA_tally2F_SORMQR_M )
void magma_tally2f_sormqr_m(
    magma_tally2_int_t *ngpu, const char* side, const char* trans, magma_tally2_int_t *m, magma_tally2_int_t *n, magma_tally2_int_t *k,
    float *A, magma_tally2_int_t *lda,
    float *tau,
    float *C, magma_tally2_int_t *ldc,
    float *work, magma_tally2_int_t *lwork,
    magma_tally2_int_t *info )
{
    magma_tally2_sormqr_m(
        *ngpu, magma_tally2_side_const(*side), magma_tally2_trans_const(*trans), *m, *n, *k,
        A, *lda,
        tau,
        C, *ldc,
        work, *lwork,
        info );
}

#define magma_tally2f_sormtr_m FORTRAN_NAME( magma_tally2f_sormtr_m, MAGMA_tally2F_SORMTR_M )
void magma_tally2f_sormtr_m(
    magma_tally2_int_t *ngpu, const char* side, const char* uplo, const char* trans, magma_tally2_int_t *m, magma_tally2_int_t *n,
    float *A, magma_tally2_int_t *lda,
    float *tau,
    float *C, magma_tally2_int_t *ldc,
    float *work, magma_tally2_int_t *lwork,
    magma_tally2_int_t *info )
{
    magma_tally2_sormtr_m(
        *ngpu, magma_tally2_side_const(*side), magma_tally2_uplo_const(*uplo), magma_tally2_trans_const(*trans), *m, *n,
        A, *lda,
        tau,
        C, *ldc,
        work, *lwork,
        info );
}

#define magma_tally2f_sgegqr_gpu FORTRAN_NAME( magma_tally2f_sgegqr_gpu, MAGMA_tally2F_SGEGQR_GPU )
void magma_tally2f_sgegqr_gpu(
    magma_tally2_int_t *ikind, magma_tally2_int_t *m, magma_tally2_int_t *n,
    devptr_t *dA, magma_tally2_int_t *ldda,
    devptr_t *dwork,
    float *work,
    magma_tally2_int_t *info )
{
    magma_tally2_sgegqr_gpu(
        *ikind, *m, *n,
        magma_tally2_sdevptr(dA), *ldda,
        magma_tally2_sdevptr(dwork),
        work,
        info );
}

#define magma_tally2f_sgelqf_gpu FORTRAN_NAME( magma_tally2f_sgelqf_gpu, MAGMA_tally2F_SGELQF_GPU )
void magma_tally2f_sgelqf_gpu(
    magma_tally2_int_t *m, magma_tally2_int_t *n,
    devptr_t *dA, magma_tally2_int_t *ldda,
    float *tau,
    float *work, magma_tally2_int_t *lwork,
    magma_tally2_int_t *info )
{
    magma_tally2_sgelqf_gpu(
        *m, *n,
        magma_tally2_sdevptr(dA), *ldda,
        tau,
        work, *lwork,
        info );
}

#define magma_tally2f_sgels_gpu FORTRAN_NAME( magma_tally2f_sgels_gpu, MAGMA_tally2F_SGELS_GPU )
void magma_tally2f_sgels_gpu(
    const char* trans, magma_tally2_int_t *m, magma_tally2_int_t *n, magma_tally2_int_t *nrhs,
    devptr_t *dA, magma_tally2_int_t *ldda,
    devptr_t *dB, magma_tally2_int_t *lddb,
    float *hwork, magma_tally2_int_t *lwork,
    magma_tally2_int_t *info )
{
    magma_tally2_sgels_gpu(
        magma_tally2_trans_const(*trans), *m, *n, *nrhs,
        magma_tally2_sdevptr(dA), *ldda,
        magma_tally2_sdevptr(dB), *lddb,
        hwork, *lwork,
        info );
}

#define magma_tally2f_sgels3_gpu FORTRAN_NAME( magma_tally2f_sgels3_gpu, MAGMA_tally2F_SGELS3_GPU )
void magma_tally2f_sgels3_gpu(
    const char* trans, magma_tally2_int_t *m, magma_tally2_int_t *n, magma_tally2_int_t *nrhs,
    devptr_t *dA, magma_tally2_int_t *ldda,
    devptr_t *dB, magma_tally2_int_t *lddb,
    float *hwork, magma_tally2_int_t *lwork,
    magma_tally2_int_t *info )
{
    magma_tally2_sgels3_gpu(
        magma_tally2_trans_const(*trans), *m, *n, *nrhs,
        magma_tally2_sdevptr(dA), *ldda,
        magma_tally2_sdevptr(dB), *lddb,
        hwork, *lwork,
        info );
}

#define magma_tally2f_sgeqp3_gpu FORTRAN_NAME( magma_tally2f_sgeqp3_gpu, MAGMA_tally2F_SGEQP3_GPU )
void magma_tally2f_sgeqp3_gpu(
    magma_tally2_int_t *m, magma_tally2_int_t *n,
    devptr_t *dA, magma_tally2_int_t *ldda,
    magma_tally2_int_t *jpvt,
    float *tau,
    devptr_t *dwork, magma_tally2_int_t *lwork,
    magma_tally2_int_t *info )
{
    magma_tally2_sgeqp3_gpu(
        *m, *n,
        magma_tally2_sdevptr(dA), *ldda,
        jpvt,
        tau,
        magma_tally2_sdevptr(dwork), *lwork,
        info );
}

#define magma_tally2f_sgeqr2x_gpu FORTRAN_NAME( magma_tally2f_sgeqr2x_gpu, MAGMA_tally2F_SGEQR2X_GPU )
void magma_tally2f_sgeqr2x_gpu(
    magma_tally2_int_t *m, magma_tally2_int_t *n,
    devptr_t *dA, magma_tally2_int_t *ldda,
    devptr_t *dtau,
    devptr_t *dT,
    devptr_t *ddA,
    devptr_t *dwork,
    magma_tally2_int_t *info )
{
    magma_tally2_sgeqr2x_gpu(
        *m, *n,
        magma_tally2_sdevptr(dA), *ldda,
        magma_tally2_sdevptr(dtau),
        magma_tally2_sdevptr(dT),
        magma_tally2_sdevptr(ddA),
        magma_tally2_sdevptr(dwork),
        info );
}

#define magma_tally2f_sgeqr2x2_gpu FORTRAN_NAME( magma_tally2f_sgeqr2x2_gpu, MAGMA_tally2F_SGEQR2X2_GPU )
void magma_tally2f_sgeqr2x2_gpu(
    magma_tally2_int_t *m, magma_tally2_int_t *n,
    devptr_t *dA, magma_tally2_int_t *ldda,
    devptr_t *dtau,
    devptr_t *dT,
    devptr_t *ddA,
    devptr_t *dwork,
    magma_tally2_int_t *info )
{
    magma_tally2_sgeqr2x2_gpu(
        *m, *n,
        magma_tally2_sdevptr(dA), *ldda,
        magma_tally2_sdevptr(dtau),
        magma_tally2_sdevptr(dT),
        magma_tally2_sdevptr(ddA),
        magma_tally2_sdevptr(dwork),
        info );
}

#define magma_tally2f_sgeqr2x3_gpu FORTRAN_NAME( magma_tally2f_sgeqr2x3_gpu, MAGMA_tally2F_SGEQR2X3_GPU )
void magma_tally2f_sgeqr2x3_gpu(
    magma_tally2_int_t *m, magma_tally2_int_t *n,
    devptr_t *dA, magma_tally2_int_t *ldda,
    devptr_t *dtau,
    devptr_t *dT,
    devptr_t *ddA,
    devptr_t *dwork,
    magma_tally2_int_t *info )
{
    magma_tally2_sgeqr2x3_gpu(
        *m, *n,
        magma_tally2_sdevptr(dA), *ldda,
        magma_tally2_sdevptr(dtau),
        magma_tally2_sdevptr(dT),
        magma_tally2_sdevptr(ddA),
        magma_tally2_sdevptr(dwork),
        info );
}

#define magma_tally2f_sgeqr2x4_gpu FORTRAN_NAME( magma_tally2f_sgeqr2x4_gpu, MAGMA_tally2F_SGEQR2X4_GPU )
void magma_tally2f_sgeqr2x4_gpu(
    magma_tally2_int_t *m, magma_tally2_int_t *n,
    devptr_t *dA, magma_tally2_int_t *ldda,
    devptr_t *dtau,
    devptr_t *dT,
    devptr_t *ddA,
    devptr_t *dwork, magma_tally2_queue_t *queue,
    magma_tally2_int_t *info )
{
    magma_tally2_sgeqr2x4_gpu(
        *m, *n,
        magma_tally2_sdevptr(dA), *ldda,
        magma_tally2_sdevptr(dtau),
        magma_tally2_sdevptr(dT),
        magma_tally2_sdevptr(ddA),
        magma_tally2_sdevptr(dwork), *queue,
        info );
}

#define magma_tally2f_sgeqrf_gpu FORTRAN_NAME( magma_tally2f_sgeqrf_gpu, MAGMA_tally2F_SGEQRF_GPU )
void magma_tally2f_sgeqrf_gpu(
    magma_tally2_int_t *m, magma_tally2_int_t *n,
    devptr_t *dA, magma_tally2_int_t *ldda,
    float *tau,
    devptr_t *dT,
    magma_tally2_int_t *info )
{
    magma_tally2_sgeqrf_gpu(
        *m, *n,
        magma_tally2_sdevptr(dA), *ldda,
        tau,
        magma_tally2_sdevptr(dT),
        info );
}

#define magma_tally2f_sgeqrf2_gpu FORTRAN_NAME( magma_tally2f_sgeqrf2_gpu, MAGMA_tally2F_SGEQRF2_GPU )
void magma_tally2f_sgeqrf2_gpu(
    magma_tally2_int_t *m, magma_tally2_int_t *n,
    devptr_t *dA, magma_tally2_int_t *ldda,
    float *tau,
    magma_tally2_int_t *info )
{
    magma_tally2_sgeqrf2_gpu(
        *m, *n,
        magma_tally2_sdevptr(dA), *ldda,
        tau,
        info );
}

#define magma_tally2f_sgeqrf3_gpu FORTRAN_NAME( magma_tally2f_sgeqrf3_gpu, MAGMA_tally2F_SGEQRF3_GPU )
void magma_tally2f_sgeqrf3_gpu(
    magma_tally2_int_t *m, magma_tally2_int_t *n,
    devptr_t *dA, magma_tally2_int_t *ldda,
    float *tau,
    devptr_t *dT,
    magma_tally2_int_t *info )
{
    magma_tally2_sgeqrf3_gpu(
        *m, *n,
        magma_tally2_sdevptr(dA), *ldda,
        tau,
        magma_tally2_sdevptr(dT),
        info );
}

#define magma_tally2f_sgeqrs_gpu FORTRAN_NAME( magma_tally2f_sgeqrs_gpu, MAGMA_tally2F_SGEQRS_GPU )
void magma_tally2f_sgeqrs_gpu(
    magma_tally2_int_t *m, magma_tally2_int_t *n, magma_tally2_int_t *nrhs,
    devptr_t *dA, magma_tally2_int_t *ldda,
    float *tau,
    devptr_t *dT,
    devptr_t *dB, magma_tally2_int_t *lddb,
    float *hwork, magma_tally2_int_t *lwork,
    magma_tally2_int_t *info )
{
    magma_tally2_sgeqrs_gpu(
        *m, *n, *nrhs,
        magma_tally2_sdevptr(dA), *ldda,
        tau,
        magma_tally2_sdevptr(dT),
        magma_tally2_sdevptr(dB), *lddb,
        hwork, *lwork,
        info );
}

#define magma_tally2f_sgeqrs3_gpu FORTRAN_NAME( magma_tally2f_sgeqrs3_gpu, MAGMA_tally2F_SGEQRS3_GPU )
void magma_tally2f_sgeqrs3_gpu(
    magma_tally2_int_t *m, magma_tally2_int_t *n, magma_tally2_int_t *nrhs,
    devptr_t *dA, magma_tally2_int_t *ldda,
    float *tau,
    devptr_t *dT,
    devptr_t *dB, magma_tally2_int_t *lddb,
    float *hwork, magma_tally2_int_t *lwork,
    magma_tally2_int_t *info )
{
    magma_tally2_sgeqrs3_gpu(
        *m, *n, *nrhs,
        magma_tally2_sdevptr(dA), *ldda,
        tau,
        magma_tally2_sdevptr(dT),
        magma_tally2_sdevptr(dB), *lddb,
        hwork, *lwork,
        info );
}

#define magma_tally2f_sgerbt_gpu FORTRAN_NAME( magma_tally2f_sgerbt_gpu, MAGMA_tally2F_SGERBT_GPU )
void magma_tally2f_sgerbt_gpu(
    const char* gen, magma_tally2_int_t *n, magma_tally2_int_t *nrhs,
    devptr_t *dA, magma_tally2_int_t *ldda,
    devptr_t *dB, magma_tally2_int_t *lddb,
    float *U,
    float *V,
    magma_tally2_int_t *info )
{
    magma_tally2_sgerbt_gpu(
        magma_tally2_bool_const(*gen), *n, *nrhs,
        magma_tally2_sdevptr(dA), *ldda,
        magma_tally2_sdevptr(dB), *lddb,
        U,
        V,
        info );
}

#define magma_tally2f_sgessm_gpu FORTRAN_NAME( magma_tally2f_sgessm_gpu, MAGMA_tally2F_SGESSM_GPU )
void magma_tally2f_sgessm_gpu(
    const char* order, magma_tally2_int_t *m, magma_tally2_int_t *n, magma_tally2_int_t *k, magma_tally2_int_t *ib,
    magma_tally2_int_t *ipiv,
    devptr_t *dL1, magma_tally2_int_t *lddl1,
    devptr_t *dL, magma_tally2_int_t *lddl,
    devptr_t *dA, magma_tally2_int_t *ldda,
    magma_tally2_int_t *info )
{
    magma_tally2_sgessm_gpu(
        magma_tally2_order_const(*order), *m, *n, *k, *ib,
        ipiv,
        magma_tally2_sdevptr(dL1), *lddl1,
        magma_tally2_sdevptr(dL), *lddl,
        magma_tally2_sdevptr(dA), *ldda,
        info );
}

#define magma_tally2f_sgesv_gpu FORTRAN_NAME( magma_tally2f_sgesv_gpu, MAGMA_tally2F_SGESV_GPU )
void magma_tally2f_sgesv_gpu(
    magma_tally2_int_t *n, magma_tally2_int_t *nrhs,
    devptr_t *dA, magma_tally2_int_t *ldda,
    magma_tally2_int_t *ipiv,
    devptr_t *dB, magma_tally2_int_t *lddb,
    magma_tally2_int_t *info )
{
    magma_tally2_sgesv_gpu(
        *n, *nrhs,
        magma_tally2_sdevptr(dA), *ldda,
        ipiv,
        magma_tally2_sdevptr(dB), *lddb,
        info );
}

#define magma_tally2f_sgesv_nopiv_gpu FORTRAN_NAME( magma_tally2f_sgesv_nopiv_gpu, MAGMA_tally2F_SGESV_NOPIV_GPU )
void magma_tally2f_sgesv_nopiv_gpu(
    magma_tally2_int_t *n, magma_tally2_int_t *nrhs,
    devptr_t *dA, magma_tally2_int_t *ldda,
    devptr_t *dB, magma_tally2_int_t *lddb,
    magma_tally2_int_t *info )
{
    magma_tally2_sgesv_nopiv_gpu(
        *n, *nrhs,
        magma_tally2_sdevptr(dA), *ldda,
        magma_tally2_sdevptr(dB), *lddb,
        info );
}

#define magma_tally2f_sgetf2_gpu FORTRAN_NAME( magma_tally2f_sgetf2_gpu, MAGMA_tally2F_SGETF2_GPU )
void magma_tally2f_sgetf2_gpu(
    magma_tally2_int_t *m, magma_tally2_int_t *n,
    devptr_t *dA, magma_tally2_int_t *ldda,
    magma_tally2_int_t *ipiv,
    magma_tally2_int_t *info )
{
    magma_tally2_sgetf2_gpu(
        *m, *n,
        magma_tally2_sdevptr(dA), *ldda,
        ipiv,
        info );
}

#define magma_tally2f_sgetrf_gpu FORTRAN_NAME( magma_tally2f_sgetrf_gpu, MAGMA_tally2F_SGETRF_GPU )
void magma_tally2f_sgetrf_gpu(
    magma_tally2_int_t *m, magma_tally2_int_t *n,
    devptr_t *dA, magma_tally2_int_t *ldda,
    magma_tally2_int_t *ipiv,
    magma_tally2_int_t *info )
{
    magma_tally2_sgetrf_gpu(
        *m, *n,
        magma_tally2_sdevptr(dA), *ldda,
        ipiv,
        info );
}

#define magma_tally2f_sgetrf_nopiv_gpu FORTRAN_NAME( magma_tally2f_sgetrf_nopiv_gpu, MAGMA_tally2F_SGETRF_NOPIV_GPU )
void magma_tally2f_sgetrf_nopiv_gpu(
    magma_tally2_int_t *m, magma_tally2_int_t *n,
    devptr_t *dA, magma_tally2_int_t *ldda,
    magma_tally2_int_t *info )
{
    magma_tally2_sgetrf_nopiv_gpu(
        *m, *n,
        magma_tally2_sdevptr(dA), *ldda,
        info );
}

#define magma_tally2f_sgetri_gpu FORTRAN_NAME( magma_tally2f_sgetri_gpu, MAGMA_tally2F_SGETRI_GPU )
void magma_tally2f_sgetri_gpu(
    magma_tally2_int_t *n,
    devptr_t *dA, magma_tally2_int_t *ldda,
    magma_tally2_int_t *ipiv,
    devptr_t *dwork, magma_tally2_int_t *lwork,
    magma_tally2_int_t *info )
{
    magma_tally2_sgetri_gpu(
        *n,
        magma_tally2_sdevptr(dA), *ldda,
        ipiv,
        magma_tally2_sdevptr(dwork), *lwork,
        info );
}

#define magma_tally2f_sgetrs_gpu FORTRAN_NAME( magma_tally2f_sgetrs_gpu, MAGMA_tally2F_SGETRS_GPU )
void magma_tally2f_sgetrs_gpu(
    const char* trans, magma_tally2_int_t *n, magma_tally2_int_t *nrhs,
    devptr_t *dA, magma_tally2_int_t *ldda,
    magma_tally2_int_t *ipiv,
    devptr_t *dB, magma_tally2_int_t *lddb,
    magma_tally2_int_t *info )
{
    magma_tally2_sgetrs_gpu(
        magma_tally2_trans_const(*trans), *n, *nrhs,
        magma_tally2_sdevptr(dA), *ldda,
        ipiv,
        magma_tally2_sdevptr(dB), *lddb,
        info );
}

#define magma_tally2f_sgetrs_nopiv_gpu FORTRAN_NAME( magma_tally2f_sgetrs_nopiv_gpu, MAGMA_tally2F_SGETRS_NOPIV_GPU )
void magma_tally2f_sgetrs_nopiv_gpu(
    const char* trans, magma_tally2_int_t *n, magma_tally2_int_t *nrhs,
    devptr_t *dA, magma_tally2_int_t *ldda,
    devptr_t *dB, magma_tally2_int_t *lddb,
    magma_tally2_int_t *info )
{
    magma_tally2_sgetrs_nopiv_gpu(
        magma_tally2_trans_const(*trans), *n, *nrhs,
        magma_tally2_sdevptr(dA), *ldda,
        magma_tally2_sdevptr(dB), *lddb,
        info );
}

#define magma_tally2f_ssyevd_gpu FORTRAN_NAME( magma_tally2f_ssyevd_gpu, MAGMA_tally2F_SSYEVD_GPU )
void magma_tally2f_ssyevd_gpu(
    const char* jobz, const char* uplo, magma_tally2_int_t *n,
    devptr_t *dA, magma_tally2_int_t *ldda,
    float *w,
    float *wA, magma_tally2_int_t *ldwa,
    float *work, magma_tally2_int_t *lwork,
    magma_tally2_int_t *iwork, magma_tally2_int_t *liwork,
    magma_tally2_int_t *info )
{
    magma_tally2_ssyevd_gpu(
        magma_tally2_vec_const(*jobz), magma_tally2_uplo_const(*uplo), *n,
        magma_tally2_sdevptr(dA), *ldda,
        w,
        wA, *ldwa,
        work, *lwork,
        iwork, *liwork,
        info );
}

#define magma_tally2f_ssyevdx_gpu FORTRAN_NAME( magma_tally2f_ssyevdx_gpu, MAGMA_tally2F_SSYEVDX_GPU )
void magma_tally2f_ssyevdx_gpu(
    const char* jobz, const char* range, const char* uplo, magma_tally2_int_t *n,
    devptr_t *dA, magma_tally2_int_t *ldda, float *vl, float *vu, magma_tally2_int_t *il, magma_tally2_int_t *iu,
    magma_tally2_int_t *m,
    float *w,
    float *wA, magma_tally2_int_t *ldwa,
    float *work, magma_tally2_int_t *lwork,
    magma_tally2_int_t *iwork, magma_tally2_int_t *liwork,
    magma_tally2_int_t *info )
{
    magma_tally2_ssyevdx_gpu(
        magma_tally2_vec_const(*jobz), magma_tally2_range_const(*range), magma_tally2_uplo_const(*uplo), *n,
        magma_tally2_sdevptr(dA), *ldda, *vl, *vu, *il, *iu,
        m,
        w,
        wA, *ldwa,
        work, *lwork,
        iwork, *liwork,
        info );
}

#define magma_tally2f_ssygst_gpu FORTRAN_NAME( magma_tally2f_ssygst_gpu, MAGMA_tally2F_SSYGST_GPU )
void magma_tally2f_ssygst_gpu(
    magma_tally2_int_t *itype, const char* uplo, magma_tally2_int_t *n,
    devptr_t *dA, magma_tally2_int_t *ldda,
    devptr_t *dB, magma_tally2_int_t *lddb,
    magma_tally2_int_t *info )
{
    magma_tally2_ssygst_gpu(
        *itype, magma_tally2_uplo_const(*uplo), *n,
        magma_tally2_sdevptr(dA), *ldda,
        magma_tally2_sdevptr(dB), *lddb,
        info );
}

#define magma_tally2f_ssytrd_gpu FORTRAN_NAME( magma_tally2f_ssytrd_gpu, MAGMA_tally2F_SSYTRD_GPU )
void magma_tally2f_ssytrd_gpu(
    const char* uplo, magma_tally2_int_t *n,
    devptr_t *dA, magma_tally2_int_t *ldda,
    float *d,
    float *e,
    float *tau,
    float *wA, magma_tally2_int_t *ldwa,
    float *work, magma_tally2_int_t *lwork,
    magma_tally2_int_t *info )
{
    magma_tally2_ssytrd_gpu(
        magma_tally2_uplo_const(*uplo), *n,
        magma_tally2_sdevptr(dA), *ldda,
        d,
        e,
        tau,
        wA, *ldwa,
        work, *lwork,
        info );
}

#define magma_tally2f_ssytrd2_gpu FORTRAN_NAME( magma_tally2f_ssytrd2_gpu, MAGMA_tally2F_SSYTRD2_GPU )
void magma_tally2f_ssytrd2_gpu(
    const char* uplo, magma_tally2_int_t *n,
    devptr_t *dA, magma_tally2_int_t *ldda,
    float *d,
    float *e,
    float *tau,
    float *wA, magma_tally2_int_t *ldwa,
    float *work, magma_tally2_int_t *lwork,
    devptr_t *dwork, magma_tally2_int_t *ldwork,
    magma_tally2_int_t *info )
{
    magma_tally2_ssytrd2_gpu(
        magma_tally2_uplo_const(*uplo), *n,
        magma_tally2_sdevptr(dA), *ldda,
        d,
        e,
        tau,
        wA, *ldwa,
        work, *lwork,
        magma_tally2_sdevptr(dwork), *ldwork,
        info );
}

#define magma_tally2f_ssytrf_nopiv_tally2_gpu FORTRAN_NAME( magma_tally2f_ssytrf_nopiv_tally2_gpu, MAGMA_tally2F_SSYTRF_NOPIV_GPU )
void magma_tally2f_ssytrf_nopiv_tally2_gpu(
    const char* uplo, magma_tally2_int_t *n,
    devptr_t *da, magma_tally2_int_t *ldda,
    magma_tally2_int_t *info )
{
    magma_tally2_ssytrf_nopiv_tally2_gpu(
        magma_tally2_uplo_const(*uplo), *n,
        magma_tally2_sdevptr(da), *ldda,
        info );
}

#define magma_tally2f_slarf_gpu FORTRAN_NAME( magma_tally2f_slarf_gpu, MAGMA_tally2F_SLARF_GPU )
void magma_tally2f_slarf_gpu(
    magma_tally2_int_t *m, magma_tally2_int_t *n,
    devptr_t *dv,
    devptr_t *dtau,
    devptr_t *dC, magma_tally2_int_t *lddc )
{
    magma_tally2_slarf_gpu(
        *m, *n,
        magma_tally2_sdevptr(dv),
        magma_tally2_sdevptr(dtau),
        magma_tally2_sdevptr(dC), *lddc );
}

#define magma_tally2f_slarfb_gpu FORTRAN_NAME( magma_tally2f_slarfb_gpu, MAGMA_tally2F_SLARFB_GPU )
void magma_tally2f_slarfb_gpu(
    const char* side, const char* trans, const char* direct, const char* storev, magma_tally2_int_t *m, magma_tally2_int_t *n, magma_tally2_int_t *k,
    devptr_t *dV, magma_tally2_int_t *lddv,
    devptr_t *dT, magma_tally2_int_t *lddt,
    devptr_t *dC, magma_tally2_int_t *lddc,
    devptr_t *dwork, magma_tally2_int_t *ldwork )
{
    magma_tally2_slarfb_gpu(
        magma_tally2_side_const(*side), magma_tally2_trans_const(*trans), magma_tally2_direct_const(*direct), magma_tally2_storev_const(*storev), *m, *n, *k,
        magma_tally2_sdevptr(dV), *lddv,
        magma_tally2_sdevptr(dT), *lddt,
        magma_tally2_sdevptr(dC), *lddc,
        magma_tally2_sdevptr(dwork), *ldwork );
}

#define magma_tally2f_slarfb_gpu_gemm FORTRAN_NAME( magma_tally2f_slarfb_gpu_gemm, MAGMA_tally2F_SLARFB_GPU_GEMM )
void magma_tally2f_slarfb_gpu_gemm(
    const char* side, const char* trans, const char* direct, const char* storev, magma_tally2_int_t *m, magma_tally2_int_t *n, magma_tally2_int_t *k,
    devptr_t *dV, magma_tally2_int_t *lddv,
    devptr_t *dT, magma_tally2_int_t *lddt,
    devptr_t *dC, magma_tally2_int_t *lddc,
    devptr_t *dwork, magma_tally2_int_t *ldwork,
    devptr_t *dworkvt, magma_tally2_int_t *ldworkvt )
{
    magma_tally2_slarfb_gpu_gemm(
        magma_tally2_side_const(*side), magma_tally2_trans_const(*trans), magma_tally2_direct_const(*direct), magma_tally2_storev_const(*storev), *m, *n, *k,
        magma_tally2_sdevptr(dV), *lddv,
        magma_tally2_sdevptr(dT), *lddt,
        magma_tally2_sdevptr(dC), *lddc,
        magma_tally2_sdevptr(dwork), *ldwork,
        magma_tally2_sdevptr(dworkvt), *ldworkvt );
}

#define magma_tally2f_slarfb2_gpu FORTRAN_NAME( magma_tally2f_slarfb2_gpu, MAGMA_tally2F_SLARFB2_GPU )
void magma_tally2f_slarfb2_gpu(
    magma_tally2_int_t *m, magma_tally2_int_t *n, magma_tally2_int_t *k,
    devptr_t *dV, magma_tally2_int_t *lddv,
    devptr_t *dT, magma_tally2_int_t *lddt,
    devptr_t *dC, magma_tally2_int_t *lddc,
    devptr_t *dwork, magma_tally2_int_t *ldwork )
{
    magma_tally2_slarfb2_gpu(
        *m, *n, *k,
        magma_tally2_sdevptr(dV), *lddv,
        magma_tally2_sdevptr(dT), *lddt,
        magma_tally2_sdevptr(dC), *lddc,
        magma_tally2_sdevptr(dwork), *ldwork );
}

#define magma_tally2f_slauum_gpu FORTRAN_NAME( magma_tally2f_slauum_gpu, MAGMA_tally2F_SLAUUM_GPU )
void magma_tally2f_slauum_gpu(
    const char* uplo, magma_tally2_int_t *n,
    devptr_t *dA, magma_tally2_int_t *ldda,
    magma_tally2_int_t *info )
{
    magma_tally2_slauum_gpu(
        magma_tally2_uplo_const(*uplo), *n,
        magma_tally2_sdevptr(dA), *ldda,
        info );
}

#define magma_tally2f_sposv_gpu FORTRAN_NAME( magma_tally2f_sposv_gpu, MAGMA_tally2F_SPOSV_GPU )
void magma_tally2f_sposv_gpu(
    const char* uplo, magma_tally2_int_t *n, magma_tally2_int_t *nrhs,
    devptr_t *dA, magma_tally2_int_t *ldda,
    devptr_t *dB, magma_tally2_int_t *lddb,
    magma_tally2_int_t *info )
{
    magma_tally2_sposv_gpu(
        magma_tally2_uplo_const(*uplo), *n, *nrhs,
        magma_tally2_sdevptr(dA), *ldda,
        magma_tally2_sdevptr(dB), *lddb,
        info );
}

#define magma_tally2f_spotf2_gpu FORTRAN_NAME( magma_tally2f_spotf2_gpu, MAGMA_tally2F_SPOTF2_GPU )
void magma_tally2f_spotf2_gpu(
    const char* uplo, magma_tally2_int_t *n,
    devptr_t *dA, magma_tally2_int_t *ldda,
    magma_tally2_int_t *info )
{
    magma_tally2_spotf2_gpu(
        magma_tally2_uplo_const(*uplo), *n,
        magma_tally2_sdevptr(dA), *ldda,
        info );
}

#define magma_tally2f_spotrf_gpu FORTRAN_NAME( magma_tally2f_spotrf_gpu, MAGMA_tally2F_SPOTRF_GPU )
void magma_tally2f_spotrf_gpu(
    const char* uplo, magma_tally2_int_t *n,
    devptr_t *dA, magma_tally2_int_t *ldda,
    magma_tally2_int_t *info )
{
    magma_tally2_spotrf_gpu(
        magma_tally2_uplo_const(*uplo), *n,
        magma_tally2_sdevptr(dA), *ldda,
        info );
}

#define magma_tally2f_spotri_gpu FORTRAN_NAME( magma_tally2f_spotri_gpu, MAGMA_tally2F_SPOTRI_GPU )
void magma_tally2f_spotri_gpu(
    const char* uplo, magma_tally2_int_t *n,
    devptr_t *dA, magma_tally2_int_t *ldda,
    magma_tally2_int_t *info )
{
    magma_tally2_spotri_gpu(
        magma_tally2_uplo_const(*uplo), *n,
        magma_tally2_sdevptr(dA), *ldda,
        info );
}

#define magma_tally2f_spotrs_gpu FORTRAN_NAME( magma_tally2f_spotrs_gpu, MAGMA_tally2F_SPOTRS_GPU )
void magma_tally2f_spotrs_gpu(
    const char* uplo, magma_tally2_int_t *n, magma_tally2_int_t *nrhs,
    devptr_t *dA, magma_tally2_int_t *ldda,
    devptr_t *dB, magma_tally2_int_t *lddb,
    magma_tally2_int_t *info )
{
    magma_tally2_spotrs_gpu(
        magma_tally2_uplo_const(*uplo), *n, *nrhs,
        magma_tally2_sdevptr(dA), *ldda,
        magma_tally2_sdevptr(dB), *lddb,
        info );
}

#define magma_tally2f_sssssm_gpu FORTRAN_NAME( magma_tally2f_sssssm_gpu, MAGMA_tally2F_SSSSSM_GPU )
void magma_tally2f_sssssm_gpu(
    const char* order, magma_tally2_int_t *m1, magma_tally2_int_t *n1, magma_tally2_int_t *m2, magma_tally2_int_t *n2, magma_tally2_int_t *k, magma_tally2_int_t *ib,
    devptr_t *dA1, magma_tally2_int_t *ldda1,
    devptr_t *dA2, magma_tally2_int_t *ldda2,
    devptr_t *dL1, magma_tally2_int_t *lddl1,
    devptr_t *dL2, magma_tally2_int_t *lddl2,
    magma_tally2_int_t *ipiv,
    magma_tally2_int_t *info )
{
    magma_tally2_sssssm_gpu(
        magma_tally2_order_const(*order), *m1, *n1, *m2, *n2, *k, *ib,
        magma_tally2_sdevptr(dA1), *ldda1,
        magma_tally2_sdevptr(dA2), *ldda2,
        magma_tally2_sdevptr(dL1), *lddl1,
        magma_tally2_sdevptr(dL2), *lddl2,
        ipiv,
        info );
}

#define magma_tally2f_strtri_gpu FORTRAN_NAME( magma_tally2f_strtri_gpu, MAGMA_tally2F_STRTRI_GPU )
void magma_tally2f_strtri_gpu(
    const char* uplo, const char* diag, magma_tally2_int_t *n,
    devptr_t *dA, magma_tally2_int_t *ldda,
    magma_tally2_int_t *info )
{
    magma_tally2_strtri_gpu(
        magma_tally2_uplo_const(*uplo), magma_tally2_diag_const(*diag), *n,
        magma_tally2_sdevptr(dA), *ldda,
        info );
}

#define magma_tally2f_sorgqr_gpu FORTRAN_NAME( magma_tally2f_sorgqr_gpu, MAGMA_tally2F_SORGQR_GPU )
void magma_tally2f_sorgqr_gpu(
    magma_tally2_int_t *m, magma_tally2_int_t *n, magma_tally2_int_t *k,
    devptr_t *dA, magma_tally2_int_t *ldda,
    float *tau,
    devptr_t *dT, magma_tally2_int_t *nb,
    magma_tally2_int_t *info )
{
    magma_tally2_sorgqr_gpu(
        *m, *n, *k,
        magma_tally2_sdevptr(dA), *ldda,
        tau,
        magma_tally2_sdevptr(dT), *nb,
        info );
}

#define magma_tally2f_sormql2_gpu FORTRAN_NAME( magma_tally2f_sormql2_gpu, MAGMA_tally2F_SORMQL2_GPU )
void magma_tally2f_sormql2_gpu(
    const char* side, const char* trans, magma_tally2_int_t *m, magma_tally2_int_t *n, magma_tally2_int_t *k,
    devptr_t *dA, magma_tally2_int_t *ldda,
    float *tau,
    devptr_t *dC, magma_tally2_int_t *lddc,
    float *wA, magma_tally2_int_t *ldwa,
    magma_tally2_int_t *info )
{
    magma_tally2_sormql2_gpu(
        magma_tally2_side_const(*side), magma_tally2_trans_const(*trans), *m, *n, *k,
        magma_tally2_sdevptr(dA), *ldda,
        tau,
        magma_tally2_sdevptr(dC), *lddc,
        wA, *ldwa,
        info );
}

#define magma_tally2f_sormqr_gpu FORTRAN_NAME( magma_tally2f_sormqr_gpu, MAGMA_tally2F_SORMQR_GPU )
void magma_tally2f_sormqr_gpu(
    const char* side, const char* trans, magma_tally2_int_t *m, magma_tally2_int_t *n, magma_tally2_int_t *k,
    devptr_t *dA, magma_tally2_int_t *ldda,
    float *tau,
    devptr_t *dC, magma_tally2_int_t *lddc,
    float *hwork, magma_tally2_int_t *lwork,
    devptr_t *dT, magma_tally2_int_t *nb,
    magma_tally2_int_t *info )
{
    magma_tally2_sormqr_gpu(
        magma_tally2_side_const(*side), magma_tally2_trans_const(*trans), *m, *n, *k,
        magma_tally2_sdevptr(dA), *ldda,
        tau,
        magma_tally2_sdevptr(dC), *lddc,
        hwork, *lwork,
        magma_tally2_sdevptr(dT), *nb,
        info );
}

#define magma_tally2f_sormqr2_gpu FORTRAN_NAME( magma_tally2f_sormqr2_gpu, MAGMA_tally2F_SORMQR2_GPU )
void magma_tally2f_sormqr2_gpu(
    const char* side, const char* trans, magma_tally2_int_t *m, magma_tally2_int_t *n, magma_tally2_int_t *k,
    devptr_t *dA, magma_tally2_int_t *ldda,
    float *tau,
    devptr_t *dC, magma_tally2_int_t *lddc,
    float *wA, magma_tally2_int_t *ldwa,
    magma_tally2_int_t *info )
{
    magma_tally2_sormqr2_gpu(
        magma_tally2_side_const(*side), magma_tally2_trans_const(*trans), *m, *n, *k,
        magma_tally2_sdevptr(dA), *ldda,
        tau,
        magma_tally2_sdevptr(dC), *lddc,
        wA, *ldwa,
        info );
}

#define magma_tally2f_sormtr_gpu FORTRAN_NAME( magma_tally2f_sormtr_gpu, MAGMA_tally2F_SORMTR_GPU )
void magma_tally2f_sormtr_gpu(
    const char* side, const char* uplo, const char* trans, magma_tally2_int_t *m, magma_tally2_int_t *n,
    devptr_t *dA, magma_tally2_int_t *ldda,
    float *tau,
    devptr_t *dC, magma_tally2_int_t *lddc,
    float *wA, magma_tally2_int_t *ldwa,
    magma_tally2_int_t *info )
{
    magma_tally2_sormtr_gpu(
        magma_tally2_side_const(*side), magma_tally2_uplo_const(*uplo), magma_tally2_trans_const(*trans), *m, *n,
        magma_tally2_sdevptr(dA), *ldda,
        tau,
        magma_tally2_sdevptr(dC), *lddc,
        wA, *ldwa,
        info );
}

#define magma_tally2f_snan_inf FORTRAN_NAME( magma_tally2f_snan_inf, MAGMA_tally2F_SNAN_INF )
void magma_tally2f_snan_inf(
    const char* uplo, magma_tally2_int_t *m, magma_tally2_int_t *n,
    const float *A, magma_tally2_int_t *lda,
    magma_tally2_int_t *cnt_nan,
    magma_tally2_int_t *cnt_inf )
{
    magma_tally2_snan_inf(
        magma_tally2_uplo_const(*uplo), *m, *n,
        A, *lda,
        cnt_nan,
        cnt_inf );
}

#define magma_tally2f_snan_inf_gpu FORTRAN_NAME( magma_tally2f_snan_inf_gpu, MAGMA_tally2F_SNAN_INF_GPU )
void magma_tally2f_snan_inf_gpu(
    const char* uplo, magma_tally2_int_t *m, magma_tally2_int_t *n,
    devptr_t *dA, magma_tally2_int_t *ldda,
    magma_tally2_int_t *cnt_nan,
    magma_tally2_int_t *cnt_inf )
{
    magma_tally2_snan_inf_gpu(
        magma_tally2_uplo_const(*uplo), *m, *n,
        magma_tally2_sdevptr(dA), *ldda,
        cnt_nan,
        cnt_inf );
}

#define magma_tally2f_sprint FORTRAN_NAME( magma_tally2f_sprint, MAGMA_tally2F_SPRINT )
void magma_tally2f_sprint(
    magma_tally2_int_t *m, magma_tally2_int_t *n,
    const float *A, magma_tally2_int_t *lda )
{
    magma_tally2_sprint(
        *m, *n,
        A, *lda );
}

#define magma_tally2f_sprint_gpu FORTRAN_NAME( magma_tally2f_sprint_gpu, MAGMA_tally2F_SPRINT_GPU )
void magma_tally2f_sprint_gpu(
    magma_tally2_int_t *m, magma_tally2_int_t *n,
    devptr_t *dA, magma_tally2_int_t *ldda )
{
    magma_tally2_sprint_gpu(
        *m, *n,
        magma_tally2_sdevptr(dA), *ldda );
}


#ifdef __cplusplus
}
#endif
