!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!  This file is AUTOMATICALLY GENERATED by:
!!  ../tools/fortran_wrappers.pl ../include/magma_tally3_z.i
!!  Do not edit.
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

module magma_tally3_zfortran

use magma_tally3_param

implicit none

!---- Fortran interfaces to MAGMA_tally3 subroutines ----
interface

integer function magma_tally3f_get_zpotrf_nb( m )
    integer :: m
end function magma_tally3f_get_zpotrf_nb

integer function magma_tally3f_get_zgetrf_nb( m )
    integer :: m
end function magma_tally3f_get_zgetrf_nb

integer function magma_tally3f_get_zgetri_nb( m )
    integer :: m
end function magma_tally3f_get_zgetri_nb

integer function magma_tally3f_get_zgeqp3_nb( m )
    integer :: m
end function magma_tally3f_get_zgeqp3_nb

integer function magma_tally3f_get_zgeqrf_nb( m )
    integer :: m
end function magma_tally3f_get_zgeqrf_nb

integer function magma_tally3f_get_zgeqlf_nb( m )
    integer :: m
end function magma_tally3f_get_zgeqlf_nb

integer function magma_tally3f_get_zgehrd_nb( m )
    integer :: m
end function magma_tally3f_get_zgehrd_nb

integer function magma_tally3f_get_zhetrd_nb( m )
    integer :: m
end function magma_tally3f_get_zhetrd_nb

integer function magma_tally3f_get_zhetrf_nb( m )
    integer :: m
end function magma_tally3f_get_zhetrf_nb

integer function magma_tally3f_get_zhetrf_nopiv_tally3_nb( m )
    integer :: m
end function magma_tally3f_get_zhetrf_nopiv_tally3_nb

integer function magma_tally3f_get_zgelqf_nb( m )
    integer :: m
end function magma_tally3f_get_zgelqf_nb

integer function magma_tally3f_get_zgebrd_nb( m )
    integer :: m
end function magma_tally3f_get_zgebrd_nb

integer function magma_tally3f_get_zhegst_nb( m )
    integer :: m
end function magma_tally3f_get_zhegst_nb

integer function magma_tally3f_get_zgesvd_nb( m )
    integer :: m
end function magma_tally3f_get_zgesvd_nb

integer function magma_tally3f_get_zhegst_nb_m( m )
    integer :: m
end function magma_tally3f_get_zhegst_nb_m

subroutine magma_tally3f_get_zbulge_nb( m, nbthreads )
    integer          :: m
    integer          :: nbthreads
end subroutine magma_tally3f_get_zbulge_nb

subroutine magma_tally3f_zbulge_get_Vblksiz( m, nb, nbthreads )
    integer          :: m
    integer          :: nb
    integer          :: nbthreads
end subroutine magma_tally3f_zbulge_get_Vblksiz

subroutine magma_tally3f_get_zbulge_gcperf(  )
end subroutine magma_tally3f_get_zbulge_gcperf

subroutine magma_tally3f_zgebrd( m, n, A, lda, d, e, tauq, taup, work, lwork, info )
    integer          :: m
    integer          :: n
    complex*16       :: A(*)
    integer          :: lda
    double precision :: d(*)
    double precision :: e(*)
    complex*16       :: tauq(*)
    complex*16       :: taup(*)
    complex*16       :: work(*)
    integer          :: lwork
    integer          :: info
end subroutine magma_tally3f_zgebrd

subroutine magma_tally3f_zgeev( jobvl, jobvr, n, A, lda, w, VL, ldvl, VR, ldvr, work, lwork,  &
        rwork, info )
    character        :: jobvl
    character        :: jobvr
    integer          :: n
    complex*16       :: A(*)
    integer          :: lda
    complex*16       :: w(*)
    complex*16       :: VL(*)
    integer          :: ldvl
    complex*16       :: VR(*)
    integer          :: ldvr
    complex*16       :: work(*)
    integer          :: lwork
    double precision :: rwork(*)
    integer          :: info
end subroutine magma_tally3f_zgeev

subroutine magma_tally3f_zgehrd( n, ilo, ihi, A, lda, tau, work, lwork, dT, info )
    integer          :: n
    integer          :: ilo
    integer          :: ihi
    complex*16       :: A(*)
    integer          :: lda
    complex*16       :: tau(*)
    complex*16       :: work(*)
    integer          :: lwork
    magma_tally3_devptr_t   :: dT
    integer          :: info
end subroutine magma_tally3f_zgehrd

subroutine magma_tally3f_zgehrd2( n, ilo, ihi, A, lda, tau, work, lwork, info )
    integer          :: n
    integer          :: ilo
    integer          :: ihi
    complex*16       :: A(*)
    integer          :: lda
    complex*16       :: tau(*)
    complex*16       :: work(*)
    integer          :: lwork
    integer          :: info
end subroutine magma_tally3f_zgehrd2

subroutine magma_tally3f_zgelqf( m, n, A, lda, tau, work, lwork, info )
    integer          :: m
    integer          :: n
    complex*16       :: A(*)
    integer          :: lda
    complex*16       :: tau(*)
    complex*16       :: work(*)
    integer          :: lwork
    integer          :: info
end subroutine magma_tally3f_zgelqf

subroutine magma_tally3f_zgeqlf( m, n, A, lda, tau, work, lwork, info )
    integer          :: m
    integer          :: n
    complex*16       :: A(*)
    integer          :: lda
    complex*16       :: tau(*)
    complex*16       :: work(*)
    integer          :: lwork
    integer          :: info
end subroutine magma_tally3f_zgeqlf

subroutine magma_tally3f_zgeqp3( m, n, A, lda, jpvt, tau, work, lwork, rwork, info )
    integer          :: m
    integer          :: n
    complex*16       :: A(*)
    integer          :: lda
    integer          :: jpvt(*)
    complex*16       :: tau(*)
    complex*16       :: work(*)
    integer          :: lwork
    double precision :: rwork(*)
    integer          :: info
end subroutine magma_tally3f_zgeqp3

subroutine magma_tally3f_zgeqrf( m, n, A, lda, tau, work, lwork, info )
    integer          :: m
    integer          :: n
    complex*16       :: A(*)
    integer          :: lda
    complex*16       :: tau(*)
    complex*16       :: work(*)
    integer          :: lwork
    integer          :: info
end subroutine magma_tally3f_zgeqrf

subroutine magma_tally3f_zgeqrf_ooc( m, n, A, lda, tau, work, lwork, info )
    integer          :: m
    integer          :: n
    complex*16       :: A(*)
    integer          :: lda
    complex*16       :: tau(*)
    complex*16       :: work(*)
    integer          :: lwork
    integer          :: info
end subroutine magma_tally3f_zgeqrf_ooc

subroutine magma_tally3f_zgeqrf4( ngpu, m, n, A, lda, tau, work, lwork, info )
    integer          :: ngpu
    integer          :: m
    integer          :: n
    complex*16       :: A(*)
    integer          :: lda
    complex*16       :: tau(*)
    complex*16       :: work(*)
    integer          :: lwork
    integer          :: info
end subroutine magma_tally3f_zgeqrf4

subroutine magma_tally3f_zgesdd( jobz, m, n, A, lda, s, U, ldu, VT, ldvt, work, lwork, rwork,  &
        iwork, info )
    character        :: jobz
    integer          :: m
    integer          :: n
    complex*16       :: A(*)
    integer          :: lda
    double precision :: s(*)
    complex*16       :: U(*)
    integer          :: ldu
    complex*16       :: VT(*)
    integer          :: ldvt
    complex*16       :: work(*)
    integer          :: lwork
    double precision :: rwork(*)
    integer          :: iwork(*)
    integer          :: info
end subroutine magma_tally3f_zgesdd

subroutine magma_tally3f_zgesv( n, nrhs, A, lda, ipiv, B, ldb, info )
    integer          :: n
    integer          :: nrhs
    complex*16       :: A(*)
    integer          :: lda
    integer          :: ipiv(*)
    complex*16       :: B(*)
    integer          :: ldb
    integer          :: info
end subroutine magma_tally3f_zgesv

subroutine magma_tally3f_zgesv_rbt( ref, n, nrhs, A, lda, B, ldb, info )
    character        :: ref
    integer          :: n
    integer          :: nrhs
    complex*16       :: A(*)
    integer          :: lda
    complex*16       :: B(*)
    integer          :: ldb
    integer          :: info
end subroutine magma_tally3f_zgesv_rbt

subroutine magma_tally3f_zgesvd( jobu, jobvt, m, n, A, lda, s, U, ldu, VT, ldvt, work, lwork,  &
        rwork, info )
    character        :: jobu
    character        :: jobvt
    integer          :: m
    integer          :: n
    complex*16       :: A(*)
    integer          :: lda
    double precision :: s(*)
    complex*16       :: U(*)
    integer          :: ldu
    complex*16       :: VT(*)
    integer          :: ldvt
    complex*16       :: work(*)
    integer          :: lwork
    double precision :: rwork(*)
    integer          :: info
end subroutine magma_tally3f_zgesvd

subroutine magma_tally3f_zgetf2_nopiv( m, n, A, lda, info )
    integer          :: m
    integer          :: n
    complex*16       :: A(*)
    integer          :: lda
    integer          :: info
end subroutine magma_tally3f_zgetf2_nopiv

subroutine magma_tally3f_zgetrf( m, n, A, lda, ipiv, info )
    integer          :: m
    integer          :: n
    complex*16       :: A(*)
    integer          :: lda
    integer          :: ipiv(*)
    integer          :: info
end subroutine magma_tally3f_zgetrf

subroutine magma_tally3f_zgetrf_nopiv( m, n, A, lda, info )
    integer          :: m
    integer          :: n
    complex*16       :: A(*)
    integer          :: lda
    integer          :: info
end subroutine magma_tally3f_zgetrf_nopiv

subroutine magma_tally3f_zgetrf_piv( m, n, NB, A, lda, ipiv, info )
    integer          :: m
    integer          :: n
    integer          :: NB
    complex*16       :: A(*)
    integer          :: lda
    integer          :: ipiv(*)
    integer          :: info
end subroutine magma_tally3f_zgetrf_piv

subroutine magma_tally3f_zheevd( jobz, uplo, n, A, lda, w, work, lwork, rwork, lrwork, iwork,  &
        liwork, info )
    character        :: jobz
    character        :: uplo
    integer          :: n
    complex*16       :: A(*)
    integer          :: lda
    double precision :: w(*)
    complex*16       :: work(*)
    integer          :: lwork
    double precision :: rwork(*)
    integer          :: lrwork
    integer          :: iwork(*)
    integer          :: liwork
    integer          :: info
end subroutine magma_tally3f_zheevd

subroutine magma_tally3f_zheevdx( jobz, range, uplo, n, A, lda, vl, vu, il, iu, m, w, work,  &
        lwork, rwork, lrwork, iwork, liwork, info )
    character        :: jobz
    character        :: range
    character        :: uplo
    integer          :: n
    complex*16       :: A(*)
    integer          :: lda
    double precision :: vl
    double precision :: vu
    integer          :: il
    integer          :: iu
    integer          :: m
    double precision :: w(*)
    complex*16       :: work(*)
    integer          :: lwork
    double precision :: rwork(*)
    integer          :: lrwork
    integer          :: iwork(*)
    integer          :: liwork
    integer          :: info
end subroutine magma_tally3f_zheevdx

subroutine magma_tally3f_zheevdx_2stage( jobz, range, uplo, n, A, lda, vl, vu, il, iu, m, w,  &
        work, lwork, rwork, lrwork, iwork, liwork, info )
    character        :: jobz
    character        :: range
    character        :: uplo
    integer          :: n
    complex*16       :: A(*)
    integer          :: lda
    double precision :: vl
    double precision :: vu
    integer          :: il
    integer          :: iu
    integer          :: m
    double precision :: w(*)
    complex*16       :: work(*)
    integer          :: lwork
    double precision :: rwork(*)
    integer          :: lrwork
    integer          :: iwork(*)
    integer          :: liwork
    integer          :: info
end subroutine magma_tally3f_zheevdx_2stage

subroutine magma_tally3f_zheevr( jobz, range, uplo, n, A, lda, vl, vu, il, iu, abstol, m, w, Z,  &
        ldz, isuppz, work, lwork, rwork, lrwork, iwork, liwork, info )
    character        :: jobz
    character        :: range
    character        :: uplo
    integer          :: n
    complex*16       :: A(*)
    integer          :: lda
    double precision :: vl
    double precision :: vu
    integer          :: il
    integer          :: iu
    double precision :: abstol
    integer          :: m
    double precision :: w(*)
    complex*16       :: Z(*)
    integer          :: ldz
    integer          :: isuppz(*)
    complex*16       :: work(*)
    integer          :: lwork
    double precision :: rwork(*)
    integer          :: lrwork
    integer          :: iwork(*)
    integer          :: liwork
    integer          :: info
end subroutine magma_tally3f_zheevr

subroutine magma_tally3f_zheevx( jobz, range, uplo, n, A, lda, vl, vu, il, iu, abstol, m, w, Z,  &
        ldz, work, lwork, rwork, iwork, ifail, info )
    character        :: jobz
    character        :: range
    character        :: uplo
    integer          :: n
    complex*16       :: A(*)
    integer          :: lda
    double precision :: vl
    double precision :: vu
    integer          :: il
    integer          :: iu
    double precision :: abstol
    integer          :: m
    double precision :: w(*)
    complex*16       :: Z(*)
    integer          :: ldz
    complex*16       :: work(*)
    integer          :: lwork
    double precision :: rwork(*)
    integer          :: iwork(*)
    integer          :: ifail(*)
    integer          :: info
end subroutine magma_tally3f_zheevx

subroutine magma_tally3f_zhegst( itype, uplo, n, A, lda, B, ldb, info )
    integer          :: itype
    character        :: uplo
    integer          :: n
    complex*16       :: A(*)
    integer          :: lda
    complex*16       :: B(*)
    integer          :: ldb
    integer          :: info
end subroutine magma_tally3f_zhegst

subroutine magma_tally3f_zhegvd( itype, jobz, uplo, n, A, lda, B, ldb, w, work, lwork, rwork,  &
        lrwork, iwork, liwork, info )
    integer          :: itype
    character        :: jobz
    character        :: uplo
    integer          :: n
    complex*16       :: A(*)
    integer          :: lda
    complex*16       :: B(*)
    integer          :: ldb
    double precision :: w(*)
    complex*16       :: work(*)
    integer          :: lwork
    double precision :: rwork(*)
    integer          :: lrwork
    integer          :: iwork(*)
    integer          :: liwork
    integer          :: info
end subroutine magma_tally3f_zhegvd

subroutine magma_tally3f_zhegvdx( itype, jobz, range, uplo, n, A, lda, B, ldb, vl, vu, il, iu,  &
        m, w, work, lwork, rwork, lrwork, iwork, liwork, info )
    integer          :: itype
    character        :: jobz
    character        :: range
    character        :: uplo
    integer          :: n
    complex*16       :: A(*)
    integer          :: lda
    complex*16       :: B(*)
    integer          :: ldb
    double precision :: vl
    double precision :: vu
    integer          :: il
    integer          :: iu
    integer          :: m
    double precision :: w(*)
    complex*16       :: work(*)
    integer          :: lwork
    double precision :: rwork(*)
    integer          :: lrwork
    integer          :: iwork(*)
    integer          :: liwork
    integer          :: info
end subroutine magma_tally3f_zhegvdx

subroutine magma_tally3f_zhegvdx_2stage( itype, jobz, range, uplo, n, A, lda, B, ldb, vl, vu,  &
        il, iu, m, w, work, lwork, rwork, lrwork, iwork, liwork, info )
    integer          :: itype
    character        :: jobz
    character        :: range
    character        :: uplo
    integer          :: n
    complex*16       :: A(*)
    integer          :: lda
    complex*16       :: B(*)
    integer          :: ldb
    double precision :: vl
    double precision :: vu
    integer          :: il
    integer          :: iu
    integer          :: m
    double precision :: w(*)
    complex*16       :: work(*)
    integer          :: lwork
    double precision :: rwork(*)
    integer          :: lrwork
    integer          :: iwork(*)
    integer          :: liwork
    integer          :: info
end subroutine magma_tally3f_zhegvdx_2stage

subroutine magma_tally3f_zhegvr( itype, jobz, range, uplo, n, A, lda, B, ldb, vl, vu, il, iu,  &
        abstol, m, w, Z, ldz, isuppz, work, lwork, rwork, lrwork, iwork, liwork, info )
    integer          :: itype
    character        :: jobz
    character        :: range
    character        :: uplo
    integer          :: n
    complex*16       :: A(*)
    integer          :: lda
    complex*16       :: B(*)
    integer          :: ldb
    double precision :: vl
    double precision :: vu
    integer          :: il
    integer          :: iu
    double precision :: abstol
    integer          :: m
    double precision :: w(*)
    complex*16       :: Z(*)
    integer          :: ldz
    integer          :: isuppz(*)
    complex*16       :: work(*)
    integer          :: lwork
    double precision :: rwork(*)
    integer          :: lrwork
    integer          :: iwork(*)
    integer          :: liwork
    integer          :: info
end subroutine magma_tally3f_zhegvr

subroutine magma_tally3f_zhegvx( itype, jobz, range, uplo, n, A, lda, B, ldb, vl, vu, il, iu,  &
        abstol, m, w, Z, ldz, work, lwork, rwork, iwork, ifail, info )
    integer          :: itype
    character        :: jobz
    character        :: range
    character        :: uplo
    integer          :: n
    complex*16       :: A(*)
    integer          :: lda
    complex*16       :: B(*)
    integer          :: ldb
    double precision :: vl
    double precision :: vu
    integer          :: il
    integer          :: iu
    double precision :: abstol
    integer          :: m
    double precision :: w(*)
    complex*16       :: Z(*)
    integer          :: ldz
    complex*16       :: work(*)
    integer          :: lwork
    double precision :: rwork(*)
    integer          :: iwork(*)
    integer          :: ifail(*)
    integer          :: info
end subroutine magma_tally3f_zhegvx

subroutine magma_tally3f_zhesv( uplo, n, nrhs, A, lda, ipiv, B, ldb, info )
    character        :: uplo
    integer          :: n
    integer          :: nrhs
    complex*16       :: A(*)
    integer          :: lda
    integer          :: ipiv(*)
    complex*16       :: B(*)
    integer          :: ldb
    integer          :: info
end subroutine magma_tally3f_zhesv

subroutine magma_tally3f_zhetrd( uplo, n, A, lda, d, e, tau, work, lwork, info )
    character        :: uplo
    integer          :: n
    complex*16       :: A(*)
    integer          :: lda
    double precision :: d(*)
    double precision :: e(*)
    complex*16       :: tau(*)
    complex*16       :: work(*)
    integer          :: lwork
    integer          :: info
end subroutine magma_tally3f_zhetrd

subroutine magma_tally3f_zhetrf( uplo, n, A, lda, ipiv, info )
    character        :: uplo
    integer          :: n
    complex*16       :: A(*)
    integer          :: lda
    integer          :: ipiv(*)
    integer          :: info
end subroutine magma_tally3f_zhetrf

subroutine magma_tally3f_zhetrf_nopiv_tally3( uplo, n, a, lda, info )
    character        :: uplo
    integer          :: n
    complex*16       :: a(*)
    integer          :: lda
    integer          :: info
end subroutine magma_tally3f_zhetrf_nopiv_tally3

subroutine magma_tally3f_zhetrd_hb2st( uplo, n, nb, Vblksiz, A, lda, d, e, V, ldv, TAU, compT,  &
        T, ldt )
    character        :: uplo
    integer          :: n
    integer          :: nb
    integer          :: Vblksiz
    complex*16       :: A(*)
    integer          :: lda
    double precision :: d(*)
    double precision :: e(*)
    complex*16       :: V(*)
    integer          :: ldv
    complex*16       :: TAU(*)
    integer          :: compT
    complex*16       :: T(*)
    integer          :: ldt
end subroutine magma_tally3f_zhetrd_hb2st

subroutine magma_tally3f_zhetrd_he2hb( uplo, n, nb, A, lda, tau, work, lwork, dT, info )
    character        :: uplo
    integer          :: n
    integer          :: nb
    complex*16       :: A(*)
    integer          :: lda
    complex*16       :: tau(*)
    complex*16       :: work(*)
    integer          :: lwork
    magma_tally3_devptr_t   :: dT
    integer          :: info
end subroutine magma_tally3f_zhetrd_he2hb

subroutine magma_tally3f_zlatrsd( uplo, trans, diag, normin, n, A, lda, lambda, x, scale, cnorm,  &
        info )
    character        :: uplo
    character        :: trans
    character        :: diag
    character        :: normin
    integer          :: n
    complex*16       :: A(*)
    integer          :: lda
    complex*16       :: lambda
    complex*16       :: x(*)
    double precision :: scale(*)
    double precision :: cnorm(*)
    integer          :: info
end subroutine magma_tally3f_zlatrsd

subroutine magma_tally3f_zlauum( uplo, n, A, lda, info )
    character        :: uplo
    integer          :: n
    complex*16       :: A(*)
    integer          :: lda
    integer          :: info
end subroutine magma_tally3f_zlauum

subroutine magma_tally3f_zposv( uplo, n, nrhs, A, lda, B, ldb, info )
    character        :: uplo
    integer          :: n
    integer          :: nrhs
    complex*16       :: A(*)
    integer          :: lda
    complex*16       :: B(*)
    integer          :: ldb
    integer          :: info
end subroutine magma_tally3f_zposv

subroutine magma_tally3f_zpotrf( uplo, n, A, lda, info )
    character        :: uplo
    integer          :: n
    complex*16       :: A(*)
    integer          :: lda
    integer          :: info
end subroutine magma_tally3f_zpotrf

subroutine magma_tally3f_zpotri( uplo, n, A, lda, info )
    character        :: uplo
    integer          :: n
    complex*16       :: A(*)
    integer          :: lda
    integer          :: info
end subroutine magma_tally3f_zpotri

subroutine magma_tally3f_zstedx( range, n, vl, vu, il, iu, d, e, Z, ldz, rwork, lrwork, iwork,  &
        liwork, dwork, info )
    character        :: range
    integer          :: n
    double precision :: vl
    double precision :: vu
    integer          :: il
    integer          :: iu
    double precision :: d(*)
    double precision :: e(*)
    complex*16       :: Z(*)
    integer          :: ldz
    double precision :: rwork(*)
    integer          :: lrwork
    integer          :: iwork(*)
    integer          :: liwork
    magma_tally3_devptr_t   :: dwork
    integer          :: info
end subroutine magma_tally3f_zstedx

subroutine magma_tally3f_ztrevc3( side, howmany, select, n, T, ldt, VL, ldvl, VR, ldvr, mm,  &
        mout, work, lwork, rwork, info )
    character        :: side
    character        :: howmany
    integer          :: select(*)
    integer          :: n
    complex*16       :: T(*)
    integer          :: ldt
    complex*16       :: VL(*)
    integer          :: ldvl
    complex*16       :: VR(*)
    integer          :: ldvr
    integer          :: mm
    integer          :: mout(*)
    complex*16       :: work(*)
    integer          :: lwork
    double precision :: rwork(*)
    integer          :: info
end subroutine magma_tally3f_ztrevc3

subroutine magma_tally3f_ztrevc3_mt( side, howmany, select, n, T, ldt, VL, ldvl, VR, ldvr, mm,  &
        mout, work, lwork, rwork, info )
    character        :: side
    character        :: howmany
    integer          :: select(*)
    integer          :: n
    complex*16       :: T(*)
    integer          :: ldt
    complex*16       :: VL(*)
    integer          :: ldvl
    complex*16       :: VR(*)
    integer          :: ldvr
    integer          :: mm
    integer          :: mout(*)
    complex*16       :: work(*)
    integer          :: lwork
    double precision :: rwork(*)
    integer          :: info
end subroutine magma_tally3f_ztrevc3_mt

subroutine magma_tally3f_ztrtri( uplo, diag, n, A, lda, info )
    character        :: uplo
    character        :: diag
    integer          :: n
    complex*16       :: A(*)
    integer          :: lda
    integer          :: info
end subroutine magma_tally3f_ztrtri

subroutine magma_tally3f_zunghr( n, ilo, ihi, A, lda, tau, dT, nb, info )
    integer          :: n
    integer          :: ilo
    integer          :: ihi
    complex*16       :: A(*)
    integer          :: lda
    complex*16       :: tau(*)
    magma_tally3_devptr_t   :: dT
    integer          :: nb
    integer          :: info
end subroutine magma_tally3f_zunghr

subroutine magma_tally3f_zungqr( m, n, k, A, lda, tau, dT, nb, info )
    integer          :: m
    integer          :: n
    integer          :: k
    complex*16       :: A(*)
    integer          :: lda
    complex*16       :: tau(*)
    magma_tally3_devptr_t   :: dT
    integer          :: nb
    integer          :: info
end subroutine magma_tally3f_zungqr

subroutine magma_tally3f_zungqr2( m, n, k, A, lda, tau, info )
    integer          :: m
    integer          :: n
    integer          :: k
    complex*16       :: A(*)
    integer          :: lda
    complex*16       :: tau(*)
    integer          :: info
end subroutine magma_tally3f_zungqr2

subroutine magma_tally3f_zunmbr( vect, side, trans, m, n, k, A, lda, tau, C, ldc, work, lwork,  &
        info )
    character        :: vect
    character        :: side
    character        :: trans
    integer          :: m
    integer          :: n
    integer          :: k
    complex*16       :: A(*)
    integer          :: lda
    complex*16       :: tau(*)
    complex*16       :: C(*)
    integer          :: ldc
    complex*16       :: work(*)
    integer          :: lwork
    integer          :: info
end subroutine magma_tally3f_zunmbr

subroutine magma_tally3f_zunmlq( side, trans, m, n, k, A, lda, tau, C, ldc, work, lwork, info )
    character        :: side
    character        :: trans
    integer          :: m
    integer          :: n
    integer          :: k
    complex*16       :: A(*)
    integer          :: lda
    complex*16       :: tau(*)
    complex*16       :: C(*)
    integer          :: ldc
    complex*16       :: work(*)
    integer          :: lwork
    integer          :: info
end subroutine magma_tally3f_zunmlq

subroutine magma_tally3f_zunmql( side, trans, m, n, k, A, lda, tau, C, ldc, work, lwork, info )
    character        :: side
    character        :: trans
    integer          :: m
    integer          :: n
    integer          :: k
    complex*16       :: A(*)
    integer          :: lda
    complex*16       :: tau(*)
    complex*16       :: C(*)
    integer          :: ldc
    complex*16       :: work(*)
    integer          :: lwork
    integer          :: info
end subroutine magma_tally3f_zunmql

subroutine magma_tally3f_zunmqr( side, trans, m, n, k, A, lda, tau, C, ldc, work, lwork, info )
    character        :: side
    character        :: trans
    integer          :: m
    integer          :: n
    integer          :: k
    complex*16       :: A(*)
    integer          :: lda
    complex*16       :: tau(*)
    complex*16       :: C(*)
    integer          :: ldc
    complex*16       :: work(*)
    integer          :: lwork
    integer          :: info
end subroutine magma_tally3f_zunmqr

subroutine magma_tally3f_zunmtr( side, uplo, trans, m, n, A, lda, tau, C, ldc, work, lwork, info  &
        )
    character        :: side
    character        :: uplo
    character        :: trans
    integer          :: m
    integer          :: n
    complex*16       :: A(*)
    integer          :: lda
    complex*16       :: tau(*)
    complex*16       :: C(*)
    integer          :: ldc
    complex*16       :: work(*)
    integer          :: lwork
    integer          :: info
end subroutine magma_tally3f_zunmtr

subroutine magma_tally3f_zgeev_m( jobvl, jobvr, n, A, lda, w, VL, ldvl, VR, ldvr, work, lwork,  &
        rwork, info )
    character        :: jobvl
    character        :: jobvr
    integer          :: n
    complex*16       :: A(*)
    integer          :: lda
    complex*16       :: w(*)
    complex*16       :: VL(*)
    integer          :: ldvl
    complex*16       :: VR(*)
    integer          :: ldvr
    complex*16       :: work(*)
    integer          :: lwork
    double precision :: rwork(*)
    integer          :: info
end subroutine magma_tally3f_zgeev_m

subroutine magma_tally3f_zgehrd_m( n, ilo, ihi, A, lda, tau, work, lwork, T, info )
    integer          :: n
    integer          :: ilo
    integer          :: ihi
    complex*16       :: A(*)
    integer          :: lda
    complex*16       :: tau(*)
    complex*16       :: work(*)
    integer          :: lwork
    complex*16       :: T(*)
    integer          :: info
end subroutine magma_tally3f_zgehrd_m

subroutine magma_tally3f_zgetrf_m( ngpu, m, n, A, lda, ipiv, info )
    integer          :: ngpu
    integer          :: m
    integer          :: n
    complex*16       :: A(*)
    integer          :: lda
    integer          :: ipiv(*)
    integer          :: info
end subroutine magma_tally3f_zgetrf_m

subroutine magma_tally3f_zheevd_m( ngpu, jobz, uplo, n, A, lda, w, work, lwork, rwork, lrwork,  &
        iwork, liwork, info )
    integer          :: ngpu
    character        :: jobz
    character        :: uplo
    integer          :: n
    complex*16       :: A(*)
    integer          :: lda
    double precision :: w(*)
    complex*16       :: work(*)
    integer          :: lwork
    double precision :: rwork(*)
    integer          :: lrwork
    integer          :: iwork(*)
    integer          :: liwork
    integer          :: info
end subroutine magma_tally3f_zheevd_m

subroutine magma_tally3f_zheevdx_2stage_m( ngpu, jobz, range, uplo, n, A, lda, vl, vu, il, iu,  &
        m, w, work, lwork, rwork, lrwork, iwork, liwork, info )
    integer          :: ngpu
    character        :: jobz
    character        :: range
    character        :: uplo
    integer          :: n
    complex*16       :: A(*)
    integer          :: lda
    double precision :: vl
    double precision :: vu
    integer          :: il
    integer          :: iu
    integer          :: m
    double precision :: w(*)
    complex*16       :: work(*)
    integer          :: lwork
    double precision :: rwork(*)
    integer          :: lrwork
    integer          :: iwork(*)
    integer          :: liwork
    integer          :: info
end subroutine magma_tally3f_zheevdx_2stage_m

subroutine magma_tally3f_zheevdx_m( ngpu, jobz, range, uplo, n, A, lda, vl, vu, il, iu, m, w,  &
        work, lwork, rwork, lrwork, iwork, liwork, info )
    integer          :: ngpu
    character        :: jobz
    character        :: range
    character        :: uplo
    integer          :: n
    complex*16       :: A(*)
    integer          :: lda
    double precision :: vl
    double precision :: vu
    integer          :: il
    integer          :: iu
    integer          :: m
    double precision :: w(*)
    complex*16       :: work(*)
    integer          :: lwork
    double precision :: rwork(*)
    integer          :: lrwork
    integer          :: iwork(*)
    integer          :: liwork
    integer          :: info
end subroutine magma_tally3f_zheevdx_m

subroutine magma_tally3f_zhegst_m( ngpu, itype, uplo, n, A, lda, B, ldb, info )
    integer          :: ngpu
    integer          :: itype
    character        :: uplo
    integer          :: n
    complex*16       :: A(*)
    integer          :: lda
    complex*16       :: B(*)
    integer          :: ldb
    integer          :: info
end subroutine magma_tally3f_zhegst_m

subroutine magma_tally3f_zhegvd_m( ngpu, itype, jobz, uplo, n, A, lda, B, ldb, w, work, lwork,  &
        rwork, lrwork, iwork, liwork, info )
    integer          :: ngpu
    integer          :: itype
    character        :: jobz
    character        :: uplo
    integer          :: n
    complex*16       :: A(*)
    integer          :: lda
    complex*16       :: B(*)
    integer          :: ldb
    double precision :: w(*)
    complex*16       :: work(*)
    integer          :: lwork
    double precision :: rwork(*)
    integer          :: lrwork
    integer          :: iwork(*)
    integer          :: liwork
    integer          :: info
end subroutine magma_tally3f_zhegvd_m

subroutine magma_tally3f_zhegvdx_2stage_m( ngpu, itype, jobz, range, uplo, n, A, lda, B, ldb,  &
        vl, vu, il, iu, m, w, work, lwork, rwork, lrwork, iwork, liwork, info )
    integer          :: ngpu
    integer          :: itype
    character        :: jobz
    character        :: range
    character        :: uplo
    integer          :: n
    complex*16       :: A(*)
    integer          :: lda
    complex*16       :: B(*)
    integer          :: ldb
    double precision :: vl
    double precision :: vu
    integer          :: il
    integer          :: iu
    integer          :: m
    double precision :: w(*)
    complex*16       :: work(*)
    integer          :: lwork
    double precision :: rwork(*)
    integer          :: lrwork
    integer          :: iwork(*)
    integer          :: liwork
    integer          :: info
end subroutine magma_tally3f_zhegvdx_2stage_m

subroutine magma_tally3f_zhegvdx_m( ngpu, itype, jobz, range, uplo, n, A, lda, B, ldb, vl, vu,  &
        il, iu, m, w, work, lwork, rwork, lrwork, iwork, liwork, info )
    integer          :: ngpu
    integer          :: itype
    character        :: jobz
    character        :: range
    character        :: uplo
    integer          :: n
    complex*16       :: A(*)
    integer          :: lda
    complex*16       :: B(*)
    integer          :: ldb
    double precision :: vl
    double precision :: vu
    integer          :: il
    integer          :: iu
    integer          :: m
    double precision :: w(*)
    complex*16       :: work(*)
    integer          :: lwork
    double precision :: rwork(*)
    integer          :: lrwork
    integer          :: iwork(*)
    integer          :: liwork
    integer          :: info
end subroutine magma_tally3f_zhegvdx_m

subroutine magma_tally3f_zpotrf_m( ngpu, uplo, n, A, lda, info )
    integer          :: ngpu
    character        :: uplo
    integer          :: n
    complex*16       :: A(*)
    integer          :: lda
    integer          :: info
end subroutine magma_tally3f_zpotrf_m

subroutine magma_tally3f_zstedx_m( ngpu, range, n, vl, vu, il, iu, d, e, Z, ldz, rwork, lrwork,  &
        iwork, liwork, info )
    integer          :: ngpu
    character        :: range
    integer          :: n
    double precision :: vl
    double precision :: vu
    integer          :: il
    integer          :: iu
    double precision :: d(*)
    double precision :: e(*)
    complex*16       :: Z(*)
    integer          :: ldz
    double precision :: rwork(*)
    integer          :: lrwork
    integer          :: iwork(*)
    integer          :: liwork
    integer          :: info
end subroutine magma_tally3f_zstedx_m

subroutine magma_tally3f_ztrsm_m( ngpu, side, uplo, transa, diag, m, n, alpha, A, lda, B, ldb )
    integer          :: ngpu
    character        :: side
    character        :: uplo
    character        :: transa
    character        :: diag
    integer          :: m
    integer          :: n
    complex*16       :: alpha
    complex*16       :: A(*)
    integer          :: lda
    complex*16       :: B(*)
    integer          :: ldb
end subroutine magma_tally3f_ztrsm_m

subroutine magma_tally3f_zunghr_m( n, ilo, ihi, A, lda, tau, T, nb, info )
    integer          :: n
    integer          :: ilo
    integer          :: ihi
    complex*16       :: A(*)
    integer          :: lda
    complex*16       :: tau(*)
    complex*16       :: T(*)
    integer          :: nb
    integer          :: info
end subroutine magma_tally3f_zunghr_m

subroutine magma_tally3f_zungqr_m( m, n, k, A, lda, tau, T, nb, info )
    integer          :: m
    integer          :: n
    integer          :: k
    complex*16       :: A(*)
    integer          :: lda
    complex*16       :: tau(*)
    complex*16       :: T(*)
    integer          :: nb
    integer          :: info
end subroutine magma_tally3f_zungqr_m

subroutine magma_tally3f_zunmqr_m( ngpu, side, trans, m, n, k, A, lda, tau, C, ldc, work, lwork,  &
        info )
    integer          :: ngpu
    character        :: side
    character        :: trans
    integer          :: m
    integer          :: n
    integer          :: k
    complex*16       :: A(*)
    integer          :: lda
    complex*16       :: tau(*)
    complex*16       :: C(*)
    integer          :: ldc
    complex*16       :: work(*)
    integer          :: lwork
    integer          :: info
end subroutine magma_tally3f_zunmqr_m

subroutine magma_tally3f_zunmtr_m( ngpu, side, uplo, trans, m, n, A, lda, tau, C, ldc, work,  &
        lwork, info )
    integer          :: ngpu
    character        :: side
    character        :: uplo
    character        :: trans
    integer          :: m
    integer          :: n
    complex*16       :: A(*)
    integer          :: lda
    complex*16       :: tau(*)
    complex*16       :: C(*)
    integer          :: ldc
    complex*16       :: work(*)
    integer          :: lwork
    integer          :: info
end subroutine magma_tally3f_zunmtr_m

subroutine magma_tally3f_zgegqr_gpu( ikind, m, n, dA, ldda, dwork, work, info )
    integer          :: ikind
    integer          :: m
    integer          :: n
    magma_tally3_devptr_t   :: dA
    integer          :: ldda
    magma_tally3_devptr_t   :: dwork
    complex*16       :: work(*)
    integer          :: info
end subroutine magma_tally3f_zgegqr_gpu

subroutine magma_tally3f_zgelqf_gpu( m, n, dA, ldda, tau, work, lwork, info )
    integer          :: m
    integer          :: n
    magma_tally3_devptr_t   :: dA
    integer          :: ldda
    complex*16       :: tau(*)
    complex*16       :: work(*)
    integer          :: lwork
    integer          :: info
end subroutine magma_tally3f_zgelqf_gpu

subroutine magma_tally3f_zgels_gpu( trans, m, n, nrhs, dA, ldda, dB, lddb, hwork, lwork, info )
    character        :: trans
    integer          :: m
    integer          :: n
    integer          :: nrhs
    magma_tally3_devptr_t   :: dA
    integer          :: ldda
    magma_tally3_devptr_t   :: dB
    integer          :: lddb
    complex*16       :: hwork(*)
    integer          :: lwork
    integer          :: info
end subroutine magma_tally3f_zgels_gpu

subroutine magma_tally3f_zgels3_gpu( trans, m, n, nrhs, dA, ldda, dB, lddb, hwork, lwork, info )
    character        :: trans
    integer          :: m
    integer          :: n
    integer          :: nrhs
    magma_tally3_devptr_t   :: dA
    integer          :: ldda
    magma_tally3_devptr_t   :: dB
    integer          :: lddb
    complex*16       :: hwork(*)
    integer          :: lwork
    integer          :: info
end subroutine magma_tally3f_zgels3_gpu

subroutine magma_tally3f_zgeqp3_gpu( m, n, dA, ldda, jpvt, tau, dwork, lwork, rwork, info )
    integer          :: m
    integer          :: n
    magma_tally3_devptr_t   :: dA
    integer          :: ldda
    integer          :: jpvt(*)
    complex*16       :: tau(*)
    magma_tally3_devptr_t   :: dwork
    integer          :: lwork
    double precision :: rwork(*)
    integer          :: info
end subroutine magma_tally3f_zgeqp3_gpu

subroutine magma_tally3f_zgeqr2x_gpu( m, n, dA, ldda, dtau, dT, ddA, dwork, info )
    integer          :: m
    integer          :: n
    magma_tally3_devptr_t   :: dA
    integer          :: ldda
    magma_tally3_devptr_t   :: dtau
    magma_tally3_devptr_t   :: dT
    magma_tally3_devptr_t   :: ddA
    magma_tally3_devptr_t   :: dwork
    integer          :: info
end subroutine magma_tally3f_zgeqr2x_gpu

subroutine magma_tally3f_zgeqr2x2_gpu( m, n, dA, ldda, dtau, dT, ddA, dwork, info )
    integer          :: m
    integer          :: n
    magma_tally3_devptr_t   :: dA
    integer          :: ldda
    magma_tally3_devptr_t   :: dtau
    magma_tally3_devptr_t   :: dT
    magma_tally3_devptr_t   :: ddA
    magma_tally3_devptr_t   :: dwork
    integer          :: info
end subroutine magma_tally3f_zgeqr2x2_gpu

subroutine magma_tally3f_zgeqr2x3_gpu( m, n, dA, ldda, dtau, dT, ddA, dwork, info )
    integer          :: m
    integer          :: n
    magma_tally3_devptr_t   :: dA
    integer          :: ldda
    magma_tally3_devptr_t   :: dtau
    magma_tally3_devptr_t   :: dT
    magma_tally3_devptr_t   :: ddA
    magma_tally3_devptr_t   :: dwork
    integer          :: info
end subroutine magma_tally3f_zgeqr2x3_gpu

subroutine magma_tally3f_zgeqr2x4_gpu( m, n, dA, ldda, dtau, dT, ddA, dwork, queue, info )
    integer          :: m
    integer          :: n
    magma_tally3_devptr_t   :: dA
    integer          :: ldda
    magma_tally3_devptr_t   :: dtau
    magma_tally3_devptr_t   :: dT
    magma_tally3_devptr_t   :: ddA
    magma_tally3_devptr_t   :: dwork
    integer          :: queue
    integer          :: info
end subroutine magma_tally3f_zgeqr2x4_gpu

subroutine magma_tally3f_zgeqrf_gpu( m, n, dA, ldda, tau, dT, info )
    integer          :: m
    integer          :: n
    magma_tally3_devptr_t   :: dA
    integer          :: ldda
    complex*16       :: tau(*)
    magma_tally3_devptr_t   :: dT
    integer          :: info
end subroutine magma_tally3f_zgeqrf_gpu

subroutine magma_tally3f_zgeqrf2_gpu( m, n, dA, ldda, tau, info )
    integer          :: m
    integer          :: n
    magma_tally3_devptr_t   :: dA
    integer          :: ldda
    complex*16       :: tau(*)
    integer          :: info
end subroutine magma_tally3f_zgeqrf2_gpu

subroutine magma_tally3f_zgeqrf3_gpu( m, n, dA, ldda, tau, dT, info )
    integer          :: m
    integer          :: n
    magma_tally3_devptr_t   :: dA
    integer          :: ldda
    complex*16       :: tau(*)
    magma_tally3_devptr_t   :: dT
    integer          :: info
end subroutine magma_tally3f_zgeqrf3_gpu

subroutine magma_tally3f_zgeqrs_gpu( m, n, nrhs, dA, ldda, tau, dT, dB, lddb, hwork, lwork, info  &
        )
    integer          :: m
    integer          :: n
    integer          :: nrhs
    magma_tally3_devptr_t   :: dA
    integer          :: ldda
    complex*16       :: tau(*)
    magma_tally3_devptr_t   :: dT
    magma_tally3_devptr_t   :: dB
    integer          :: lddb
    complex*16       :: hwork(*)
    integer          :: lwork
    integer          :: info
end subroutine magma_tally3f_zgeqrs_gpu

subroutine magma_tally3f_zgeqrs3_gpu( m, n, nrhs, dA, ldda, tau, dT, dB, lddb, hwork, lwork,  &
        info )
    integer          :: m
    integer          :: n
    integer          :: nrhs
    magma_tally3_devptr_t   :: dA
    integer          :: ldda
    complex*16       :: tau(*)
    magma_tally3_devptr_t   :: dT
    magma_tally3_devptr_t   :: dB
    integer          :: lddb
    complex*16       :: hwork(*)
    integer          :: lwork
    integer          :: info
end subroutine magma_tally3f_zgeqrs3_gpu

subroutine magma_tally3f_zgerbt_gpu( gen, n, nrhs, dA, ldda, dB, lddb, U, V, info )
    character        :: gen
    integer          :: n
    integer          :: nrhs
    magma_tally3_devptr_t   :: dA
    integer          :: ldda
    magma_tally3_devptr_t   :: dB
    integer          :: lddb
    complex*16       :: U(*)
    complex*16       :: V(*)
    integer          :: info
end subroutine magma_tally3f_zgerbt_gpu

subroutine magma_tally3f_zgessm_gpu( order, m, n, k, ib, ipiv, dL1, lddl1, dL, lddl, dA, ldda,  &
        info )
    character        :: order
    integer          :: m
    integer          :: n
    integer          :: k
    integer          :: ib
    integer          :: ipiv(*)
    magma_tally3_devptr_t   :: dL1
    integer          :: lddl1
    magma_tally3_devptr_t   :: dL
    integer          :: lddl
    magma_tally3_devptr_t   :: dA
    integer          :: ldda
    integer          :: info
end subroutine magma_tally3f_zgessm_gpu

subroutine magma_tally3f_zgesv_gpu( n, nrhs, dA, ldda, ipiv, dB, lddb, info )
    integer          :: n
    integer          :: nrhs
    magma_tally3_devptr_t   :: dA
    integer          :: ldda
    integer          :: ipiv(*)
    magma_tally3_devptr_t   :: dB
    integer          :: lddb
    integer          :: info
end subroutine magma_tally3f_zgesv_gpu

subroutine magma_tally3f_zgesv_nopiv_gpu( n, nrhs, dA, ldda, dB, lddb, info )
    integer          :: n
    integer          :: nrhs
    magma_tally3_devptr_t   :: dA
    integer          :: ldda
    magma_tally3_devptr_t   :: dB
    integer          :: lddb
    integer          :: info
end subroutine magma_tally3f_zgesv_nopiv_gpu

subroutine magma_tally3f_zgetf2_gpu( m, n, dA, ldda, ipiv, info )
    integer          :: m
    integer          :: n
    magma_tally3_devptr_t   :: dA
    integer          :: ldda
    integer          :: ipiv(*)
    integer          :: info
end subroutine magma_tally3f_zgetf2_gpu

subroutine magma_tally3f_zgetrf_gpu( m, n, dA, ldda, ipiv, info )
    integer          :: m
    integer          :: n
    magma_tally3_devptr_t   :: dA
    integer          :: ldda
    integer          :: ipiv(*)
    integer          :: info
end subroutine magma_tally3f_zgetrf_gpu

subroutine magma_tally3f_zgetrf_nopiv_gpu( m, n, dA, ldda, info )
    integer          :: m
    integer          :: n
    magma_tally3_devptr_t   :: dA
    integer          :: ldda
    integer          :: info
end subroutine magma_tally3f_zgetrf_nopiv_gpu

subroutine magma_tally3f_zgetri_gpu( n, dA, ldda, ipiv, dwork, lwork, info )
    integer          :: n
    magma_tally3_devptr_t   :: dA
    integer          :: ldda
    integer          :: ipiv(*)
    magma_tally3_devptr_t   :: dwork
    integer          :: lwork
    integer          :: info
end subroutine magma_tally3f_zgetri_gpu

subroutine magma_tally3f_zgetrs_gpu( trans, n, nrhs, dA, ldda, ipiv, dB, lddb, info )
    character        :: trans
    integer          :: n
    integer          :: nrhs
    magma_tally3_devptr_t   :: dA
    integer          :: ldda
    integer          :: ipiv(*)
    magma_tally3_devptr_t   :: dB
    integer          :: lddb
    integer          :: info
end subroutine magma_tally3f_zgetrs_gpu

subroutine magma_tally3f_zgetrs_nopiv_gpu( trans, n, nrhs, dA, ldda, dB, lddb, info )
    character        :: trans
    integer          :: n
    integer          :: nrhs
    magma_tally3_devptr_t   :: dA
    integer          :: ldda
    magma_tally3_devptr_t   :: dB
    integer          :: lddb
    integer          :: info
end subroutine magma_tally3f_zgetrs_nopiv_gpu

subroutine magma_tally3f_zheevd_gpu( jobz, uplo, n, dA, ldda, w, wA, ldwa, work, lwork, rwork,  &
        lrwork, iwork, liwork, info )
    character        :: jobz
    character        :: uplo
    integer          :: n
    magma_tally3_devptr_t   :: dA
    integer          :: ldda
    double precision :: w(*)
    complex*16       :: wA(*)
    integer          :: ldwa
    complex*16       :: work(*)
    integer          :: lwork
    double precision :: rwork(*)
    integer          :: lrwork
    integer          :: iwork(*)
    integer          :: liwork
    integer          :: info
end subroutine magma_tally3f_zheevd_gpu

subroutine magma_tally3f_zheevdx_gpu( jobz, range, uplo, n, dA, ldda, vl, vu, il, iu, m, w, wA,  &
        ldwa, work, lwork, rwork, lrwork, iwork, liwork, info )
    character        :: jobz
    character        :: range
    character        :: uplo
    integer          :: n
    magma_tally3_devptr_t   :: dA
    integer          :: ldda
    double precision :: vl
    double precision :: vu
    integer          :: il
    integer          :: iu
    integer          :: m
    double precision :: w(*)
    complex*16       :: wA(*)
    integer          :: ldwa
    complex*16       :: work(*)
    integer          :: lwork
    double precision :: rwork(*)
    integer          :: lrwork
    integer          :: iwork(*)
    integer          :: liwork
    integer          :: info
end subroutine magma_tally3f_zheevdx_gpu

subroutine magma_tally3f_zheevr_gpu( jobz, range, uplo, n, dA, ldda, vl, vu, il, iu, abstol, m,  &
        w, dZ, lddz, isuppz, wA, ldwa, wZ, ldwz, work, lwork, rwork, lrwork, iwork,  &
        liwork, info )
    character        :: jobz
    character        :: range
    character        :: uplo
    integer          :: n
    magma_tally3_devptr_t   :: dA
    integer          :: ldda
    double precision :: vl
    double precision :: vu
    integer          :: il
    integer          :: iu
    double precision :: abstol
    integer          :: m
    double precision :: w(*)
    magma_tally3_devptr_t   :: dZ
    integer          :: lddz
    integer          :: isuppz(*)
    complex*16       :: wA(*)
    integer          :: ldwa
    complex*16       :: wZ(*)
    integer          :: ldwz
    complex*16       :: work(*)
    integer          :: lwork
    double precision :: rwork(*)
    integer          :: lrwork
    integer          :: iwork(*)
    integer          :: liwork
    integer          :: info
end subroutine magma_tally3f_zheevr_gpu

subroutine magma_tally3f_zheevx_gpu( jobz, range, uplo, n, dA, ldda, vl, vu, il, iu, abstol, m,  &
        w, dZ, lddz, wA, ldwa, wZ, ldwz, work, lwork, rwork, iwork, ifail, info )
    character        :: jobz
    character        :: range
    character        :: uplo
    integer          :: n
    magma_tally3_devptr_t   :: dA
    integer          :: ldda
    double precision :: vl
    double precision :: vu
    integer          :: il
    integer          :: iu
    double precision :: abstol
    integer          :: m
    double precision :: w(*)
    magma_tally3_devptr_t   :: dZ
    integer          :: lddz
    complex*16       :: wA(*)
    integer          :: ldwa
    complex*16       :: wZ(*)
    integer          :: ldwz
    complex*16       :: work(*)
    integer          :: lwork
    double precision :: rwork(*)
    integer          :: iwork(*)
    integer          :: ifail(*)
    integer          :: info
end subroutine magma_tally3f_zheevx_gpu

subroutine magma_tally3f_zhegst_gpu( itype, uplo, n, dA, ldda, dB, lddb, info )
    integer          :: itype
    character        :: uplo
    integer          :: n
    magma_tally3_devptr_t   :: dA
    integer          :: ldda
    magma_tally3_devptr_t   :: dB
    integer          :: lddb
    integer          :: info
end subroutine magma_tally3f_zhegst_gpu

subroutine magma_tally3f_zhetrd_gpu( uplo, n, dA, ldda, d, e, tau, wA, ldwa, work, lwork, info )
    character        :: uplo
    integer          :: n
    magma_tally3_devptr_t   :: dA
    integer          :: ldda
    double precision :: d(*)
    double precision :: e(*)
    complex*16       :: tau(*)
    complex*16       :: wA(*)
    integer          :: ldwa
    complex*16       :: work(*)
    integer          :: lwork
    integer          :: info
end subroutine magma_tally3f_zhetrd_gpu

subroutine magma_tally3f_zhetrd2_gpu( uplo, n, dA, ldda, d, e, tau, wA, ldwa, work, lwork,  &
        dwork, ldwork, info )
    character        :: uplo
    integer          :: n
    magma_tally3_devptr_t   :: dA
    integer          :: ldda
    double precision :: d(*)
    double precision :: e(*)
    complex*16       :: tau(*)
    complex*16       :: wA(*)
    integer          :: ldwa
    complex*16       :: work(*)
    integer          :: lwork
    magma_tally3_devptr_t   :: dwork
    integer          :: ldwork
    integer          :: info
end subroutine magma_tally3f_zhetrd2_gpu

subroutine magma_tally3f_zhetrf_nopiv_tally3_gpu( uplo, n, da, ldda, info )
    character        :: uplo
    integer          :: n
    magma_tally3_devptr_t   :: da
    integer          :: ldda
    integer          :: info
end subroutine magma_tally3f_zhetrf_nopiv_tally3_gpu

subroutine magma_tally3f_zlarf_gpu( m, n, dv, dtau, dC, lddc )
    integer          :: m
    integer          :: n
    magma_tally3_devptr_t   :: dv
    magma_tally3_devptr_t   :: dtau
    magma_tally3_devptr_t   :: dC
    integer          :: lddc
end subroutine magma_tally3f_zlarf_gpu

subroutine magma_tally3f_zlarfb_gpu( side, trans, direct, storev, m, n, k, dV, lddv, dT, lddt,  &
        dC, lddc, dwork, ldwork )
    character        :: side
    character        :: trans
    character        :: direct
    character        :: storev
    integer          :: m
    integer          :: n
    integer          :: k
    magma_tally3_devptr_t   :: dV
    integer          :: lddv
    magma_tally3_devptr_t   :: dT
    integer          :: lddt
    magma_tally3_devptr_t   :: dC
    integer          :: lddc
    magma_tally3_devptr_t   :: dwork
    integer          :: ldwork
end subroutine magma_tally3f_zlarfb_gpu

subroutine magma_tally3f_zlarfb_gpu_gemm( side, trans, direct, storev, m, n, k, dV, lddv, dT,  &
        lddt, dC, lddc, dwork, ldwork, dworkvt, ldworkvt )
    character        :: side
    character        :: trans
    character        :: direct
    character        :: storev
    integer          :: m
    integer          :: n
    integer          :: k
    magma_tally3_devptr_t   :: dV
    integer          :: lddv
    magma_tally3_devptr_t   :: dT
    integer          :: lddt
    magma_tally3_devptr_t   :: dC
    integer          :: lddc
    magma_tally3_devptr_t   :: dwork
    integer          :: ldwork
    magma_tally3_devptr_t   :: dworkvt
    integer          :: ldworkvt
end subroutine magma_tally3f_zlarfb_gpu_gemm

subroutine magma_tally3f_zlarfb2_gpu( m, n, k, dV, lddv, dT, lddt, dC, lddc, dwork, ldwork )
    integer          :: m
    integer          :: n
    integer          :: k
    magma_tally3_devptr_t   :: dV
    integer          :: lddv
    magma_tally3_devptr_t   :: dT
    integer          :: lddt
    magma_tally3_devptr_t   :: dC
    integer          :: lddc
    magma_tally3_devptr_t   :: dwork
    integer          :: ldwork
end subroutine magma_tally3f_zlarfb2_gpu

subroutine magma_tally3f_zlauum_gpu( uplo, n, dA, ldda, info )
    character        :: uplo
    integer          :: n
    magma_tally3_devptr_t   :: dA
    integer          :: ldda
    integer          :: info
end subroutine magma_tally3f_zlauum_gpu

subroutine magma_tally3f_zposv_gpu( uplo, n, nrhs, dA, ldda, dB, lddb, info )
    character        :: uplo
    integer          :: n
    integer          :: nrhs
    magma_tally3_devptr_t   :: dA
    integer          :: ldda
    magma_tally3_devptr_t   :: dB
    integer          :: lddb
    integer          :: info
end subroutine magma_tally3f_zposv_gpu

subroutine magma_tally3f_zpotf2_gpu( uplo, n, dA, ldda, info )
    character        :: uplo
    integer          :: n
    magma_tally3_devptr_t   :: dA
    integer          :: ldda
    integer          :: info
end subroutine magma_tally3f_zpotf2_gpu

subroutine magma_tally3f_zpotrf_gpu( uplo, n, dA, ldda, info )
    character        :: uplo
    integer          :: n
    magma_tally3_devptr_t   :: dA
    integer          :: ldda
    integer          :: info
end subroutine magma_tally3f_zpotrf_gpu

subroutine magma_tally3f_zpotri_gpu( uplo, n, dA, ldda, info )
    character        :: uplo
    integer          :: n
    magma_tally3_devptr_t   :: dA
    integer          :: ldda
    integer          :: info
end subroutine magma_tally3f_zpotri_gpu

subroutine magma_tally3f_zpotrs_gpu( uplo, n, nrhs, dA, ldda, dB, lddb, info )
    character        :: uplo
    integer          :: n
    integer          :: nrhs
    magma_tally3_devptr_t   :: dA
    integer          :: ldda
    magma_tally3_devptr_t   :: dB
    integer          :: lddb
    integer          :: info
end subroutine magma_tally3f_zpotrs_gpu

subroutine magma_tally3f_zssssm_gpu( order, m1, n1, m2, n2, k, ib, dA1, ldda1, dA2, ldda2, dL1,  &
        lddl1, dL2, lddl2, ipiv, info )
    character        :: order
    integer          :: m1
    integer          :: n1
    integer          :: m2
    integer          :: n2
    integer          :: k
    integer          :: ib
    magma_tally3_devptr_t   :: dA1
    integer          :: ldda1
    magma_tally3_devptr_t   :: dA2
    integer          :: ldda2
    magma_tally3_devptr_t   :: dL1
    integer          :: lddl1
    magma_tally3_devptr_t   :: dL2
    integer          :: lddl2
    integer          :: ipiv(*)
    integer          :: info
end subroutine magma_tally3f_zssssm_gpu

subroutine magma_tally3f_ztrtri_gpu( uplo, diag, n, dA, ldda, info )
    character        :: uplo
    character        :: diag
    integer          :: n
    magma_tally3_devptr_t   :: dA
    integer          :: ldda
    integer          :: info
end subroutine magma_tally3f_ztrtri_gpu

subroutine magma_tally3f_zungqr_gpu( m, n, k, dA, ldda, tau, dT, nb, info )
    integer          :: m
    integer          :: n
    integer          :: k
    magma_tally3_devptr_t   :: dA
    integer          :: ldda
    complex*16       :: tau(*)
    magma_tally3_devptr_t   :: dT
    integer          :: nb
    integer          :: info
end subroutine magma_tally3f_zungqr_gpu

subroutine magma_tally3f_zunmql2_gpu( side, trans, m, n, k, dA, ldda, tau, dC, lddc, wA, ldwa,  &
        info )
    character        :: side
    character        :: trans
    integer          :: m
    integer          :: n
    integer          :: k
    magma_tally3_devptr_t   :: dA
    integer          :: ldda
    complex*16       :: tau(*)
    magma_tally3_devptr_t   :: dC
    integer          :: lddc
    complex*16       :: wA(*)
    integer          :: ldwa
    integer          :: info
end subroutine magma_tally3f_zunmql2_gpu

subroutine magma_tally3f_zunmqr_gpu( side, trans, m, n, k, dA, ldda, tau, dC, lddc, hwork,  &
        lwork, dT, nb, info )
    character        :: side
    character        :: trans
    integer          :: m
    integer          :: n
    integer          :: k
    magma_tally3_devptr_t   :: dA
    integer          :: ldda
    complex*16       :: tau(*)
    magma_tally3_devptr_t   :: dC
    integer          :: lddc
    complex*16       :: hwork(*)
    integer          :: lwork
    magma_tally3_devptr_t   :: dT
    integer          :: nb
    integer          :: info
end subroutine magma_tally3f_zunmqr_gpu

subroutine magma_tally3f_zunmqr2_gpu( side, trans, m, n, k, dA, ldda, tau, dC, lddc, wA, ldwa,  &
        info )
    character        :: side
    character        :: trans
    integer          :: m
    integer          :: n
    integer          :: k
    magma_tally3_devptr_t   :: dA
    integer          :: ldda
    complex*16       :: tau(*)
    magma_tally3_devptr_t   :: dC
    integer          :: lddc
    complex*16       :: wA(*)
    integer          :: ldwa
    integer          :: info
end subroutine magma_tally3f_zunmqr2_gpu

subroutine magma_tally3f_zunmtr_gpu( side, uplo, trans, m, n, dA, ldda, tau, dC, lddc, wA, ldwa,  &
        info )
    character        :: side
    character        :: uplo
    character        :: trans
    integer          :: m
    integer          :: n
    magma_tally3_devptr_t   :: dA
    integer          :: ldda
    complex*16       :: tau(*)
    magma_tally3_devptr_t   :: dC
    integer          :: lddc
    complex*16       :: wA(*)
    integer          :: ldwa
    integer          :: info
end subroutine magma_tally3f_zunmtr_gpu

subroutine magma_tally3f_znan_inf( uplo, m, n, A, lda, cnt_nan, cnt_inf )
    character        :: uplo
    integer          :: m
    integer          :: n
    complex*16       :: A(*)
    integer          :: lda
    integer          :: cnt_nan(*)
    integer          :: cnt_inf(*)
end subroutine magma_tally3f_znan_inf

subroutine magma_tally3f_znan_inf_gpu( uplo, m, n, dA, ldda, cnt_nan, cnt_inf )
    character        :: uplo
    integer          :: m
    integer          :: n
    magma_tally3_devptr_t   :: dA
    integer          :: ldda
    integer          :: cnt_nan(*)
    integer          :: cnt_inf(*)
end subroutine magma_tally3f_znan_inf_gpu

subroutine magma_tally3f_zprint( m, n, A, lda )
    integer          :: m
    integer          :: n
    complex*16       :: A(*)
    integer          :: lda
end subroutine magma_tally3f_zprint

subroutine magma_tally3f_zprint_gpu( m, n, dA, ldda )
    integer          :: m
    integer          :: n
    magma_tally3_devptr_t   :: dA
    integer          :: ldda
end subroutine magma_tally3f_zprint_gpu

end interface

!---- Fortran-only subroutines (see ../tools/fortran_wrappers.pl to edit) ----
contains

subroutine magma_tally3f_zoff1d( ptrNew, ptrOld, inc, i)
    magma_tally3_devptr_t   :: ptrNew
    magma_tally3_devptr_t   :: ptrOld
    integer          :: inc, i

    ptrNew = ptrOld + (i-1) * inc * sizeof_complex_16
end subroutine magma_tally3f_zoff1d

subroutine magma_tally3f_zoff2d( ptrNew, ptrOld, lda, i, j)
    magma_tally3_devptr_t   :: ptrNew
    magma_tally3_devptr_t   :: ptrOld
    integer          :: lda, i, j

    ptrNew = ptrOld + ((j-1) * lda + (i-1)) * sizeof_complex_16
end subroutine magma_tally3f_zoff2d

end module magma_tally3_zfortran
