/*******************************************************************************
 *  This file is AUTOMATICALLY GENERATED by:
 *  ../tools/fortran_wrappers.pl ../include/magma_minproduct_c.i
 *  Do not edit.
 ******************************************************************************/

#include <stdint.h>  // for uintptr_t

#include "magma_minproduct.h"
#include "magma_minproduct_mangling.h"

/*
 * typedef comming from fortran.h file provided in CUDADIR/src directory
 * it will probably change with future release of CUDA when they use 64 bit addresses
 */
typedef size_t devptr_t;

#ifdef PGI_FORTRAN
    #define magma_minproduct_idevptr(ptr_) ((int*)               (ptr_))
    #define magma_minproduct_zdevptr(ptr_) ((magma_minproductDoubleComplex*)(ptr_))
    #ifndef magma_minproduct_cdevptr
    #define magma_minproduct_cdevptr(ptr_) ((magma_minproductFloatComplex*) (ptr_))
    #endif
    #ifndef magma_minproduct_ddevptr
    #define magma_minproduct_ddevptr(ptr_) ((double*)            (ptr_))
    #endif
    #ifndef magma_minproduct_sdevptr
    #define magma_minproduct_sdevptr(ptr_) ((float*)             (ptr_))
    #endif
#else
    #define magma_minproduct_idevptr(ptr_) ((int*)               (uintptr_t)(*(ptr_)))
    #define magma_minproduct_zdevptr(ptr_) ((magma_minproductDoubleComplex*)(uintptr_t)(*(ptr_)))
    #ifndef magma_minproduct_cdevptr
    #define magma_minproduct_cdevptr(ptr_) ((magma_minproductFloatComplex*) (uintptr_t)(*(ptr_)))
    #endif
    #ifndef magma_minproduct_ddevptr
    #define magma_minproduct_ddevptr(ptr_) ((double*)            (uintptr_t)(*(ptr_)))
    #endif
    #ifndef magma_minproduct_sdevptr
    #define magma_minproduct_sdevptr(ptr_) ((float*)             (uintptr_t)(*(ptr_)))
    #endif
#endif

#ifdef __cplusplus
extern "C" {
#endif

#define magma_minproductf_get_cpotrf_nb FORTRAN_NAME( magma_minproductf_get_cpotrf_nb, MAGMA_minproductF_GET_CPOTRF_NB )
magma_minproduct_int_t magma_minproductf_get_cpotrf_nb( magma_minproduct_int_t *m )
{
    return magma_minproduct_get_cpotrf_nb( *m );
}

#define magma_minproductf_get_cgetrf_nb FORTRAN_NAME( magma_minproductf_get_cgetrf_nb, MAGMA_minproductF_GET_CGETRF_NB )
magma_minproduct_int_t magma_minproductf_get_cgetrf_nb( magma_minproduct_int_t *m )
{
    return magma_minproduct_get_cgetrf_nb( *m );
}

#define magma_minproductf_get_cgetri_nb FORTRAN_NAME( magma_minproductf_get_cgetri_nb, MAGMA_minproductF_GET_CGETRI_NB )
magma_minproduct_int_t magma_minproductf_get_cgetri_nb( magma_minproduct_int_t *m )
{
    return magma_minproduct_get_cgetri_nb( *m );
}

#define magma_minproductf_get_cgeqp3_nb FORTRAN_NAME( magma_minproductf_get_cgeqp3_nb, MAGMA_minproductF_GET_CGEQP3_NB )
magma_minproduct_int_t magma_minproductf_get_cgeqp3_nb( magma_minproduct_int_t *m )
{
    return magma_minproduct_get_cgeqp3_nb( *m );
}

#define magma_minproductf_get_cgeqrf_nb FORTRAN_NAME( magma_minproductf_get_cgeqrf_nb, MAGMA_minproductF_GET_CGEQRF_NB )
magma_minproduct_int_t magma_minproductf_get_cgeqrf_nb( magma_minproduct_int_t *m )
{
    return magma_minproduct_get_cgeqrf_nb( *m );
}

#define magma_minproductf_get_cgeqlf_nb FORTRAN_NAME( magma_minproductf_get_cgeqlf_nb, MAGMA_minproductF_GET_CGEQLF_NB )
magma_minproduct_int_t magma_minproductf_get_cgeqlf_nb( magma_minproduct_int_t *m )
{
    return magma_minproduct_get_cgeqlf_nb( *m );
}

#define magma_minproductf_get_cgehrd_nb FORTRAN_NAME( magma_minproductf_get_cgehrd_nb, MAGMA_minproductF_GET_CGEHRD_NB )
magma_minproduct_int_t magma_minproductf_get_cgehrd_nb( magma_minproduct_int_t *m )
{
    return magma_minproduct_get_cgehrd_nb( *m );
}

#define magma_minproductf_get_chetrd_nb FORTRAN_NAME( magma_minproductf_get_chetrd_nb, MAGMA_minproductF_GET_CHETRD_NB )
magma_minproduct_int_t magma_minproductf_get_chetrd_nb( magma_minproduct_int_t *m )
{
    return magma_minproduct_get_chetrd_nb( *m );
}

#define magma_minproductf_get_chetrf_nb FORTRAN_NAME( magma_minproductf_get_chetrf_nb, MAGMA_minproductF_GET_CHETRF_NB )
magma_minproduct_int_t magma_minproductf_get_chetrf_nb( magma_minproduct_int_t *m )
{
    return magma_minproduct_get_chetrf_nb( *m );
}

#define magma_minproductf_get_chetrf_nopiv_nb FORTRAN_NAME( magma_minproductf_get_chetrf_nopiv_nb, MAGMA_minproductF_GET_CHETRF_NOPIV_NB )
magma_minproduct_int_t magma_minproductf_get_chetrf_nopiv_nb( magma_minproduct_int_t *m )
{
    return magma_minproduct_get_chetrf_nopiv_nb( *m );
}

#define magma_minproductf_get_cgelqf_nb FORTRAN_NAME( magma_minproductf_get_cgelqf_nb, MAGMA_minproductF_GET_CGELQF_NB )
magma_minproduct_int_t magma_minproductf_get_cgelqf_nb( magma_minproduct_int_t *m )
{
    return magma_minproduct_get_cgelqf_nb( *m );
}

#define magma_minproductf_get_cgebrd_nb FORTRAN_NAME( magma_minproductf_get_cgebrd_nb, MAGMA_minproductF_GET_CGEBRD_NB )
magma_minproduct_int_t magma_minproductf_get_cgebrd_nb( magma_minproduct_int_t *m )
{
    return magma_minproduct_get_cgebrd_nb( *m );
}

#define magma_minproductf_get_chegst_nb FORTRAN_NAME( magma_minproductf_get_chegst_nb, MAGMA_minproductF_GET_CHEGST_NB )
magma_minproduct_int_t magma_minproductf_get_chegst_nb( magma_minproduct_int_t *m )
{
    return magma_minproduct_get_chegst_nb( *m );
}

#define magma_minproductf_get_cgesvd_nb FORTRAN_NAME( magma_minproductf_get_cgesvd_nb, MAGMA_minproductF_GET_CGESVD_NB )
magma_minproduct_int_t magma_minproductf_get_cgesvd_nb( magma_minproduct_int_t *m )
{
    return magma_minproduct_get_cgesvd_nb( *m );
}

#define magma_minproductf_get_chegst_nb_m FORTRAN_NAME( magma_minproductf_get_chegst_nb_m, MAGMA_minproductF_GET_CHEGST_NB_M )
magma_minproduct_int_t magma_minproductf_get_chegst_nb_m( magma_minproduct_int_t *m )
{
    return magma_minproduct_get_chegst_nb_m( *m );
}

#define magma_minproductf_get_cbulge_nb FORTRAN_NAME( magma_minproductf_get_cbulge_nb, MAGMA_minproductF_GET_CBULGE_NB )
void magma_minproductf_get_cbulge_nb(
    magma_minproduct_int_t *m, magma_minproduct_int_t *nbthreads )
{
    magma_minproduct_get_cbulge_nb(
        *m, *nbthreads );
}

#define magma_minproductf_cbulge_get_Vblksiz FORTRAN_NAME( magma_minproductf_cbulge_get_Vblksiz, MAGMA_minproductF_CBULGE_GET_VBLKSIZ )
void magma_minproductf_cbulge_get_Vblksiz(
    magma_minproduct_int_t *m, magma_minproduct_int_t *nb, magma_minproduct_int_t *nbthreads )
{
    magma_minproduct_cbulge_get_Vblksiz(
        *m, *nb, *nbthreads );
}

#define magma_minproductf_get_cbulge_gcperf FORTRAN_NAME( magma_minproductf_get_cbulge_gcperf, MAGMA_minproductF_GET_CBULGE_GCPERF )
void magma_minproductf_get_cbulge_gcperf(
     )
{
    magma_minproduct_get_cbulge_gcperf(
         );
}

#define magma_minproductf_cgebrd FORTRAN_NAME( magma_minproductf_cgebrd, MAGMA_minproductF_CGEBRD )
void magma_minproductf_cgebrd(
    magma_minproduct_int_t *m, magma_minproduct_int_t *n,
    magma_minproductFloatComplex *A, magma_minproduct_int_t *lda,
    float *d,
    float *e,
    magma_minproductFloatComplex *tauq,
    magma_minproductFloatComplex *taup,
    magma_minproductFloatComplex *work, magma_minproduct_int_t *lwork,
    magma_minproduct_int_t *info )
{
    magma_minproduct_cgebrd(
        *m, *n,
        A, *lda,
        d,
        e,
        tauq,
        taup,
        work, *lwork,
        info );
}

#define magma_minproductf_cgeev FORTRAN_NAME( magma_minproductf_cgeev, MAGMA_minproductF_CGEEV )
void magma_minproductf_cgeev(
    const char* jobvl, const char* jobvr, magma_minproduct_int_t *n,
    magma_minproductFloatComplex *A, magma_minproduct_int_t *lda,
    magma_minproductFloatComplex *w,
    magma_minproductFloatComplex *VL, magma_minproduct_int_t *ldvl,
    magma_minproductFloatComplex *VR, magma_minproduct_int_t *ldvr,
    magma_minproductFloatComplex *work, magma_minproduct_int_t *lwork,
    float *rwork,
    magma_minproduct_int_t *info )
{
    magma_minproduct_cgeev(
        magma_minproduct_vec_const(*jobvl), magma_minproduct_vec_const(*jobvr), *n,
        A, *lda,
        w,
        VL, *ldvl,
        VR, *ldvr,
        work, *lwork,
        rwork,
        info );
}

#define magma_minproductf_cgehrd FORTRAN_NAME( magma_minproductf_cgehrd, MAGMA_minproductF_CGEHRD )
void magma_minproductf_cgehrd(
    magma_minproduct_int_t *n, magma_minproduct_int_t *ilo, magma_minproduct_int_t *ihi,
    magma_minproductFloatComplex *A, magma_minproduct_int_t *lda,
    magma_minproductFloatComplex *tau,
    magma_minproductFloatComplex *work, magma_minproduct_int_t *lwork,
    devptr_t *dT,
    magma_minproduct_int_t *info )
{
    magma_minproduct_cgehrd(
        *n, *ilo, *ihi,
        A, *lda,
        tau,
        work, *lwork,
        magma_minproduct_cdevptr(dT),
        info );
}

#define magma_minproductf_cgehrd2 FORTRAN_NAME( magma_minproductf_cgehrd2, MAGMA_minproductF_CGEHRD2 )
void magma_minproductf_cgehrd2(
    magma_minproduct_int_t *n, magma_minproduct_int_t *ilo, magma_minproduct_int_t *ihi,
    magma_minproductFloatComplex *A, magma_minproduct_int_t *lda,
    magma_minproductFloatComplex *tau,
    magma_minproductFloatComplex *work, magma_minproduct_int_t *lwork,
    magma_minproduct_int_t *info )
{
    magma_minproduct_cgehrd2(
        *n, *ilo, *ihi,
        A, *lda,
        tau,
        work, *lwork,
        info );
}

#define magma_minproductf_cgelqf FORTRAN_NAME( magma_minproductf_cgelqf, MAGMA_minproductF_CGELQF )
void magma_minproductf_cgelqf(
    magma_minproduct_int_t *m, magma_minproduct_int_t *n,
    magma_minproductFloatComplex *A, magma_minproduct_int_t *lda,
    magma_minproductFloatComplex *tau,
    magma_minproductFloatComplex *work, magma_minproduct_int_t *lwork,
    magma_minproduct_int_t *info )
{
    magma_minproduct_cgelqf(
        *m, *n,
        A, *lda,
        tau,
        work, *lwork,
        info );
}

#define magma_minproductf_cgeqlf FORTRAN_NAME( magma_minproductf_cgeqlf, MAGMA_minproductF_CGEQLF )
void magma_minproductf_cgeqlf(
    magma_minproduct_int_t *m, magma_minproduct_int_t *n,
    magma_minproductFloatComplex *A, magma_minproduct_int_t *lda,
    magma_minproductFloatComplex *tau,
    magma_minproductFloatComplex *work, magma_minproduct_int_t *lwork,
    magma_minproduct_int_t *info )
{
    magma_minproduct_cgeqlf(
        *m, *n,
        A, *lda,
        tau,
        work, *lwork,
        info );
}

#define magma_minproductf_cgeqp3 FORTRAN_NAME( magma_minproductf_cgeqp3, MAGMA_minproductF_CGEQP3 )
void magma_minproductf_cgeqp3(
    magma_minproduct_int_t *m, magma_minproduct_int_t *n,
    magma_minproductFloatComplex *A, magma_minproduct_int_t *lda,
    magma_minproduct_int_t *jpvt,
    magma_minproductFloatComplex *tau,
    magma_minproductFloatComplex *work, magma_minproduct_int_t *lwork,
    float *rwork,
    magma_minproduct_int_t *info )
{
    magma_minproduct_cgeqp3(
        *m, *n,
        A, *lda,
        jpvt,
        tau,
        work, *lwork,
        rwork,
        info );
}

#define magma_minproductf_cgeqrf FORTRAN_NAME( magma_minproductf_cgeqrf, MAGMA_minproductF_CGEQRF )
void magma_minproductf_cgeqrf(
    magma_minproduct_int_t *m, magma_minproduct_int_t *n,
    magma_minproductFloatComplex *A, magma_minproduct_int_t *lda,
    magma_minproductFloatComplex *tau,
    magma_minproductFloatComplex *work, magma_minproduct_int_t *lwork,
    magma_minproduct_int_t *info )
{
    magma_minproduct_cgeqrf(
        *m, *n,
        A, *lda,
        tau,
        work, *lwork,
        info );
}

#define magma_minproductf_cgeqrf_ooc FORTRAN_NAME( magma_minproductf_cgeqrf_ooc, MAGMA_minproductF_CGEQRF_OOC )
void magma_minproductf_cgeqrf_ooc(
    magma_minproduct_int_t *m, magma_minproduct_int_t *n,
    magma_minproductFloatComplex *A, magma_minproduct_int_t *lda,
    magma_minproductFloatComplex *tau,
    magma_minproductFloatComplex *work, magma_minproduct_int_t *lwork,
    magma_minproduct_int_t *info )
{
    magma_minproduct_cgeqrf_ooc(
        *m, *n,
        A, *lda,
        tau,
        work, *lwork,
        info );
}

#define magma_minproductf_cgeqrf4 FORTRAN_NAME( magma_minproductf_cgeqrf4, MAGMA_minproductF_CGEQRF4 )
void magma_minproductf_cgeqrf4(
    magma_minproduct_int_t *ngpu, magma_minproduct_int_t *m, magma_minproduct_int_t *n,
    magma_minproductFloatComplex *A, magma_minproduct_int_t *lda,
    magma_minproductFloatComplex *tau,
    magma_minproductFloatComplex *work, magma_minproduct_int_t *lwork,
    magma_minproduct_int_t *info )
{
    magma_minproduct_cgeqrf4(
        *ngpu, *m, *n,
        A, *lda,
        tau,
        work, *lwork,
        info );
}

#define magma_minproductf_cgesdd FORTRAN_NAME( magma_minproductf_cgesdd, MAGMA_minproductF_CGESDD )
void magma_minproductf_cgesdd(
    const char* jobz, magma_minproduct_int_t *m, magma_minproduct_int_t *n,
    magma_minproductFloatComplex *A, magma_minproduct_int_t *lda,
    float *s,
    magma_minproductFloatComplex *U, magma_minproduct_int_t *ldu,
    magma_minproductFloatComplex *VT, magma_minproduct_int_t *ldvt,
    magma_minproductFloatComplex *work, magma_minproduct_int_t *lwork,
    float *rwork,
    magma_minproduct_int_t *iwork,
    magma_minproduct_int_t *info )
{
    magma_minproduct_cgesdd(
        magma_minproduct_vec_const(*jobz), *m, *n,
        A, *lda,
        s,
        U, *ldu,
        VT, *ldvt,
        work, *lwork,
        rwork,
        iwork,
        info );
}

#define magma_minproductf_cgesv FORTRAN_NAME( magma_minproductf_cgesv, MAGMA_minproductF_CGESV )
void magma_minproductf_cgesv(
    magma_minproduct_int_t *n, magma_minproduct_int_t *nrhs,
    magma_minproductFloatComplex *A, magma_minproduct_int_t *lda,
    magma_minproduct_int_t *ipiv,
    magma_minproductFloatComplex *B, magma_minproduct_int_t *ldb,
    magma_minproduct_int_t *info )
{
    magma_minproduct_cgesv(
        *n, *nrhs,
        A, *lda,
        ipiv,
        B, *ldb,
        info );
}

#define magma_minproductf_cgesv_rbt FORTRAN_NAME( magma_minproductf_cgesv_rbt, MAGMA_minproductF_CGESV_RBT )
void magma_minproductf_cgesv_rbt(
    const char* ref, magma_minproduct_int_t *n, magma_minproduct_int_t *nrhs,
    magma_minproductFloatComplex *A, magma_minproduct_int_t *lda,
    magma_minproductFloatComplex *B, magma_minproduct_int_t *ldb,
    magma_minproduct_int_t *info )
{
    magma_minproduct_cgesv_rbt(
        magma_minproduct_bool_const(*ref), *n, *nrhs,
        A, *lda,
        B, *ldb,
        info );
}

#define magma_minproductf_cgesvd FORTRAN_NAME( magma_minproductf_cgesvd, MAGMA_minproductF_CGESVD )
void magma_minproductf_cgesvd(
    const char* jobu, const char* jobvt, magma_minproduct_int_t *m, magma_minproduct_int_t *n,
    magma_minproductFloatComplex *A, magma_minproduct_int_t *lda,
    float *s,
    magma_minproductFloatComplex *U, magma_minproduct_int_t *ldu,
    magma_minproductFloatComplex *VT, magma_minproduct_int_t *ldvt,
    magma_minproductFloatComplex *work, magma_minproduct_int_t *lwork,
    float *rwork,
    magma_minproduct_int_t *info )
{
    magma_minproduct_cgesvd(
        magma_minproduct_vec_const(*jobu), magma_minproduct_vec_const(*jobvt), *m, *n,
        A, *lda,
        s,
        U, *ldu,
        VT, *ldvt,
        work, *lwork,
        rwork,
        info );
}

#define magma_minproductf_cgetf2_nopiv FORTRAN_NAME( magma_minproductf_cgetf2_nopiv, MAGMA_minproductF_CGETF2_NOPIV )
void magma_minproductf_cgetf2_nopiv(
    magma_minproduct_int_t *m, magma_minproduct_int_t *n,
    magma_minproductFloatComplex *A, magma_minproduct_int_t *lda,
    magma_minproduct_int_t *info )
{
    magma_minproduct_cgetf2_nopiv(
        *m, *n,
        A, *lda,
        info );
}

#define magma_minproductf_cgetrf FORTRAN_NAME( magma_minproductf_cgetrf, MAGMA_minproductF_CGETRF )
void magma_minproductf_cgetrf(
    magma_minproduct_int_t *m, magma_minproduct_int_t *n,
    magma_minproductFloatComplex *A, magma_minproduct_int_t *lda,
    magma_minproduct_int_t *ipiv,
    magma_minproduct_int_t *info )
{
    magma_minproduct_cgetrf(
        *m, *n,
        A, *lda,
        ipiv,
        info );
}

#define magma_minproductf_cgetrf_nopiv FORTRAN_NAME( magma_minproductf_cgetrf_nopiv, MAGMA_minproductF_CGETRF_NOPIV )
void magma_minproductf_cgetrf_nopiv(
    magma_minproduct_int_t *m, magma_minproduct_int_t *n,
    magma_minproductFloatComplex *A, magma_minproduct_int_t *lda,
    magma_minproduct_int_t *info )
{
    magma_minproduct_cgetrf_nopiv(
        *m, *n,
        A, *lda,
        info );
}

#define magma_minproductf_cgetrf_piv FORTRAN_NAME( magma_minproductf_cgetrf_piv, MAGMA_minproductF_CGETRF_PIV )
void magma_minproductf_cgetrf_piv(
    magma_minproduct_int_t *m, magma_minproduct_int_t *n, magma_minproduct_int_t *NB,
    magma_minproductFloatComplex *A, magma_minproduct_int_t *lda,
    magma_minproduct_int_t *ipiv,
    magma_minproduct_int_t *info )
{
    magma_minproduct_cgetrf_piv(
        *m, *n, *NB,
        A, *lda,
        ipiv,
        info );
}

#define magma_minproductf_cheevd FORTRAN_NAME( magma_minproductf_cheevd, MAGMA_minproductF_CHEEVD )
void magma_minproductf_cheevd(
    const char* jobz, const char* uplo, magma_minproduct_int_t *n,
    magma_minproductFloatComplex *A, magma_minproduct_int_t *lda,
    float *w,
    magma_minproductFloatComplex *work, magma_minproduct_int_t *lwork,
    float *rwork, magma_minproduct_int_t *lrwork,
    magma_minproduct_int_t *iwork, magma_minproduct_int_t *liwork,
    magma_minproduct_int_t *info )
{
    magma_minproduct_cheevd(
        magma_minproduct_vec_const(*jobz), magma_minproduct_uplo_const(*uplo), *n,
        A, *lda,
        w,
        work, *lwork,
        rwork, *lrwork,
        iwork, *liwork,
        info );
}

#define magma_minproductf_cheevdx FORTRAN_NAME( magma_minproductf_cheevdx, MAGMA_minproductF_CHEEVDX )
void magma_minproductf_cheevdx(
    const char* jobz, const char* range, const char* uplo, magma_minproduct_int_t *n,
    magma_minproductFloatComplex *A, magma_minproduct_int_t *lda, float *vl, float *vu, magma_minproduct_int_t *il, magma_minproduct_int_t *iu,
    magma_minproduct_int_t *m,
    float *w,
    magma_minproductFloatComplex *work, magma_minproduct_int_t *lwork,
    float *rwork, magma_minproduct_int_t *lrwork,
    magma_minproduct_int_t *iwork, magma_minproduct_int_t *liwork,
    magma_minproduct_int_t *info )
{
    magma_minproduct_cheevdx(
        magma_minproduct_vec_const(*jobz), magma_minproduct_range_const(*range), magma_minproduct_uplo_const(*uplo), *n,
        A, *lda, *vl, *vu, *il, *iu,
        m,
        w,
        work, *lwork,
        rwork, *lrwork,
        iwork, *liwork,
        info );
}

#define magma_minproductf_cheevdx_2stage FORTRAN_NAME( magma_minproductf_cheevdx_2stage, MAGMA_minproductF_CHEEVDX_2STAGE )
void magma_minproductf_cheevdx_2stage(
    const char* jobz, const char* range, const char* uplo, magma_minproduct_int_t *n,
    magma_minproductFloatComplex *A, magma_minproduct_int_t *lda, float *vl, float *vu, magma_minproduct_int_t *il, magma_minproduct_int_t *iu,
    magma_minproduct_int_t *m,
    float *w,
    magma_minproductFloatComplex *work, magma_minproduct_int_t *lwork,
    float *rwork, magma_minproduct_int_t *lrwork,
    magma_minproduct_int_t *iwork, magma_minproduct_int_t *liwork,
    magma_minproduct_int_t *info )
{
    magma_minproduct_cheevdx_2stage(
        magma_minproduct_vec_const(*jobz), magma_minproduct_range_const(*range), magma_minproduct_uplo_const(*uplo), *n,
        A, *lda, *vl, *vu, *il, *iu,
        m,
        w,
        work, *lwork,
        rwork, *lrwork,
        iwork, *liwork,
        info );
}

#define magma_minproductf_cheevr FORTRAN_NAME( magma_minproductf_cheevr, MAGMA_minproductF_CHEEVR )
void magma_minproductf_cheevr(
    const char* jobz, const char* range, const char* uplo, magma_minproduct_int_t *n,
    magma_minproductFloatComplex *A, magma_minproduct_int_t *lda, float *vl, float *vu, magma_minproduct_int_t *il, magma_minproduct_int_t *iu, float *abstol,
    magma_minproduct_int_t *m,
    float *w,
    magma_minproductFloatComplex *Z, magma_minproduct_int_t *ldz,
    magma_minproduct_int_t *isuppz,
    magma_minproductFloatComplex *work, magma_minproduct_int_t *lwork,
    float *rwork, magma_minproduct_int_t *lrwork,
    magma_minproduct_int_t *iwork, magma_minproduct_int_t *liwork,
    magma_minproduct_int_t *info )
{
    magma_minproduct_cheevr(
        magma_minproduct_vec_const(*jobz), magma_minproduct_range_const(*range), magma_minproduct_uplo_const(*uplo), *n,
        A, *lda, *vl, *vu, *il, *iu, *abstol,
        m,
        w,
        Z, *ldz,
        isuppz,
        work, *lwork,
        rwork, *lrwork,
        iwork, *liwork,
        info );
}

#define magma_minproductf_cheevx FORTRAN_NAME( magma_minproductf_cheevx, MAGMA_minproductF_CHEEVX )
void magma_minproductf_cheevx(
    const char* jobz, const char* range, const char* uplo, magma_minproduct_int_t *n,
    magma_minproductFloatComplex *A, magma_minproduct_int_t *lda, float *vl, float *vu, magma_minproduct_int_t *il, magma_minproduct_int_t *iu, float *abstol,
    magma_minproduct_int_t *m,
    float *w,
    magma_minproductFloatComplex *Z, magma_minproduct_int_t *ldz,
    magma_minproductFloatComplex *work, magma_minproduct_int_t *lwork,
    float *rwork,
    magma_minproduct_int_t *iwork,
    magma_minproduct_int_t *ifail,
    magma_minproduct_int_t *info )
{
    magma_minproduct_cheevx(
        magma_minproduct_vec_const(*jobz), magma_minproduct_range_const(*range), magma_minproduct_uplo_const(*uplo), *n,
        A, *lda, *vl, *vu, *il, *iu, *abstol,
        m,
        w,
        Z, *ldz,
        work, *lwork,
        rwork,
        iwork,
        ifail,
        info );
}

#define magma_minproductf_chegst FORTRAN_NAME( magma_minproductf_chegst, MAGMA_minproductF_CHEGST )
void magma_minproductf_chegst(
    magma_minproduct_int_t *itype, const char* uplo, magma_minproduct_int_t *n,
    magma_minproductFloatComplex *A, magma_minproduct_int_t *lda,
    magma_minproductFloatComplex *B, magma_minproduct_int_t *ldb,
    magma_minproduct_int_t *info )
{
    magma_minproduct_chegst(
        *itype, magma_minproduct_uplo_const(*uplo), *n,
        A, *lda,
        B, *ldb,
        info );
}

#define magma_minproductf_chegvd FORTRAN_NAME( magma_minproductf_chegvd, MAGMA_minproductF_CHEGVD )
void magma_minproductf_chegvd(
    magma_minproduct_int_t *itype, const char* jobz, const char* uplo, magma_minproduct_int_t *n,
    magma_minproductFloatComplex *A, magma_minproduct_int_t *lda,
    magma_minproductFloatComplex *B, magma_minproduct_int_t *ldb,
    float *w,
    magma_minproductFloatComplex *work, magma_minproduct_int_t *lwork,
    float *rwork, magma_minproduct_int_t *lrwork,
    magma_minproduct_int_t *iwork, magma_minproduct_int_t *liwork,
    magma_minproduct_int_t *info )
{
    magma_minproduct_chegvd(
        *itype, magma_minproduct_vec_const(*jobz), magma_minproduct_uplo_const(*uplo), *n,
        A, *lda,
        B, *ldb,
        w,
        work, *lwork,
        rwork, *lrwork,
        iwork, *liwork,
        info );
}

#define magma_minproductf_chegvdx FORTRAN_NAME( magma_minproductf_chegvdx, MAGMA_minproductF_CHEGVDX )
void magma_minproductf_chegvdx(
    magma_minproduct_int_t *itype, const char* jobz, const char* range, const char* uplo, magma_minproduct_int_t *n,
    magma_minproductFloatComplex *A, magma_minproduct_int_t *lda,
    magma_minproductFloatComplex *B, magma_minproduct_int_t *ldb, float *vl, float *vu, magma_minproduct_int_t *il, magma_minproduct_int_t *iu,
    magma_minproduct_int_t *m,
    float *w,
    magma_minproductFloatComplex *work, magma_minproduct_int_t *lwork,
    float *rwork, magma_minproduct_int_t *lrwork,
    magma_minproduct_int_t *iwork, magma_minproduct_int_t *liwork,
    magma_minproduct_int_t *info )
{
    magma_minproduct_chegvdx(
        *itype, magma_minproduct_vec_const(*jobz), magma_minproduct_range_const(*range), magma_minproduct_uplo_const(*uplo), *n,
        A, *lda,
        B, *ldb, *vl, *vu, *il, *iu,
        m,
        w,
        work, *lwork,
        rwork, *lrwork,
        iwork, *liwork,
        info );
}

#define magma_minproductf_chegvdx_2stage FORTRAN_NAME( magma_minproductf_chegvdx_2stage, MAGMA_minproductF_CHEGVDX_2STAGE )
void magma_minproductf_chegvdx_2stage(
    magma_minproduct_int_t *itype, const char* jobz, const char* range, const char* uplo, magma_minproduct_int_t *n,
    magma_minproductFloatComplex *A, magma_minproduct_int_t *lda,
    magma_minproductFloatComplex *B, magma_minproduct_int_t *ldb, float *vl, float *vu, magma_minproduct_int_t *il, magma_minproduct_int_t *iu,
    magma_minproduct_int_t *m,
    float *w,
    magma_minproductFloatComplex *work, magma_minproduct_int_t *lwork,
    float *rwork, magma_minproduct_int_t *lrwork,
    magma_minproduct_int_t *iwork, magma_minproduct_int_t *liwork,
    magma_minproduct_int_t *info )
{
    magma_minproduct_chegvdx_2stage(
        *itype, magma_minproduct_vec_const(*jobz), magma_minproduct_range_const(*range), magma_minproduct_uplo_const(*uplo), *n,
        A, *lda,
        B, *ldb, *vl, *vu, *il, *iu,
        m,
        w,
        work, *lwork,
        rwork, *lrwork,
        iwork, *liwork,
        info );
}

#define magma_minproductf_chegvr FORTRAN_NAME( magma_minproductf_chegvr, MAGMA_minproductF_CHEGVR )
void magma_minproductf_chegvr(
    magma_minproduct_int_t *itype, const char* jobz, const char* range, const char* uplo, magma_minproduct_int_t *n,
    magma_minproductFloatComplex *A, magma_minproduct_int_t *lda,
    magma_minproductFloatComplex *B, magma_minproduct_int_t *ldb, float *vl, float *vu, magma_minproduct_int_t *il, magma_minproduct_int_t *iu, float *abstol,
    magma_minproduct_int_t *m,
    float *w,
    magma_minproductFloatComplex *Z, magma_minproduct_int_t *ldz,
    magma_minproduct_int_t *isuppz,
    magma_minproductFloatComplex *work, magma_minproduct_int_t *lwork,
    float *rwork, magma_minproduct_int_t *lrwork,
    magma_minproduct_int_t *iwork, magma_minproduct_int_t *liwork,
    magma_minproduct_int_t *info )
{
    magma_minproduct_chegvr(
        *itype, magma_minproduct_vec_const(*jobz), magma_minproduct_range_const(*range), magma_minproduct_uplo_const(*uplo), *n,
        A, *lda,
        B, *ldb, *vl, *vu, *il, *iu, *abstol,
        m,
        w,
        Z, *ldz,
        isuppz,
        work, *lwork,
        rwork, *lrwork,
        iwork, *liwork,
        info );
}

#define magma_minproductf_chegvx FORTRAN_NAME( magma_minproductf_chegvx, MAGMA_minproductF_CHEGVX )
void magma_minproductf_chegvx(
    magma_minproduct_int_t *itype, const char* jobz, const char* range, const char* uplo, magma_minproduct_int_t *n,
    magma_minproductFloatComplex *A, magma_minproduct_int_t *lda,
    magma_minproductFloatComplex *B, magma_minproduct_int_t *ldb, float *vl, float *vu, magma_minproduct_int_t *il, magma_minproduct_int_t *iu, float *abstol,
    magma_minproduct_int_t *m,
    float *w,
    magma_minproductFloatComplex *Z, magma_minproduct_int_t *ldz,
    magma_minproductFloatComplex *work, magma_minproduct_int_t *lwork,
    float *rwork,
    magma_minproduct_int_t *iwork,
    magma_minproduct_int_t *ifail,
    magma_minproduct_int_t *info )
{
    magma_minproduct_chegvx(
        *itype, magma_minproduct_vec_const(*jobz), magma_minproduct_range_const(*range), magma_minproduct_uplo_const(*uplo), *n,
        A, *lda,
        B, *ldb, *vl, *vu, *il, *iu, *abstol,
        m,
        w,
        Z, *ldz,
        work, *lwork,
        rwork,
        iwork,
        ifail,
        info );
}

#define magma_minproductf_chesv FORTRAN_NAME( magma_minproductf_chesv, MAGMA_minproductF_CHESV )
void magma_minproductf_chesv(
    const char* uplo, magma_minproduct_int_t *n, magma_minproduct_int_t *nrhs,
    magma_minproductFloatComplex *A, magma_minproduct_int_t *lda,
    magma_minproduct_int_t *ipiv,
    magma_minproductFloatComplex *B, magma_minproduct_int_t *ldb,
    magma_minproduct_int_t *info )
{
    magma_minproduct_chesv(
        magma_minproduct_uplo_const(*uplo), *n, *nrhs,
        A, *lda,
        ipiv,
        B, *ldb,
        info );
}

#define magma_minproductf_chetrd FORTRAN_NAME( magma_minproductf_chetrd, MAGMA_minproductF_CHETRD )
void magma_minproductf_chetrd(
    const char* uplo, magma_minproduct_int_t *n,
    magma_minproductFloatComplex *A, magma_minproduct_int_t *lda,
    float *d,
    float *e,
    magma_minproductFloatComplex *tau,
    magma_minproductFloatComplex *work, magma_minproduct_int_t *lwork,
    magma_minproduct_int_t *info )
{
    magma_minproduct_chetrd(
        magma_minproduct_uplo_const(*uplo), *n,
        A, *lda,
        d,
        e,
        tau,
        work, *lwork,
        info );
}

#define magma_minproductf_chetrf FORTRAN_NAME( magma_minproductf_chetrf, MAGMA_minproductF_CHETRF )
void magma_minproductf_chetrf(
    const char* uplo, magma_minproduct_int_t *n,
    magma_minproductFloatComplex *A, magma_minproduct_int_t *lda,
    magma_minproduct_int_t *ipiv,
    magma_minproduct_int_t *info )
{
    magma_minproduct_chetrf(
        magma_minproduct_uplo_const(*uplo), *n,
        A, *lda,
        ipiv,
        info );
}

#define magma_minproductf_chetrf_nopiv FORTRAN_NAME( magma_minproductf_chetrf_nopiv, MAGMA_minproductF_CHETRF_NOPIV )
void magma_minproductf_chetrf_nopiv(
    const char* uplo, magma_minproduct_int_t *n,
    magma_minproductFloatComplex *a, magma_minproduct_int_t *lda,
    magma_minproduct_int_t *info )
{
    magma_minproduct_chetrf_nopiv(
        magma_minproduct_uplo_const(*uplo), *n,
        a, *lda,
        info );
}

#define magma_minproductf_chetrd_hb2st FORTRAN_NAME( magma_minproductf_chetrd_hb2st, MAGMA_minproductF_CHETRD_HB2ST )
void magma_minproductf_chetrd_hb2st(
    const char* uplo, magma_minproduct_int_t *n, magma_minproduct_int_t *nb, magma_minproduct_int_t *Vblksiz,
    magma_minproductFloatComplex *A, magma_minproduct_int_t *lda,
    float *d,
    float *e,
    magma_minproductFloatComplex *V, magma_minproduct_int_t *ldv,
    magma_minproductFloatComplex *TAU, magma_minproduct_int_t *compT,
    magma_minproductFloatComplex *T, magma_minproduct_int_t *ldt )
{
    magma_minproduct_chetrd_hb2st(
        magma_minproduct_uplo_const(*uplo), *n, *nb, *Vblksiz,
        A, *lda,
        d,
        e,
        V, *ldv,
        TAU, *compT,
        T, *ldt );
}

#define magma_minproductf_chetrd_he2hb FORTRAN_NAME( magma_minproductf_chetrd_he2hb, MAGMA_minproductF_CHETRD_HE2HB )
void magma_minproductf_chetrd_he2hb(
    const char* uplo, magma_minproduct_int_t *n, magma_minproduct_int_t *nb,
    magma_minproductFloatComplex *A, magma_minproduct_int_t *lda,
    magma_minproductFloatComplex *tau,
    magma_minproductFloatComplex *work, magma_minproduct_int_t *lwork,
    devptr_t *dT,
    magma_minproduct_int_t *info )
{
    magma_minproduct_chetrd_he2hb(
        magma_minproduct_uplo_const(*uplo), *n, *nb,
        A, *lda,
        tau,
        work, *lwork,
        magma_minproduct_cdevptr(dT),
        info );
}

#define magma_minproductf_clatrsd FORTRAN_NAME( magma_minproductf_clatrsd, MAGMA_minproductF_CLATRSD )
void magma_minproductf_clatrsd(
    const char* uplo, const char* trans, const char* diag, const char* normin, magma_minproduct_int_t *n,
    const magma_minproductFloatComplex *A, magma_minproduct_int_t *lda, magma_minproductFloatComplex *lambda,
    magma_minproductFloatComplex *x,
    float *scale,
    float *cnorm,
    magma_minproduct_int_t *info )
{
    magma_minproduct_clatrsd(
        magma_minproduct_uplo_const(*uplo), magma_minproduct_trans_const(*trans), magma_minproduct_diag_const(*diag), magma_minproduct_bool_const(*normin), *n,
        A, *lda, *lambda,
        x,
        scale,
        cnorm,
        info );
}

#define magma_minproductf_clauum FORTRAN_NAME( magma_minproductf_clauum, MAGMA_minproductF_CLAUUM )
void magma_minproductf_clauum(
    const char* uplo, magma_minproduct_int_t *n,
    magma_minproductFloatComplex *A, magma_minproduct_int_t *lda,
    magma_minproduct_int_t *info )
{
    magma_minproduct_clauum(
        magma_minproduct_uplo_const(*uplo), *n,
        A, *lda,
        info );
}

#define magma_minproductf_cposv FORTRAN_NAME( magma_minproductf_cposv, MAGMA_minproductF_CPOSV )
void magma_minproductf_cposv(
    const char* uplo, magma_minproduct_int_t *n, magma_minproduct_int_t *nrhs,
    magma_minproductFloatComplex *A, magma_minproduct_int_t *lda,
    magma_minproductFloatComplex *B, magma_minproduct_int_t *ldb,
    magma_minproduct_int_t *info )
{
    magma_minproduct_cposv(
        magma_minproduct_uplo_const(*uplo), *n, *nrhs,
        A, *lda,
        B, *ldb,
        info );
}

#define magma_minproductf_cpotrf FORTRAN_NAME( magma_minproductf_cpotrf, MAGMA_minproductF_CPOTRF )
void magma_minproductf_cpotrf(
    const char* uplo, magma_minproduct_int_t *n,
    magma_minproductFloatComplex *A, magma_minproduct_int_t *lda,
    magma_minproduct_int_t *info )
{
    magma_minproduct_cpotrf(
        magma_minproduct_uplo_const(*uplo), *n,
        A, *lda,
        info );
}

#define magma_minproductf_cpotri FORTRAN_NAME( magma_minproductf_cpotri, MAGMA_minproductF_CPOTRI )
void magma_minproductf_cpotri(
    const char* uplo, magma_minproduct_int_t *n,
    magma_minproductFloatComplex *A, magma_minproduct_int_t *lda,
    magma_minproduct_int_t *info )
{
    magma_minproduct_cpotri(
        magma_minproduct_uplo_const(*uplo), *n,
        A, *lda,
        info );
}

#define magma_minproductf_cstedx FORTRAN_NAME( magma_minproductf_cstedx, MAGMA_minproductF_CSTEDX )
void magma_minproductf_cstedx(
    const char* range, magma_minproduct_int_t *n, float *vl, float *vu, magma_minproduct_int_t *il, magma_minproduct_int_t *iu,
    float *d,
    float *e,
    magma_minproductFloatComplex *Z, magma_minproduct_int_t *ldz,
    float *rwork, magma_minproduct_int_t *lrwork,
    magma_minproduct_int_t *iwork, magma_minproduct_int_t *liwork,
    devptr_t *dwork,
    magma_minproduct_int_t *info )
{
    magma_minproduct_cstedx(
        magma_minproduct_range_const(*range), *n, *vl, *vu, *il, *iu,
        d,
        e,
        Z, *ldz,
        rwork, *lrwork,
        iwork, *liwork,
        magma_minproduct_sdevptr(dwork),
        info );
}

#define magma_minproductf_ctrevc3 FORTRAN_NAME( magma_minproductf_ctrevc3, MAGMA_minproductF_CTREVC3 )
void magma_minproductf_ctrevc3(
    const char* side, const char* howmany,
    magma_minproduct_int_t *select, magma_minproduct_int_t *n,
    magma_minproductFloatComplex *T, magma_minproduct_int_t *ldt,
    magma_minproductFloatComplex *VL, magma_minproduct_int_t *ldvl,
    magma_minproductFloatComplex *VR, magma_minproduct_int_t *ldvr, magma_minproduct_int_t *mm,
    magma_minproduct_int_t *mout,
    magma_minproductFloatComplex *work, magma_minproduct_int_t *lwork,
    float *rwork,
    magma_minproduct_int_t *info )
{
    magma_minproduct_ctrevc3(
        magma_minproduct_side_const(*side), magma_minproduct_vec_const(*howmany),
        select, *n,
        T, *ldt,
        VL, *ldvl,
        VR, *ldvr, *mm,
        mout,
        work, *lwork,
        rwork,
        info );
}

#define magma_minproductf_ctrevc3_mt FORTRAN_NAME( magma_minproductf_ctrevc3_mt, MAGMA_minproductF_CTREVC3_MT )
void magma_minproductf_ctrevc3_mt(
    const char* side, const char* howmany,
    magma_minproduct_int_t *select, magma_minproduct_int_t *n,
    magma_minproductFloatComplex *T, magma_minproduct_int_t *ldt,
    magma_minproductFloatComplex *VL, magma_minproduct_int_t *ldvl,
    magma_minproductFloatComplex *VR, magma_minproduct_int_t *ldvr, magma_minproduct_int_t *mm,
    magma_minproduct_int_t *mout,
    magma_minproductFloatComplex *work, magma_minproduct_int_t *lwork,
    float *rwork,
    magma_minproduct_int_t *info )
{
    magma_minproduct_ctrevc3_mt(
        magma_minproduct_side_const(*side), magma_minproduct_vec_const(*howmany),
        select, *n,
        T, *ldt,
        VL, *ldvl,
        VR, *ldvr, *mm,
        mout,
        work, *lwork,
        rwork,
        info );
}

#define magma_minproductf_ctrtri FORTRAN_NAME( magma_minproductf_ctrtri, MAGMA_minproductF_CTRTRI )
void magma_minproductf_ctrtri(
    const char* uplo, const char* diag, magma_minproduct_int_t *n,
    magma_minproductFloatComplex *A, magma_minproduct_int_t *lda,
    magma_minproduct_int_t *info )
{
    magma_minproduct_ctrtri(
        magma_minproduct_uplo_const(*uplo), magma_minproduct_diag_const(*diag), *n,
        A, *lda,
        info );
}

#define magma_minproductf_cunghr FORTRAN_NAME( magma_minproductf_cunghr, MAGMA_minproductF_CUNGHR )
void magma_minproductf_cunghr(
    magma_minproduct_int_t *n, magma_minproduct_int_t *ilo, magma_minproduct_int_t *ihi,
    magma_minproductFloatComplex *A, magma_minproduct_int_t *lda,
    magma_minproductFloatComplex *tau,
    devptr_t *dT, magma_minproduct_int_t *nb,
    magma_minproduct_int_t *info )
{
    magma_minproduct_cunghr(
        *n, *ilo, *ihi,
        A, *lda,
        tau,
        magma_minproduct_cdevptr(dT), *nb,
        info );
}

#define magma_minproductf_cungqr FORTRAN_NAME( magma_minproductf_cungqr, MAGMA_minproductF_CUNGQR )
void magma_minproductf_cungqr(
    magma_minproduct_int_t *m, magma_minproduct_int_t *n, magma_minproduct_int_t *k,
    magma_minproductFloatComplex *A, magma_minproduct_int_t *lda,
    magma_minproductFloatComplex *tau,
    devptr_t *dT, magma_minproduct_int_t *nb,
    magma_minproduct_int_t *info )
{
    magma_minproduct_cungqr(
        *m, *n, *k,
        A, *lda,
        tau,
        magma_minproduct_cdevptr(dT), *nb,
        info );
}

#define magma_minproductf_cungqr2 FORTRAN_NAME( magma_minproductf_cungqr2, MAGMA_minproductF_CUNGQR2 )
void magma_minproductf_cungqr2(
    magma_minproduct_int_t *m, magma_minproduct_int_t *n, magma_minproduct_int_t *k,
    magma_minproductFloatComplex *A, magma_minproduct_int_t *lda,
    magma_minproductFloatComplex *tau,
    magma_minproduct_int_t *info )
{
    magma_minproduct_cungqr2(
        *m, *n, *k,
        A, *lda,
        tau,
        info );
}

#define magma_minproductf_cunmbr FORTRAN_NAME( magma_minproductf_cunmbr, MAGMA_minproductF_CUNMBR )
void magma_minproductf_cunmbr(
    const char* vect, const char* side, const char* trans, magma_minproduct_int_t *m, magma_minproduct_int_t *n, magma_minproduct_int_t *k,
    magma_minproductFloatComplex *A, magma_minproduct_int_t *lda,
    magma_minproductFloatComplex *tau,
    magma_minproductFloatComplex *C, magma_minproduct_int_t *ldc,
    magma_minproductFloatComplex *work, magma_minproduct_int_t *lwork,
    magma_minproduct_int_t *info )
{
    magma_minproduct_cunmbr(
        magma_minproduct_vect_const(*vect), magma_minproduct_side_const(*side), magma_minproduct_trans_const(*trans), *m, *n, *k,
        A, *lda,
        tau,
        C, *ldc,
        work, *lwork,
        info );
}

#define magma_minproductf_cunmlq FORTRAN_NAME( magma_minproductf_cunmlq, MAGMA_minproductF_CUNMLQ )
void magma_minproductf_cunmlq(
    const char* side, const char* trans, magma_minproduct_int_t *m, magma_minproduct_int_t *n, magma_minproduct_int_t *k,
    magma_minproductFloatComplex *A, magma_minproduct_int_t *lda,
    magma_minproductFloatComplex *tau,
    magma_minproductFloatComplex *C, magma_minproduct_int_t *ldc,
    magma_minproductFloatComplex *work, magma_minproduct_int_t *lwork,
    magma_minproduct_int_t *info )
{
    magma_minproduct_cunmlq(
        magma_minproduct_side_const(*side), magma_minproduct_trans_const(*trans), *m, *n, *k,
        A, *lda,
        tau,
        C, *ldc,
        work, *lwork,
        info );
}

#define magma_minproductf_cunmql FORTRAN_NAME( magma_minproductf_cunmql, MAGMA_minproductF_CUNMQL )
void magma_minproductf_cunmql(
    const char* side, const char* trans, magma_minproduct_int_t *m, magma_minproduct_int_t *n, magma_minproduct_int_t *k,
    magma_minproductFloatComplex *A, magma_minproduct_int_t *lda,
    magma_minproductFloatComplex *tau,
    magma_minproductFloatComplex *C, magma_minproduct_int_t *ldc,
    magma_minproductFloatComplex *work, magma_minproduct_int_t *lwork,
    magma_minproduct_int_t *info )
{
    magma_minproduct_cunmql(
        magma_minproduct_side_const(*side), magma_minproduct_trans_const(*trans), *m, *n, *k,
        A, *lda,
        tau,
        C, *ldc,
        work, *lwork,
        info );
}

#define magma_minproductf_cunmqr FORTRAN_NAME( magma_minproductf_cunmqr, MAGMA_minproductF_CUNMQR )
void magma_minproductf_cunmqr(
    const char* side, const char* trans, magma_minproduct_int_t *m, magma_minproduct_int_t *n, magma_minproduct_int_t *k,
    magma_minproductFloatComplex *A, magma_minproduct_int_t *lda,
    magma_minproductFloatComplex *tau,
    magma_minproductFloatComplex *C, magma_minproduct_int_t *ldc,
    magma_minproductFloatComplex *work, magma_minproduct_int_t *lwork,
    magma_minproduct_int_t *info )
{
    magma_minproduct_cunmqr(
        magma_minproduct_side_const(*side), magma_minproduct_trans_const(*trans), *m, *n, *k,
        A, *lda,
        tau,
        C, *ldc,
        work, *lwork,
        info );
}

#define magma_minproductf_cunmtr FORTRAN_NAME( magma_minproductf_cunmtr, MAGMA_minproductF_CUNMTR )
void magma_minproductf_cunmtr(
    const char* side, const char* uplo, const char* trans, magma_minproduct_int_t *m, magma_minproduct_int_t *n,
    magma_minproductFloatComplex *A, magma_minproduct_int_t *lda,
    magma_minproductFloatComplex *tau,
    magma_minproductFloatComplex *C, magma_minproduct_int_t *ldc,
    magma_minproductFloatComplex *work, magma_minproduct_int_t *lwork,
    magma_minproduct_int_t *info )
{
    magma_minproduct_cunmtr(
        magma_minproduct_side_const(*side), magma_minproduct_uplo_const(*uplo), magma_minproduct_trans_const(*trans), *m, *n,
        A, *lda,
        tau,
        C, *ldc,
        work, *lwork,
        info );
}

#define magma_minproductf_cgeev_m FORTRAN_NAME( magma_minproductf_cgeev_m, MAGMA_minproductF_CGEEV_M )
void magma_minproductf_cgeev_m(
    const char* jobvl, const char* jobvr, magma_minproduct_int_t *n,
    magma_minproductFloatComplex *A, magma_minproduct_int_t *lda,
    magma_minproductFloatComplex *w,
    magma_minproductFloatComplex *VL, magma_minproduct_int_t *ldvl,
    magma_minproductFloatComplex *VR, magma_minproduct_int_t *ldvr,
    magma_minproductFloatComplex *work, magma_minproduct_int_t *lwork,
    float *rwork,
    magma_minproduct_int_t *info )
{
    magma_minproduct_cgeev_m(
        magma_minproduct_vec_const(*jobvl), magma_minproduct_vec_const(*jobvr), *n,
        A, *lda,
        w,
        VL, *ldvl,
        VR, *ldvr,
        work, *lwork,
        rwork,
        info );
}

#define magma_minproductf_cgehrd_m FORTRAN_NAME( magma_minproductf_cgehrd_m, MAGMA_minproductF_CGEHRD_M )
void magma_minproductf_cgehrd_m(
    magma_minproduct_int_t *n, magma_minproduct_int_t *ilo, magma_minproduct_int_t *ihi,
    magma_minproductFloatComplex *A, magma_minproduct_int_t *lda,
    magma_minproductFloatComplex *tau,
    magma_minproductFloatComplex *work, magma_minproduct_int_t *lwork,
    magma_minproductFloatComplex *T,
    magma_minproduct_int_t *info )
{
    magma_minproduct_cgehrd_m(
        *n, *ilo, *ihi,
        A, *lda,
        tau,
        work, *lwork,
        T,
        info );
}

#define magma_minproductf_cgetrf_m FORTRAN_NAME( magma_minproductf_cgetrf_m, MAGMA_minproductF_CGETRF_M )
void magma_minproductf_cgetrf_m(
    magma_minproduct_int_t *ngpu, magma_minproduct_int_t *m, magma_minproduct_int_t *n,
    magma_minproductFloatComplex *A, magma_minproduct_int_t *lda,
    magma_minproduct_int_t *ipiv,
    magma_minproduct_int_t *info )
{
    magma_minproduct_cgetrf_m(
        *ngpu, *m, *n,
        A, *lda,
        ipiv,
        info );
}

#define magma_minproductf_cheevd_m FORTRAN_NAME( magma_minproductf_cheevd_m, MAGMA_minproductF_CHEEVD_M )
void magma_minproductf_cheevd_m(
    magma_minproduct_int_t *ngpu, const char* jobz, const char* uplo, magma_minproduct_int_t *n,
    magma_minproductFloatComplex *A, magma_minproduct_int_t *lda,
    float *w,
    magma_minproductFloatComplex *work, magma_minproduct_int_t *lwork,
    float *rwork, magma_minproduct_int_t *lrwork,
    magma_minproduct_int_t *iwork, magma_minproduct_int_t *liwork,
    magma_minproduct_int_t *info )
{
    magma_minproduct_cheevd_m(
        *ngpu, magma_minproduct_vec_const(*jobz), magma_minproduct_uplo_const(*uplo), *n,
        A, *lda,
        w,
        work, *lwork,
        rwork, *lrwork,
        iwork, *liwork,
        info );
}

#define magma_minproductf_cheevdx_2stage_m FORTRAN_NAME( magma_minproductf_cheevdx_2stage_m, MAGMA_minproductF_CHEEVDX_2STAGE_M )
void magma_minproductf_cheevdx_2stage_m(
    magma_minproduct_int_t *ngpu, const char* jobz, const char* range, const char* uplo, magma_minproduct_int_t *n,
    magma_minproductFloatComplex *A, magma_minproduct_int_t *lda, float *vl, float *vu, magma_minproduct_int_t *il, magma_minproduct_int_t *iu,
    magma_minproduct_int_t *m,
    float *w,
    magma_minproductFloatComplex *work, magma_minproduct_int_t *lwork,
    float *rwork, magma_minproduct_int_t *lrwork,
    magma_minproduct_int_t *iwork, magma_minproduct_int_t *liwork,
    magma_minproduct_int_t *info )
{
    magma_minproduct_cheevdx_2stage_m(
        *ngpu, magma_minproduct_vec_const(*jobz), magma_minproduct_range_const(*range), magma_minproduct_uplo_const(*uplo), *n,
        A, *lda, *vl, *vu, *il, *iu,
        m,
        w,
        work, *lwork,
        rwork, *lrwork,
        iwork, *liwork,
        info );
}

#define magma_minproductf_cheevdx_m FORTRAN_NAME( magma_minproductf_cheevdx_m, MAGMA_minproductF_CHEEVDX_M )
void magma_minproductf_cheevdx_m(
    magma_minproduct_int_t *ngpu, const char* jobz, const char* range, const char* uplo, magma_minproduct_int_t *n,
    magma_minproductFloatComplex *A, magma_minproduct_int_t *lda, float *vl, float *vu, magma_minproduct_int_t *il, magma_minproduct_int_t *iu,
    magma_minproduct_int_t *m,
    float *w,
    magma_minproductFloatComplex *work, magma_minproduct_int_t *lwork,
    float *rwork, magma_minproduct_int_t *lrwork,
    magma_minproduct_int_t *iwork, magma_minproduct_int_t *liwork,
    magma_minproduct_int_t *info )
{
    magma_minproduct_cheevdx_m(
        *ngpu, magma_minproduct_vec_const(*jobz), magma_minproduct_range_const(*range), magma_minproduct_uplo_const(*uplo), *n,
        A, *lda, *vl, *vu, *il, *iu,
        m,
        w,
        work, *lwork,
        rwork, *lrwork,
        iwork, *liwork,
        info );
}

#define magma_minproductf_chegst_m FORTRAN_NAME( magma_minproductf_chegst_m, MAGMA_minproductF_CHEGST_M )
void magma_minproductf_chegst_m(
    magma_minproduct_int_t *ngpu, magma_minproduct_int_t *itype, const char* uplo, magma_minproduct_int_t *n,
    magma_minproductFloatComplex *A, magma_minproduct_int_t *lda,
    magma_minproductFloatComplex *B, magma_minproduct_int_t *ldb,
    magma_minproduct_int_t *info )
{
    magma_minproduct_chegst_m(
        *ngpu, *itype, magma_minproduct_uplo_const(*uplo), *n,
        A, *lda,
        B, *ldb,
        info );
}

#define magma_minproductf_chegvd_m FORTRAN_NAME( magma_minproductf_chegvd_m, MAGMA_minproductF_CHEGVD_M )
void magma_minproductf_chegvd_m(
    magma_minproduct_int_t *ngpu, magma_minproduct_int_t *itype, const char* jobz, const char* uplo, magma_minproduct_int_t *n,
    magma_minproductFloatComplex *A, magma_minproduct_int_t *lda,
    magma_minproductFloatComplex *B, magma_minproduct_int_t *ldb,
    float *w,
    magma_minproductFloatComplex *work, magma_minproduct_int_t *lwork,
    float *rwork, magma_minproduct_int_t *lrwork,
    magma_minproduct_int_t *iwork, magma_minproduct_int_t *liwork,
    magma_minproduct_int_t *info )
{
    magma_minproduct_chegvd_m(
        *ngpu, *itype, magma_minproduct_vec_const(*jobz), magma_minproduct_uplo_const(*uplo), *n,
        A, *lda,
        B, *ldb,
        w,
        work, *lwork,
        rwork, *lrwork,
        iwork, *liwork,
        info );
}

#define magma_minproductf_chegvdx_2stage_m FORTRAN_NAME( magma_minproductf_chegvdx_2stage_m, MAGMA_minproductF_CHEGVDX_2STAGE_M )
void magma_minproductf_chegvdx_2stage_m(
    magma_minproduct_int_t *ngpu, magma_minproduct_int_t *itype, const char* jobz, const char* range, const char* uplo, magma_minproduct_int_t *n,
    magma_minproductFloatComplex *A, magma_minproduct_int_t *lda,
    magma_minproductFloatComplex *B, magma_minproduct_int_t *ldb, float *vl, float *vu, magma_minproduct_int_t *il, magma_minproduct_int_t *iu,
    magma_minproduct_int_t *m,
    float *w,
    magma_minproductFloatComplex *work, magma_minproduct_int_t *lwork,
    float *rwork, magma_minproduct_int_t *lrwork,
    magma_minproduct_int_t *iwork, magma_minproduct_int_t *liwork,
    magma_minproduct_int_t *info )
{
    magma_minproduct_chegvdx_2stage_m(
        *ngpu, *itype, magma_minproduct_vec_const(*jobz), magma_minproduct_range_const(*range), magma_minproduct_uplo_const(*uplo), *n,
        A, *lda,
        B, *ldb, *vl, *vu, *il, *iu,
        m,
        w,
        work, *lwork,
        rwork, *lrwork,
        iwork, *liwork,
        info );
}

#define magma_minproductf_chegvdx_m FORTRAN_NAME( magma_minproductf_chegvdx_m, MAGMA_minproductF_CHEGVDX_M )
void magma_minproductf_chegvdx_m(
    magma_minproduct_int_t *ngpu, magma_minproduct_int_t *itype, const char* jobz, const char* range, const char* uplo, magma_minproduct_int_t *n,
    magma_minproductFloatComplex *A, magma_minproduct_int_t *lda,
    magma_minproductFloatComplex *B, magma_minproduct_int_t *ldb, float *vl, float *vu, magma_minproduct_int_t *il, magma_minproduct_int_t *iu,
    magma_minproduct_int_t *m,
    float *w,
    magma_minproductFloatComplex *work, magma_minproduct_int_t *lwork,
    float *rwork, magma_minproduct_int_t *lrwork,
    magma_minproduct_int_t *iwork, magma_minproduct_int_t *liwork,
    magma_minproduct_int_t *info )
{
    magma_minproduct_chegvdx_m(
        *ngpu, *itype, magma_minproduct_vec_const(*jobz), magma_minproduct_range_const(*range), magma_minproduct_uplo_const(*uplo), *n,
        A, *lda,
        B, *ldb, *vl, *vu, *il, *iu,
        m,
        w,
        work, *lwork,
        rwork, *lrwork,
        iwork, *liwork,
        info );
}

#define magma_minproductf_cpotrf_m FORTRAN_NAME( magma_minproductf_cpotrf_m, MAGMA_minproductF_CPOTRF_M )
void magma_minproductf_cpotrf_m(
    magma_minproduct_int_t *ngpu, const char* uplo, magma_minproduct_int_t *n,
    magma_minproductFloatComplex *A, magma_minproduct_int_t *lda,
    magma_minproduct_int_t *info )
{
    magma_minproduct_cpotrf_m(
        *ngpu, magma_minproduct_uplo_const(*uplo), *n,
        A, *lda,
        info );
}

#define magma_minproductf_cstedx_m FORTRAN_NAME( magma_minproductf_cstedx_m, MAGMA_minproductF_CSTEDX_M )
void magma_minproductf_cstedx_m(
    magma_minproduct_int_t *ngpu, const char* range, magma_minproduct_int_t *n, float *vl, float *vu, magma_minproduct_int_t *il, magma_minproduct_int_t *iu,
    float *d,
    float *e,
    magma_minproductFloatComplex *Z, magma_minproduct_int_t *ldz,
    float *rwork, magma_minproduct_int_t *lrwork,
    magma_minproduct_int_t *iwork, magma_minproduct_int_t *liwork,
    magma_minproduct_int_t *info )
{
    magma_minproduct_cstedx_m(
        *ngpu, magma_minproduct_range_const(*range), *n, *vl, *vu, *il, *iu,
        d,
        e,
        Z, *ldz,
        rwork, *lrwork,
        iwork, *liwork,
        info );
}

#define magma_minproductf_ctrsm_m FORTRAN_NAME( magma_minproductf_ctrsm_m, MAGMA_minproductF_CTRSM_M )
void magma_minproductf_ctrsm_m(
    magma_minproduct_int_t *ngpu, const char* side, const char* uplo, const char* transa, const char* diag, magma_minproduct_int_t *m, magma_minproduct_int_t *n, magma_minproductFloatComplex *alpha,
    magma_minproductFloatComplex *A, magma_minproduct_int_t *lda,
    magma_minproductFloatComplex *B, magma_minproduct_int_t *ldb )
{
    magma_minproduct_ctrsm_m(
        *ngpu, magma_minproduct_side_const(*side), magma_minproduct_uplo_const(*uplo), magma_minproduct_trans_const(*transa), magma_minproduct_diag_const(*diag), *m, *n, *alpha,
        A, *lda,
        B, *ldb );
}

#define magma_minproductf_cunghr_m FORTRAN_NAME( magma_minproductf_cunghr_m, MAGMA_minproductF_CUNGHR_M )
void magma_minproductf_cunghr_m(
    magma_minproduct_int_t *n, magma_minproduct_int_t *ilo, magma_minproduct_int_t *ihi,
    magma_minproductFloatComplex *A, magma_minproduct_int_t *lda,
    magma_minproductFloatComplex *tau,
    magma_minproductFloatComplex *T, magma_minproduct_int_t *nb,
    magma_minproduct_int_t *info )
{
    magma_minproduct_cunghr_m(
        *n, *ilo, *ihi,
        A, *lda,
        tau,
        T, *nb,
        info );
}

#define magma_minproductf_cungqr_m FORTRAN_NAME( magma_minproductf_cungqr_m, MAGMA_minproductF_CUNGQR_M )
void magma_minproductf_cungqr_m(
    magma_minproduct_int_t *m, magma_minproduct_int_t *n, magma_minproduct_int_t *k,
    magma_minproductFloatComplex *A, magma_minproduct_int_t *lda,
    magma_minproductFloatComplex *tau,
    magma_minproductFloatComplex *T, magma_minproduct_int_t *nb,
    magma_minproduct_int_t *info )
{
    magma_minproduct_cungqr_m(
        *m, *n, *k,
        A, *lda,
        tau,
        T, *nb,
        info );
}

#define magma_minproductf_cunmqr_m FORTRAN_NAME( magma_minproductf_cunmqr_m, MAGMA_minproductF_CUNMQR_M )
void magma_minproductf_cunmqr_m(
    magma_minproduct_int_t *ngpu, const char* side, const char* trans, magma_minproduct_int_t *m, magma_minproduct_int_t *n, magma_minproduct_int_t *k,
    magma_minproductFloatComplex *A, magma_minproduct_int_t *lda,
    magma_minproductFloatComplex *tau,
    magma_minproductFloatComplex *C, magma_minproduct_int_t *ldc,
    magma_minproductFloatComplex *work, magma_minproduct_int_t *lwork,
    magma_minproduct_int_t *info )
{
    magma_minproduct_cunmqr_m(
        *ngpu, magma_minproduct_side_const(*side), magma_minproduct_trans_const(*trans), *m, *n, *k,
        A, *lda,
        tau,
        C, *ldc,
        work, *lwork,
        info );
}

#define magma_minproductf_cunmtr_m FORTRAN_NAME( magma_minproductf_cunmtr_m, MAGMA_minproductF_CUNMTR_M )
void magma_minproductf_cunmtr_m(
    magma_minproduct_int_t *ngpu, const char* side, const char* uplo, const char* trans, magma_minproduct_int_t *m, magma_minproduct_int_t *n,
    magma_minproductFloatComplex *A, magma_minproduct_int_t *lda,
    magma_minproductFloatComplex *tau,
    magma_minproductFloatComplex *C, magma_minproduct_int_t *ldc,
    magma_minproductFloatComplex *work, magma_minproduct_int_t *lwork,
    magma_minproduct_int_t *info )
{
    magma_minproduct_cunmtr_m(
        *ngpu, magma_minproduct_side_const(*side), magma_minproduct_uplo_const(*uplo), magma_minproduct_trans_const(*trans), *m, *n,
        A, *lda,
        tau,
        C, *ldc,
        work, *lwork,
        info );
}

#define magma_minproductf_cgegqr_gpu FORTRAN_NAME( magma_minproductf_cgegqr_gpu, MAGMA_minproductF_CGEGQR_GPU )
void magma_minproductf_cgegqr_gpu(
    magma_minproduct_int_t *ikind, magma_minproduct_int_t *m, magma_minproduct_int_t *n,
    devptr_t *dA, magma_minproduct_int_t *ldda,
    devptr_t *dwork,
    magma_minproductFloatComplex *work,
    magma_minproduct_int_t *info )
{
    magma_minproduct_cgegqr_gpu(
        *ikind, *m, *n,
        magma_minproduct_cdevptr(dA), *ldda,
        magma_minproduct_cdevptr(dwork),
        work,
        info );
}

#define magma_minproductf_cgelqf_gpu FORTRAN_NAME( magma_minproductf_cgelqf_gpu, MAGMA_minproductF_CGELQF_GPU )
void magma_minproductf_cgelqf_gpu(
    magma_minproduct_int_t *m, magma_minproduct_int_t *n,
    devptr_t *dA, magma_minproduct_int_t *ldda,
    magma_minproductFloatComplex *tau,
    magma_minproductFloatComplex *work, magma_minproduct_int_t *lwork,
    magma_minproduct_int_t *info )
{
    magma_minproduct_cgelqf_gpu(
        *m, *n,
        magma_minproduct_cdevptr(dA), *ldda,
        tau,
        work, *lwork,
        info );
}

#define magma_minproductf_cgels_gpu FORTRAN_NAME( magma_minproductf_cgels_gpu, MAGMA_minproductF_CGELS_GPU )
void magma_minproductf_cgels_gpu(
    const char* trans, magma_minproduct_int_t *m, magma_minproduct_int_t *n, magma_minproduct_int_t *nrhs,
    devptr_t *dA, magma_minproduct_int_t *ldda,
    devptr_t *dB, magma_minproduct_int_t *lddb,
    magma_minproductFloatComplex *hwork, magma_minproduct_int_t *lwork,
    magma_minproduct_int_t *info )
{
    magma_minproduct_cgels_gpu(
        magma_minproduct_trans_const(*trans), *m, *n, *nrhs,
        magma_minproduct_cdevptr(dA), *ldda,
        magma_minproduct_cdevptr(dB), *lddb,
        hwork, *lwork,
        info );
}

#define magma_minproductf_cgels3_gpu FORTRAN_NAME( magma_minproductf_cgels3_gpu, MAGMA_minproductF_CGELS3_GPU )
void magma_minproductf_cgels3_gpu(
    const char* trans, magma_minproduct_int_t *m, magma_minproduct_int_t *n, magma_minproduct_int_t *nrhs,
    devptr_t *dA, magma_minproduct_int_t *ldda,
    devptr_t *dB, magma_minproduct_int_t *lddb,
    magma_minproductFloatComplex *hwork, magma_minproduct_int_t *lwork,
    magma_minproduct_int_t *info )
{
    magma_minproduct_cgels3_gpu(
        magma_minproduct_trans_const(*trans), *m, *n, *nrhs,
        magma_minproduct_cdevptr(dA), *ldda,
        magma_minproduct_cdevptr(dB), *lddb,
        hwork, *lwork,
        info );
}

#define magma_minproductf_cgeqp3_gpu FORTRAN_NAME( magma_minproductf_cgeqp3_gpu, MAGMA_minproductF_CGEQP3_GPU )
void magma_minproductf_cgeqp3_gpu(
    magma_minproduct_int_t *m, magma_minproduct_int_t *n,
    devptr_t *dA, magma_minproduct_int_t *ldda,
    magma_minproduct_int_t *jpvt,
    magma_minproductFloatComplex *tau,
    devptr_t *dwork, magma_minproduct_int_t *lwork,
    float *rwork,
    magma_minproduct_int_t *info )
{
    magma_minproduct_cgeqp3_gpu(
        *m, *n,
        magma_minproduct_cdevptr(dA), *ldda,
        jpvt,
        tau,
        magma_minproduct_cdevptr(dwork), *lwork,
        rwork,
        info );
}

#define magma_minproductf_cgeqr2x_gpu FORTRAN_NAME( magma_minproductf_cgeqr2x_gpu, MAGMA_minproductF_CGEQR2X_GPU )
void magma_minproductf_cgeqr2x_gpu(
    magma_minproduct_int_t *m, magma_minproduct_int_t *n,
    devptr_t *dA, magma_minproduct_int_t *ldda,
    devptr_t *dtau,
    devptr_t *dT,
    devptr_t *ddA,
    devptr_t *dwork,
    magma_minproduct_int_t *info )
{
    magma_minproduct_cgeqr2x_gpu(
        *m, *n,
        magma_minproduct_cdevptr(dA), *ldda,
        magma_minproduct_cdevptr(dtau),
        magma_minproduct_cdevptr(dT),
        magma_minproduct_cdevptr(ddA),
        magma_minproduct_sdevptr(dwork),
        info );
}

#define magma_minproductf_cgeqr2x2_gpu FORTRAN_NAME( magma_minproductf_cgeqr2x2_gpu, MAGMA_minproductF_CGEQR2X2_GPU )
void magma_minproductf_cgeqr2x2_gpu(
    magma_minproduct_int_t *m, magma_minproduct_int_t *n,
    devptr_t *dA, magma_minproduct_int_t *ldda,
    devptr_t *dtau,
    devptr_t *dT,
    devptr_t *ddA,
    devptr_t *dwork,
    magma_minproduct_int_t *info )
{
    magma_minproduct_cgeqr2x2_gpu(
        *m, *n,
        magma_minproduct_cdevptr(dA), *ldda,
        magma_minproduct_cdevptr(dtau),
        magma_minproduct_cdevptr(dT),
        magma_minproduct_cdevptr(ddA),
        magma_minproduct_sdevptr(dwork),
        info );
}

#define magma_minproductf_cgeqr2x3_gpu FORTRAN_NAME( magma_minproductf_cgeqr2x3_gpu, MAGMA_minproductF_CGEQR2X3_GPU )
void magma_minproductf_cgeqr2x3_gpu(
    magma_minproduct_int_t *m, magma_minproduct_int_t *n,
    devptr_t *dA, magma_minproduct_int_t *ldda,
    devptr_t *dtau,
    devptr_t *dT,
    devptr_t *ddA,
    devptr_t *dwork,
    magma_minproduct_int_t *info )
{
    magma_minproduct_cgeqr2x3_gpu(
        *m, *n,
        magma_minproduct_cdevptr(dA), *ldda,
        magma_minproduct_cdevptr(dtau),
        magma_minproduct_cdevptr(dT),
        magma_minproduct_cdevptr(ddA),
        magma_minproduct_sdevptr(dwork),
        info );
}

#define magma_minproductf_cgeqr2x4_gpu FORTRAN_NAME( magma_minproductf_cgeqr2x4_gpu, MAGMA_minproductF_CGEQR2X4_GPU )
void magma_minproductf_cgeqr2x4_gpu(
    magma_minproduct_int_t *m, magma_minproduct_int_t *n,
    devptr_t *dA, magma_minproduct_int_t *ldda,
    devptr_t *dtau,
    devptr_t *dT,
    devptr_t *ddA,
    devptr_t *dwork, magma_minproduct_queue_t *queue,
    magma_minproduct_int_t *info )
{
    magma_minproduct_cgeqr2x4_gpu(
        *m, *n,
        magma_minproduct_cdevptr(dA), *ldda,
        magma_minproduct_cdevptr(dtau),
        magma_minproduct_cdevptr(dT),
        magma_minproduct_cdevptr(ddA),
        magma_minproduct_sdevptr(dwork), *queue,
        info );
}

#define magma_minproductf_cgeqrf_gpu FORTRAN_NAME( magma_minproductf_cgeqrf_gpu, MAGMA_minproductF_CGEQRF_GPU )
void magma_minproductf_cgeqrf_gpu(
    magma_minproduct_int_t *m, magma_minproduct_int_t *n,
    devptr_t *dA, magma_minproduct_int_t *ldda,
    magma_minproductFloatComplex *tau,
    devptr_t *dT,
    magma_minproduct_int_t *info )
{
    magma_minproduct_cgeqrf_gpu(
        *m, *n,
        magma_minproduct_cdevptr(dA), *ldda,
        tau,
        magma_minproduct_cdevptr(dT),
        info );
}

#define magma_minproductf_cgeqrf2_gpu FORTRAN_NAME( magma_minproductf_cgeqrf2_gpu, MAGMA_minproductF_CGEQRF2_GPU )
void magma_minproductf_cgeqrf2_gpu(
    magma_minproduct_int_t *m, magma_minproduct_int_t *n,
    devptr_t *dA, magma_minproduct_int_t *ldda,
    magma_minproductFloatComplex *tau,
    magma_minproduct_int_t *info )
{
    magma_minproduct_cgeqrf2_gpu(
        *m, *n,
        magma_minproduct_cdevptr(dA), *ldda,
        tau,
        info );
}

#define magma_minproductf_cgeqrf3_gpu FORTRAN_NAME( magma_minproductf_cgeqrf3_gpu, MAGMA_minproductF_CGEQRF3_GPU )
void magma_minproductf_cgeqrf3_gpu(
    magma_minproduct_int_t *m, magma_minproduct_int_t *n,
    devptr_t *dA, magma_minproduct_int_t *ldda,
    magma_minproductFloatComplex *tau,
    devptr_t *dT,
    magma_minproduct_int_t *info )
{
    magma_minproduct_cgeqrf3_gpu(
        *m, *n,
        magma_minproduct_cdevptr(dA), *ldda,
        tau,
        magma_minproduct_cdevptr(dT),
        info );
}

#define magma_minproductf_cgeqrs_gpu FORTRAN_NAME( magma_minproductf_cgeqrs_gpu, MAGMA_minproductF_CGEQRS_GPU )
void magma_minproductf_cgeqrs_gpu(
    magma_minproduct_int_t *m, magma_minproduct_int_t *n, magma_minproduct_int_t *nrhs,
    devptr_t *dA, magma_minproduct_int_t *ldda,
    magma_minproductFloatComplex *tau,
    devptr_t *dT,
    devptr_t *dB, magma_minproduct_int_t *lddb,
    magma_minproductFloatComplex *hwork, magma_minproduct_int_t *lwork,
    magma_minproduct_int_t *info )
{
    magma_minproduct_cgeqrs_gpu(
        *m, *n, *nrhs,
        magma_minproduct_cdevptr(dA), *ldda,
        tau,
        magma_minproduct_cdevptr(dT),
        magma_minproduct_cdevptr(dB), *lddb,
        hwork, *lwork,
        info );
}

#define magma_minproductf_cgeqrs3_gpu FORTRAN_NAME( magma_minproductf_cgeqrs3_gpu, MAGMA_minproductF_CGEQRS3_GPU )
void magma_minproductf_cgeqrs3_gpu(
    magma_minproduct_int_t *m, magma_minproduct_int_t *n, magma_minproduct_int_t *nrhs,
    devptr_t *dA, magma_minproduct_int_t *ldda,
    magma_minproductFloatComplex *tau,
    devptr_t *dT,
    devptr_t *dB, magma_minproduct_int_t *lddb,
    magma_minproductFloatComplex *hwork, magma_minproduct_int_t *lwork,
    magma_minproduct_int_t *info )
{
    magma_minproduct_cgeqrs3_gpu(
        *m, *n, *nrhs,
        magma_minproduct_cdevptr(dA), *ldda,
        tau,
        magma_minproduct_cdevptr(dT),
        magma_minproduct_cdevptr(dB), *lddb,
        hwork, *lwork,
        info );
}

#define magma_minproductf_cgerbt_gpu FORTRAN_NAME( magma_minproductf_cgerbt_gpu, MAGMA_minproductF_CGERBT_GPU )
void magma_minproductf_cgerbt_gpu(
    const char* gen, magma_minproduct_int_t *n, magma_minproduct_int_t *nrhs,
    devptr_t *dA, magma_minproduct_int_t *ldda,
    devptr_t *dB, magma_minproduct_int_t *lddb,
    magma_minproductFloatComplex *U,
    magma_minproductFloatComplex *V,
    magma_minproduct_int_t *info )
{
    magma_minproduct_cgerbt_gpu(
        magma_minproduct_bool_const(*gen), *n, *nrhs,
        magma_minproduct_cdevptr(dA), *ldda,
        magma_minproduct_cdevptr(dB), *lddb,
        U,
        V,
        info );
}

#define magma_minproductf_cgessm_gpu FORTRAN_NAME( magma_minproductf_cgessm_gpu, MAGMA_minproductF_CGESSM_GPU )
void magma_minproductf_cgessm_gpu(
    const char* order, magma_minproduct_int_t *m, magma_minproduct_int_t *n, magma_minproduct_int_t *k, magma_minproduct_int_t *ib,
    magma_minproduct_int_t *ipiv,
    devptr_t *dL1, magma_minproduct_int_t *lddl1,
    devptr_t *dL, magma_minproduct_int_t *lddl,
    devptr_t *dA, magma_minproduct_int_t *ldda,
    magma_minproduct_int_t *info )
{
    magma_minproduct_cgessm_gpu(
        magma_minproduct_order_const(*order), *m, *n, *k, *ib,
        ipiv,
        magma_minproduct_cdevptr(dL1), *lddl1,
        magma_minproduct_cdevptr(dL), *lddl,
        magma_minproduct_cdevptr(dA), *ldda,
        info );
}

#define magma_minproductf_cgesv_gpu FORTRAN_NAME( magma_minproductf_cgesv_gpu, MAGMA_minproductF_CGESV_GPU )
void magma_minproductf_cgesv_gpu(
    magma_minproduct_int_t *n, magma_minproduct_int_t *nrhs,
    devptr_t *dA, magma_minproduct_int_t *ldda,
    magma_minproduct_int_t *ipiv,
    devptr_t *dB, magma_minproduct_int_t *lddb,
    magma_minproduct_int_t *info )
{
    magma_minproduct_cgesv_gpu(
        *n, *nrhs,
        magma_minproduct_cdevptr(dA), *ldda,
        ipiv,
        magma_minproduct_cdevptr(dB), *lddb,
        info );
}

#define magma_minproductf_cgesv_nopiv_gpu FORTRAN_NAME( magma_minproductf_cgesv_nopiv_gpu, MAGMA_minproductF_CGESV_NOPIV_GPU )
void magma_minproductf_cgesv_nopiv_gpu(
    magma_minproduct_int_t *n, magma_minproduct_int_t *nrhs,
    devptr_t *dA, magma_minproduct_int_t *ldda,
    devptr_t *dB, magma_minproduct_int_t *lddb,
    magma_minproduct_int_t *info )
{
    magma_minproduct_cgesv_nopiv_gpu(
        *n, *nrhs,
        magma_minproduct_cdevptr(dA), *ldda,
        magma_minproduct_cdevptr(dB), *lddb,
        info );
}

#define magma_minproductf_cgetf2_gpu FORTRAN_NAME( magma_minproductf_cgetf2_gpu, MAGMA_minproductF_CGETF2_GPU )
void magma_minproductf_cgetf2_gpu(
    magma_minproduct_int_t *m, magma_minproduct_int_t *n,
    devptr_t *dA, magma_minproduct_int_t *ldda,
    magma_minproduct_int_t *ipiv,
    magma_minproduct_int_t *info )
{
    magma_minproduct_cgetf2_gpu(
        *m, *n,
        magma_minproduct_cdevptr(dA), *ldda,
        ipiv,
        info );
}

#define magma_minproductf_cgetrf_gpu FORTRAN_NAME( magma_minproductf_cgetrf_gpu, MAGMA_minproductF_CGETRF_GPU )
void magma_minproductf_cgetrf_gpu(
    magma_minproduct_int_t *m, magma_minproduct_int_t *n,
    devptr_t *dA, magma_minproduct_int_t *ldda,
    magma_minproduct_int_t *ipiv,
    magma_minproduct_int_t *info )
{
    magma_minproduct_cgetrf_gpu(
        *m, *n,
        magma_minproduct_cdevptr(dA), *ldda,
        ipiv,
        info );
}

#define magma_minproductf_cgetrf_nopiv_gpu FORTRAN_NAME( magma_minproductf_cgetrf_nopiv_gpu, MAGMA_minproductF_CGETRF_NOPIV_GPU )
void magma_minproductf_cgetrf_nopiv_gpu(
    magma_minproduct_int_t *m, magma_minproduct_int_t *n,
    devptr_t *dA, magma_minproduct_int_t *ldda,
    magma_minproduct_int_t *info )
{
    magma_minproduct_cgetrf_nopiv_gpu(
        *m, *n,
        magma_minproduct_cdevptr(dA), *ldda,
        info );
}

#define magma_minproductf_cgetri_gpu FORTRAN_NAME( magma_minproductf_cgetri_gpu, MAGMA_minproductF_CGETRI_GPU )
void magma_minproductf_cgetri_gpu(
    magma_minproduct_int_t *n,
    devptr_t *dA, magma_minproduct_int_t *ldda,
    magma_minproduct_int_t *ipiv,
    devptr_t *dwork, magma_minproduct_int_t *lwork,
    magma_minproduct_int_t *info )
{
    magma_minproduct_cgetri_gpu(
        *n,
        magma_minproduct_cdevptr(dA), *ldda,
        ipiv,
        magma_minproduct_cdevptr(dwork), *lwork,
        info );
}

#define magma_minproductf_cgetrs_gpu FORTRAN_NAME( magma_minproductf_cgetrs_gpu, MAGMA_minproductF_CGETRS_GPU )
void magma_minproductf_cgetrs_gpu(
    const char* trans, magma_minproduct_int_t *n, magma_minproduct_int_t *nrhs,
    devptr_t *dA, magma_minproduct_int_t *ldda,
    magma_minproduct_int_t *ipiv,
    devptr_t *dB, magma_minproduct_int_t *lddb,
    magma_minproduct_int_t *info )
{
    magma_minproduct_cgetrs_gpu(
        magma_minproduct_trans_const(*trans), *n, *nrhs,
        magma_minproduct_cdevptr(dA), *ldda,
        ipiv,
        magma_minproduct_cdevptr(dB), *lddb,
        info );
}

#define magma_minproductf_cgetrs_nopiv_gpu FORTRAN_NAME( magma_minproductf_cgetrs_nopiv_gpu, MAGMA_minproductF_CGETRS_NOPIV_GPU )
void magma_minproductf_cgetrs_nopiv_gpu(
    const char* trans, magma_minproduct_int_t *n, magma_minproduct_int_t *nrhs,
    devptr_t *dA, magma_minproduct_int_t *ldda,
    devptr_t *dB, magma_minproduct_int_t *lddb,
    magma_minproduct_int_t *info )
{
    magma_minproduct_cgetrs_nopiv_gpu(
        magma_minproduct_trans_const(*trans), *n, *nrhs,
        magma_minproduct_cdevptr(dA), *ldda,
        magma_minproduct_cdevptr(dB), *lddb,
        info );
}

#define magma_minproductf_cheevd_gpu FORTRAN_NAME( magma_minproductf_cheevd_gpu, MAGMA_minproductF_CHEEVD_GPU )
void magma_minproductf_cheevd_gpu(
    const char* jobz, const char* uplo, magma_minproduct_int_t *n,
    devptr_t *dA, magma_minproduct_int_t *ldda,
    float *w,
    magma_minproductFloatComplex *wA, magma_minproduct_int_t *ldwa,
    magma_minproductFloatComplex *work, magma_minproduct_int_t *lwork,
    float *rwork, magma_minproduct_int_t *lrwork,
    magma_minproduct_int_t *iwork, magma_minproduct_int_t *liwork,
    magma_minproduct_int_t *info )
{
    magma_minproduct_cheevd_gpu(
        magma_minproduct_vec_const(*jobz), magma_minproduct_uplo_const(*uplo), *n,
        magma_minproduct_cdevptr(dA), *ldda,
        w,
        wA, *ldwa,
        work, *lwork,
        rwork, *lrwork,
        iwork, *liwork,
        info );
}

#define magma_minproductf_cheevdx_gpu FORTRAN_NAME( magma_minproductf_cheevdx_gpu, MAGMA_minproductF_CHEEVDX_GPU )
void magma_minproductf_cheevdx_gpu(
    const char* jobz, const char* range, const char* uplo, magma_minproduct_int_t *n,
    devptr_t *dA, magma_minproduct_int_t *ldda, float *vl, float *vu, magma_minproduct_int_t *il, magma_minproduct_int_t *iu,
    magma_minproduct_int_t *m,
    float *w,
    magma_minproductFloatComplex *wA, magma_minproduct_int_t *ldwa,
    magma_minproductFloatComplex *work, magma_minproduct_int_t *lwork,
    float *rwork, magma_minproduct_int_t *lrwork,
    magma_minproduct_int_t *iwork, magma_minproduct_int_t *liwork,
    magma_minproduct_int_t *info )
{
    magma_minproduct_cheevdx_gpu(
        magma_minproduct_vec_const(*jobz), magma_minproduct_range_const(*range), magma_minproduct_uplo_const(*uplo), *n,
        magma_minproduct_cdevptr(dA), *ldda, *vl, *vu, *il, *iu,
        m,
        w,
        wA, *ldwa,
        work, *lwork,
        rwork, *lrwork,
        iwork, *liwork,
        info );
}

#define magma_minproductf_cheevr_gpu FORTRAN_NAME( magma_minproductf_cheevr_gpu, MAGMA_minproductF_CHEEVR_GPU )
void magma_minproductf_cheevr_gpu(
    const char* jobz, const char* range, const char* uplo, magma_minproduct_int_t *n,
    devptr_t *dA, magma_minproduct_int_t *ldda, float *vl, float *vu, magma_minproduct_int_t *il, magma_minproduct_int_t *iu, float *abstol,
    magma_minproduct_int_t *m,
    float *w,
    devptr_t *dZ, magma_minproduct_int_t *lddz,
    magma_minproduct_int_t *isuppz,
    magma_minproductFloatComplex *wA, magma_minproduct_int_t *ldwa,
    magma_minproductFloatComplex *wZ, magma_minproduct_int_t *ldwz,
    magma_minproductFloatComplex *work, magma_minproduct_int_t *lwork,
    float *rwork, magma_minproduct_int_t *lrwork,
    magma_minproduct_int_t *iwork, magma_minproduct_int_t *liwork,
    magma_minproduct_int_t *info )
{
    magma_minproduct_cheevr_gpu(
        magma_minproduct_vec_const(*jobz), magma_minproduct_range_const(*range), magma_minproduct_uplo_const(*uplo), *n,
        magma_minproduct_cdevptr(dA), *ldda, *vl, *vu, *il, *iu, *abstol,
        m,
        w,
        magma_minproduct_cdevptr(dZ), *lddz,
        isuppz,
        wA, *ldwa,
        wZ, *ldwz,
        work, *lwork,
        rwork, *lrwork,
        iwork, *liwork,
        info );
}

#define magma_minproductf_cheevx_gpu FORTRAN_NAME( magma_minproductf_cheevx_gpu, MAGMA_minproductF_CHEEVX_GPU )
void magma_minproductf_cheevx_gpu(
    const char* jobz, const char* range, const char* uplo, magma_minproduct_int_t *n,
    devptr_t *dA, magma_minproduct_int_t *ldda, float *vl, float *vu, magma_minproduct_int_t *il, magma_minproduct_int_t *iu, float *abstol,
    magma_minproduct_int_t *m,
    float *w,
    devptr_t *dZ, magma_minproduct_int_t *lddz,
    magma_minproductFloatComplex *wA, magma_minproduct_int_t *ldwa,
    magma_minproductFloatComplex *wZ, magma_minproduct_int_t *ldwz,
    magma_minproductFloatComplex *work, magma_minproduct_int_t *lwork,
    float *rwork,
    magma_minproduct_int_t *iwork,
    magma_minproduct_int_t *ifail,
    magma_minproduct_int_t *info )
{
    magma_minproduct_cheevx_gpu(
        magma_minproduct_vec_const(*jobz), magma_minproduct_range_const(*range), magma_minproduct_uplo_const(*uplo), *n,
        magma_minproduct_cdevptr(dA), *ldda, *vl, *vu, *il, *iu, *abstol,
        m,
        w,
        magma_minproduct_cdevptr(dZ), *lddz,
        wA, *ldwa,
        wZ, *ldwz,
        work, *lwork,
        rwork,
        iwork,
        ifail,
        info );
}

#define magma_minproductf_chegst_gpu FORTRAN_NAME( magma_minproductf_chegst_gpu, MAGMA_minproductF_CHEGST_GPU )
void magma_minproductf_chegst_gpu(
    magma_minproduct_int_t *itype, const char* uplo, magma_minproduct_int_t *n,
    devptr_t *dA, magma_minproduct_int_t *ldda,
    devptr_t *dB, magma_minproduct_int_t *lddb,
    magma_minproduct_int_t *info )
{
    magma_minproduct_chegst_gpu(
        *itype, magma_minproduct_uplo_const(*uplo), *n,
        magma_minproduct_cdevptr(dA), *ldda,
        magma_minproduct_cdevptr(dB), *lddb,
        info );
}

#define magma_minproductf_chetrd_gpu FORTRAN_NAME( magma_minproductf_chetrd_gpu, MAGMA_minproductF_CHETRD_GPU )
void magma_minproductf_chetrd_gpu(
    const char* uplo, magma_minproduct_int_t *n,
    devptr_t *dA, magma_minproduct_int_t *ldda,
    float *d,
    float *e,
    magma_minproductFloatComplex *tau,
    magma_minproductFloatComplex *wA, magma_minproduct_int_t *ldwa,
    magma_minproductFloatComplex *work, magma_minproduct_int_t *lwork,
    magma_minproduct_int_t *info )
{
    magma_minproduct_chetrd_gpu(
        magma_minproduct_uplo_const(*uplo), *n,
        magma_minproduct_cdevptr(dA), *ldda,
        d,
        e,
        tau,
        wA, *ldwa,
        work, *lwork,
        info );
}

#define magma_minproductf_chetrd2_gpu FORTRAN_NAME( magma_minproductf_chetrd2_gpu, MAGMA_minproductF_CHETRD2_GPU )
void magma_minproductf_chetrd2_gpu(
    const char* uplo, magma_minproduct_int_t *n,
    devptr_t *dA, magma_minproduct_int_t *ldda,
    float *d,
    float *e,
    magma_minproductFloatComplex *tau,
    magma_minproductFloatComplex *wA, magma_minproduct_int_t *ldwa,
    magma_minproductFloatComplex *work, magma_minproduct_int_t *lwork,
    devptr_t *dwork, magma_minproduct_int_t *ldwork,
    magma_minproduct_int_t *info )
{
    magma_minproduct_chetrd2_gpu(
        magma_minproduct_uplo_const(*uplo), *n,
        magma_minproduct_cdevptr(dA), *ldda,
        d,
        e,
        tau,
        wA, *ldwa,
        work, *lwork,
        magma_minproduct_cdevptr(dwork), *ldwork,
        info );
}

#define magma_minproductf_chetrf_nopiv_gpu FORTRAN_NAME( magma_minproductf_chetrf_nopiv_gpu, MAGMA_minproductF_CHETRF_NOPIV_GPU )
void magma_minproductf_chetrf_nopiv_gpu(
    const char* uplo, magma_minproduct_int_t *n,
    devptr_t *da, magma_minproduct_int_t *ldda,
    magma_minproduct_int_t *info )
{
    magma_minproduct_chetrf_nopiv_gpu(
        magma_minproduct_uplo_const(*uplo), *n,
        magma_minproduct_cdevptr(da), *ldda,
        info );
}

#define magma_minproductf_clarf_gpu FORTRAN_NAME( magma_minproductf_clarf_gpu, MAGMA_minproductF_CLARF_GPU )
void magma_minproductf_clarf_gpu(
    magma_minproduct_int_t *m, magma_minproduct_int_t *n,
    devptr_t *dv,
    devptr_t *dtau,
    devptr_t *dC, magma_minproduct_int_t *lddc )
{
    magma_minproduct_clarf_gpu(
        *m, *n,
        magma_minproduct_cdevptr(dv),
        magma_minproduct_cdevptr(dtau),
        magma_minproduct_cdevptr(dC), *lddc );
}

#define magma_minproductf_clarfb_gpu FORTRAN_NAME( magma_minproductf_clarfb_gpu, MAGMA_minproductF_CLARFB_GPU )
void magma_minproductf_clarfb_gpu(
    const char* side, const char* trans, const char* direct, const char* storev, magma_minproduct_int_t *m, magma_minproduct_int_t *n, magma_minproduct_int_t *k,
    devptr_t *dV, magma_minproduct_int_t *lddv,
    devptr_t *dT, magma_minproduct_int_t *lddt,
    devptr_t *dC, magma_minproduct_int_t *lddc,
    devptr_t *dwork, magma_minproduct_int_t *ldwork )
{
    magma_minproduct_clarfb_gpu(
        magma_minproduct_side_const(*side), magma_minproduct_trans_const(*trans), magma_minproduct_direct_const(*direct), magma_minproduct_storev_const(*storev), *m, *n, *k,
        magma_minproduct_cdevptr(dV), *lddv,
        magma_minproduct_cdevptr(dT), *lddt,
        magma_minproduct_cdevptr(dC), *lddc,
        magma_minproduct_cdevptr(dwork), *ldwork );
}

#define magma_minproductf_clarfb_gpu_gemm FORTRAN_NAME( magma_minproductf_clarfb_gpu_gemm, MAGMA_minproductF_CLARFB_GPU_GEMM )
void magma_minproductf_clarfb_gpu_gemm(
    const char* side, const char* trans, const char* direct, const char* storev, magma_minproduct_int_t *m, magma_minproduct_int_t *n, magma_minproduct_int_t *k,
    devptr_t *dV, magma_minproduct_int_t *lddv,
    devptr_t *dT, magma_minproduct_int_t *lddt,
    devptr_t *dC, magma_minproduct_int_t *lddc,
    devptr_t *dwork, magma_minproduct_int_t *ldwork,
    devptr_t *dworkvt, magma_minproduct_int_t *ldworkvt )
{
    magma_minproduct_clarfb_gpu_gemm(
        magma_minproduct_side_const(*side), magma_minproduct_trans_const(*trans), magma_minproduct_direct_const(*direct), magma_minproduct_storev_const(*storev), *m, *n, *k,
        magma_minproduct_cdevptr(dV), *lddv,
        magma_minproduct_cdevptr(dT), *lddt,
        magma_minproduct_cdevptr(dC), *lddc,
        magma_minproduct_cdevptr(dwork), *ldwork,
        magma_minproduct_cdevptr(dworkvt), *ldworkvt );
}

#define magma_minproductf_clarfb2_gpu FORTRAN_NAME( magma_minproductf_clarfb2_gpu, MAGMA_minproductF_CLARFB2_GPU )
void magma_minproductf_clarfb2_gpu(
    magma_minproduct_int_t *m, magma_minproduct_int_t *n, magma_minproduct_int_t *k,
    devptr_t *dV, magma_minproduct_int_t *lddv,
    devptr_t *dT, magma_minproduct_int_t *lddt,
    devptr_t *dC, magma_minproduct_int_t *lddc,
    devptr_t *dwork, magma_minproduct_int_t *ldwork )
{
    magma_minproduct_clarfb2_gpu(
        *m, *n, *k,
        magma_minproduct_cdevptr(dV), *lddv,
        magma_minproduct_cdevptr(dT), *lddt,
        magma_minproduct_cdevptr(dC), *lddc,
        magma_minproduct_cdevptr(dwork), *ldwork );
}

#define magma_minproductf_clauum_gpu FORTRAN_NAME( magma_minproductf_clauum_gpu, MAGMA_minproductF_CLAUUM_GPU )
void magma_minproductf_clauum_gpu(
    const char* uplo, magma_minproduct_int_t *n,
    devptr_t *dA, magma_minproduct_int_t *ldda,
    magma_minproduct_int_t *info )
{
    magma_minproduct_clauum_gpu(
        magma_minproduct_uplo_const(*uplo), *n,
        magma_minproduct_cdevptr(dA), *ldda,
        info );
}

#define magma_minproductf_cposv_gpu FORTRAN_NAME( magma_minproductf_cposv_gpu, MAGMA_minproductF_CPOSV_GPU )
void magma_minproductf_cposv_gpu(
    const char* uplo, magma_minproduct_int_t *n, magma_minproduct_int_t *nrhs,
    devptr_t *dA, magma_minproduct_int_t *ldda,
    devptr_t *dB, magma_minproduct_int_t *lddb,
    magma_minproduct_int_t *info )
{
    magma_minproduct_cposv_gpu(
        magma_minproduct_uplo_const(*uplo), *n, *nrhs,
        magma_minproduct_cdevptr(dA), *ldda,
        magma_minproduct_cdevptr(dB), *lddb,
        info );
}

#define magma_minproductf_cpotf2_gpu FORTRAN_NAME( magma_minproductf_cpotf2_gpu, MAGMA_minproductF_CPOTF2_GPU )
void magma_minproductf_cpotf2_gpu(
    const char* uplo, magma_minproduct_int_t *n,
    devptr_t *dA, magma_minproduct_int_t *ldda,
    magma_minproduct_int_t *info )
{
    magma_minproduct_cpotf2_gpu(
        magma_minproduct_uplo_const(*uplo), *n,
        magma_minproduct_cdevptr(dA), *ldda,
        info );
}

#define magma_minproductf_cpotrf_gpu FORTRAN_NAME( magma_minproductf_cpotrf_gpu, MAGMA_minproductF_CPOTRF_GPU )
void magma_minproductf_cpotrf_gpu(
    const char* uplo, magma_minproduct_int_t *n,
    devptr_t *dA, magma_minproduct_int_t *ldda,
    magma_minproduct_int_t *info )
{
    magma_minproduct_cpotrf_gpu(
        magma_minproduct_uplo_const(*uplo), *n,
        magma_minproduct_cdevptr(dA), *ldda,
        info );
}

#define magma_minproductf_cpotri_gpu FORTRAN_NAME( magma_minproductf_cpotri_gpu, MAGMA_minproductF_CPOTRI_GPU )
void magma_minproductf_cpotri_gpu(
    const char* uplo, magma_minproduct_int_t *n,
    devptr_t *dA, magma_minproduct_int_t *ldda,
    magma_minproduct_int_t *info )
{
    magma_minproduct_cpotri_gpu(
        magma_minproduct_uplo_const(*uplo), *n,
        magma_minproduct_cdevptr(dA), *ldda,
        info );
}

#define magma_minproductf_cpotrs_gpu FORTRAN_NAME( magma_minproductf_cpotrs_gpu, MAGMA_minproductF_CPOTRS_GPU )
void magma_minproductf_cpotrs_gpu(
    const char* uplo, magma_minproduct_int_t *n, magma_minproduct_int_t *nrhs,
    devptr_t *dA, magma_minproduct_int_t *ldda,
    devptr_t *dB, magma_minproduct_int_t *lddb,
    magma_minproduct_int_t *info )
{
    magma_minproduct_cpotrs_gpu(
        magma_minproduct_uplo_const(*uplo), *n, *nrhs,
        magma_minproduct_cdevptr(dA), *ldda,
        magma_minproduct_cdevptr(dB), *lddb,
        info );
}

#define magma_minproductf_cssssm_gpu FORTRAN_NAME( magma_minproductf_cssssm_gpu, MAGMA_minproductF_CSSSSM_GPU )
void magma_minproductf_cssssm_gpu(
    const char* order, magma_minproduct_int_t *m1, magma_minproduct_int_t *n1, magma_minproduct_int_t *m2, magma_minproduct_int_t *n2, magma_minproduct_int_t *k, magma_minproduct_int_t *ib,
    devptr_t *dA1, magma_minproduct_int_t *ldda1,
    devptr_t *dA2, magma_minproduct_int_t *ldda2,
    devptr_t *dL1, magma_minproduct_int_t *lddl1,
    devptr_t *dL2, magma_minproduct_int_t *lddl2,
    magma_minproduct_int_t *ipiv,
    magma_minproduct_int_t *info )
{
    magma_minproduct_cssssm_gpu(
        magma_minproduct_order_const(*order), *m1, *n1, *m2, *n2, *k, *ib,
        magma_minproduct_cdevptr(dA1), *ldda1,
        magma_minproduct_cdevptr(dA2), *ldda2,
        magma_minproduct_cdevptr(dL1), *lddl1,
        magma_minproduct_cdevptr(dL2), *lddl2,
        ipiv,
        info );
}

#define magma_minproductf_ctrtri_gpu FORTRAN_NAME( magma_minproductf_ctrtri_gpu, MAGMA_minproductF_CTRTRI_GPU )
void magma_minproductf_ctrtri_gpu(
    const char* uplo, const char* diag, magma_minproduct_int_t *n,
    devptr_t *dA, magma_minproduct_int_t *ldda,
    magma_minproduct_int_t *info )
{
    magma_minproduct_ctrtri_gpu(
        magma_minproduct_uplo_const(*uplo), magma_minproduct_diag_const(*diag), *n,
        magma_minproduct_cdevptr(dA), *ldda,
        info );
}

#define magma_minproductf_cungqr_gpu FORTRAN_NAME( magma_minproductf_cungqr_gpu, MAGMA_minproductF_CUNGQR_GPU )
void magma_minproductf_cungqr_gpu(
    magma_minproduct_int_t *m, magma_minproduct_int_t *n, magma_minproduct_int_t *k,
    devptr_t *dA, magma_minproduct_int_t *ldda,
    magma_minproductFloatComplex *tau,
    devptr_t *dT, magma_minproduct_int_t *nb,
    magma_minproduct_int_t *info )
{
    magma_minproduct_cungqr_gpu(
        *m, *n, *k,
        magma_minproduct_cdevptr(dA), *ldda,
        tau,
        magma_minproduct_cdevptr(dT), *nb,
        info );
}

#define magma_minproductf_cunmql2_gpu FORTRAN_NAME( magma_minproductf_cunmql2_gpu, MAGMA_minproductF_CUNMQL2_GPU )
void magma_minproductf_cunmql2_gpu(
    const char* side, const char* trans, magma_minproduct_int_t *m, magma_minproduct_int_t *n, magma_minproduct_int_t *k,
    devptr_t *dA, magma_minproduct_int_t *ldda,
    magma_minproductFloatComplex *tau,
    devptr_t *dC, magma_minproduct_int_t *lddc,
    magma_minproductFloatComplex *wA, magma_minproduct_int_t *ldwa,
    magma_minproduct_int_t *info )
{
    magma_minproduct_cunmql2_gpu(
        magma_minproduct_side_const(*side), magma_minproduct_trans_const(*trans), *m, *n, *k,
        magma_minproduct_cdevptr(dA), *ldda,
        tau,
        magma_minproduct_cdevptr(dC), *lddc,
        wA, *ldwa,
        info );
}

#define magma_minproductf_cunmqr_gpu FORTRAN_NAME( magma_minproductf_cunmqr_gpu, MAGMA_minproductF_CUNMQR_GPU )
void magma_minproductf_cunmqr_gpu(
    const char* side, const char* trans, magma_minproduct_int_t *m, magma_minproduct_int_t *n, magma_minproduct_int_t *k,
    devptr_t *dA, magma_minproduct_int_t *ldda,
    magma_minproductFloatComplex *tau,
    devptr_t *dC, magma_minproduct_int_t *lddc,
    magma_minproductFloatComplex *hwork, magma_minproduct_int_t *lwork,
    devptr_t *dT, magma_minproduct_int_t *nb,
    magma_minproduct_int_t *info )
{
    magma_minproduct_cunmqr_gpu(
        magma_minproduct_side_const(*side), magma_minproduct_trans_const(*trans), *m, *n, *k,
        magma_minproduct_cdevptr(dA), *ldda,
        tau,
        magma_minproduct_cdevptr(dC), *lddc,
        hwork, *lwork,
        magma_minproduct_cdevptr(dT), *nb,
        info );
}

#define magma_minproductf_cunmqr2_gpu FORTRAN_NAME( magma_minproductf_cunmqr2_gpu, MAGMA_minproductF_CUNMQR2_GPU )
void magma_minproductf_cunmqr2_gpu(
    const char* side, const char* trans, magma_minproduct_int_t *m, magma_minproduct_int_t *n, magma_minproduct_int_t *k,
    devptr_t *dA, magma_minproduct_int_t *ldda,
    magma_minproductFloatComplex *tau,
    devptr_t *dC, magma_minproduct_int_t *lddc,
    magma_minproductFloatComplex *wA, magma_minproduct_int_t *ldwa,
    magma_minproduct_int_t *info )
{
    magma_minproduct_cunmqr2_gpu(
        magma_minproduct_side_const(*side), magma_minproduct_trans_const(*trans), *m, *n, *k,
        magma_minproduct_cdevptr(dA), *ldda,
        tau,
        magma_minproduct_cdevptr(dC), *lddc,
        wA, *ldwa,
        info );
}

#define magma_minproductf_cunmtr_gpu FORTRAN_NAME( magma_minproductf_cunmtr_gpu, MAGMA_minproductF_CUNMTR_GPU )
void magma_minproductf_cunmtr_gpu(
    const char* side, const char* uplo, const char* trans, magma_minproduct_int_t *m, magma_minproduct_int_t *n,
    devptr_t *dA, magma_minproduct_int_t *ldda,
    magma_minproductFloatComplex *tau,
    devptr_t *dC, magma_minproduct_int_t *lddc,
    magma_minproductFloatComplex *wA, magma_minproduct_int_t *ldwa,
    magma_minproduct_int_t *info )
{
    magma_minproduct_cunmtr_gpu(
        magma_minproduct_side_const(*side), magma_minproduct_uplo_const(*uplo), magma_minproduct_trans_const(*trans), *m, *n,
        magma_minproduct_cdevptr(dA), *ldda,
        tau,
        magma_minproduct_cdevptr(dC), *lddc,
        wA, *ldwa,
        info );
}

#define magma_minproductf_cnan_inf FORTRAN_NAME( magma_minproductf_cnan_inf, MAGMA_minproductF_CNAN_INF )
void magma_minproductf_cnan_inf(
    const char* uplo, magma_minproduct_int_t *m, magma_minproduct_int_t *n,
    const magma_minproductFloatComplex *A, magma_minproduct_int_t *lda,
    magma_minproduct_int_t *cnt_nan,
    magma_minproduct_int_t *cnt_inf )
{
    magma_minproduct_cnan_inf(
        magma_minproduct_uplo_const(*uplo), *m, *n,
        A, *lda,
        cnt_nan,
        cnt_inf );
}

#define magma_minproductf_cnan_inf_gpu FORTRAN_NAME( magma_minproductf_cnan_inf_gpu, MAGMA_minproductF_CNAN_INF_GPU )
void magma_minproductf_cnan_inf_gpu(
    const char* uplo, magma_minproduct_int_t *m, magma_minproduct_int_t *n,
    devptr_t *dA, magma_minproduct_int_t *ldda,
    magma_minproduct_int_t *cnt_nan,
    magma_minproduct_int_t *cnt_inf )
{
    magma_minproduct_cnan_inf_gpu(
        magma_minproduct_uplo_const(*uplo), *m, *n,
        magma_minproduct_cdevptr(dA), *ldda,
        cnt_nan,
        cnt_inf );
}

#define magma_minproductf_cprint FORTRAN_NAME( magma_minproductf_cprint, MAGMA_minproductF_CPRINT )
void magma_minproductf_cprint(
    magma_minproduct_int_t *m, magma_minproduct_int_t *n,
    const magma_minproductFloatComplex *A, magma_minproduct_int_t *lda )
{
    magma_minproduct_cprint(
        *m, *n,
        A, *lda );
}

#define magma_minproductf_cprint_gpu FORTRAN_NAME( magma_minproductf_cprint_gpu, MAGMA_minproductF_CPRINT_GPU )
void magma_minproductf_cprint_gpu(
    magma_minproduct_int_t *m, magma_minproduct_int_t *n,
    devptr_t *dA, magma_minproduct_int_t *ldda )
{
    magma_minproduct_cprint_gpu(
        *m, *n,
        magma_minproduct_cdevptr(dA), *ldda );
}


#ifdef __cplusplus
}
#endif
